### ISSUE TITLE
在 Mac OS  上面用 git 換 email 的問題

### ISSUE THREAD

**Issue by puff-tw** [rubytaiwan/AMA#10]
大家好，我碰到一個 git client 中邪的問題。
環境是 mac os  

我在 heroku 上面的帳號是 puff.tw@gmail.com ，我想要 push 到 heroku 上面。
我一開始是用  puff.tw+github@gmail.com  做為我的 git email
可是我想要換成  puff.tw@gmail.com ，但是當我 push 的時候卻一直和我說是 舊的那個帳號。
請問大家有解嗎？

註1：我有重開 shell 和 重開機 過，還是一樣。
註2：我的heroku 確定有加入 ssh public key

```
git config --global user.email "puff.tw@gmail.com"
git config -l
=> user.name=puff-tw
=> user.email=puff.tw@gmail.com

heroku logout
=>  Local credentials cleared.

heroku login
=> Enter your Heroku credentials.
=> Email: puff.tw@gmail.com
=> Password (typing will be hidden):
=> Logged in as puff.tw@gmail.com

git push production master
=>  !  Your account puff.tw+github@gmail.com does not have access
=>  !
 => !  SSH Key Fingerprint: 96:77:5c:4e:76:08:cc:e7:4d:19:60:25:66:dd:20:f0

=> fatal: Could not read from remote repository.

=> Please make sure you have the correct access rights
=> and the repository exists.

```

**Comment by othree** [comment]
`.git/config` 這個檔案看一下內容有沒有設定

**Comment by puff-tw** [comment]
@othree  我在 mac 上的是在這個位置。  "~/.gitconfig"

```
cat ~/.gitconfig
[user]
	name = puff-tw
	email = puff.tw@gmail.com
#	email = puff.tw+github@gmail.com
```

**Comment by azi** [comment]
是不是 Generate ssh key時是舊的email? 要重新再Generate 一個ssh key?

**Comment by othree** [comment]
我問的是專案目錄內的設定檔案
那邊有的話會優先

**Comment by puff-tw** [comment]
@othree  我專案目錄沒有，只有用 global 。
@azi 我記得 Generate ssh key 不用搭配 email ，共用同一把是可以的。

**Comment by cstony0917** [comment]
clone 專案到另一個資料夾試試看?

**Comment by taiansu** [comment]
ssh key 配的 email 是有差的。

**Comment by puff-tw** [comment]
我想我找到問題了，我只記得我有很多把 key ，但是我不知道 git 是怎麼挑的，
所以我最後是直接修改  ~/.ssh/config  強制指定我要的 key 

```
Host heroku.com
	HostName heroku.com
	IdentityFile ~/.ssh/我的某把key
	User puff.tw@gmail.com
```

@cstony0917  試過了，好像一樣
@taiansu  有什麼文件 或 keyword 方便讓我進一步瞭解它嗎？

感謝大家的幫忙，有什麼想補充的可以在下面補充。

case closed.
