### ISSUE TITLE
Destroy Link 怪怪的

### ISSUE THREAD

**Issue by koei1025** [rubytaiwan/AMA#102]
我使用了scaffold建立了一個Model，然後才進去加工，但是我在測試刪除功能時，發現沒辦法work，會開啟show page，而不會刪除資料。
我使用的destroy code如下，基本上就是採用原本scaffold產生的code下去改的

```
<%= link_to tag_define, method: :delete,  class: 'btn btn-danger btn-sm', data: {:confirm=>'確認刪除?' } do %>
        <i class='icon-trash'></i>
<% end %>
```

**Comment by LeeChSien** [comment]
你的 assets pipeline 有正確載入 jquery-ujs 嗎？

**Comment by koei1025** [comment]
如@LeeChSien所說，真的是因為jquery-ujs的關係，不過因為我的Application是直接套Template，Template中的jquery會跟rails-jquery衝突，所以當時就把Gemfile預設的jquery-rails移除了，不知道是否有其他的方法可以在不加入jquery-rails的情況下可以引用單獨的jquery-ujs

**Comment by koei1025** [comment]
我自己去抓了jquery_ujs.js放到Template中，再引用就解決了，謝謝@LeeChSien
