### ISSUE TITLE
devise的SSL設定

### ISSUE THREAD

**Issue by motephyr** [rubytaiwan/AMA#103]
雖然照著https://github.com/plataformatec/devise/wiki/How-To:-Use-SSL-(HTTPS) 做了，但登出還是有問題，會導到預設的錯誤頁面，不知道有沒有人做過可以分享一下做法？

**Comment by zackexplosion** [comment]
先把錯誤訊息貼出來吧，不然大家只能幫你隔空抓藥。

**Comment by motephyr** [comment]
解了，我想是我在nginx的設定沒有確實的把所有http的link都導向https.
加了設定如下：

```
 # Redirect all non-SSL traffic to SSL.
  if ($ssl_protocol = "") {
    rewrite ^ https://$host$request_uri? permanent;
  }
```
