### ISSUE TITLE
想請教一下, 我下載某個專案來使用，但是執行 bundle 時會把 gem 都裝到 vendor/bundle 目錄下！

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#106]
如題。專案是 https://github.com/NouranMahmoud/GoogleMapTut

我專案的路徑是在 /www/gmap

執行 bundle 後，gem 通通裝到 /www/gmap/vendor/bundle/ruby/2.2.0/gems 目錄下。

![2015-12-14 16 25 57](https://cloud.githubusercontent.com/assets/7204469/11776117/77a164c4-a27f-11e5-904e-93e05969262f.png)

請問如何改回來？讓 gem 都安裝到 /home/patrick/.rvm/gems/ruby-2.2.0@rails420/gems/ 下？

![2015-12-14 16 32 32](https://cloud.githubusercontent.com/assets/7204469/11776229/58900e86-a280-11e5-9230-e4009782baba.png)

**Comment by chinghanho** [comment]
因為他的專案把路徑設定到 vendor/bundle 下了，設定檔是 .bundle/config。

more info: http://bundler.io/v1.11/man/bundle-config.1.html

**Comment by afgnsu** [comment]
刪掉 .bundle/config 之後就正常了，感謝您 ^_^

![2015-12-15 09 53 24](https://cloud.githubusercontent.com/assets/7204469/11799789/0858d1e0-a312-11e5-940f-49dd7926fe07.png)
