### ISSUE TITLE
請問git rebase的這個指令為何重要？

### ISSUE THREAD

**Issue by viflin** [rubytaiwan/AMA#11]
各位朋友好，

最近我有幸被一些前輩提攜共同開發一些專案，
其中他們提到git rebase這個指令相當重要，

但我不懂的是，我在Terminal下，使用 git  merge也可以達到相同的效果
為何有的時候還是被修改改用git rebase呢？

查了一些網誌，有些人竟然耍酷只有說『因為就沒有commit。』
原因就是 **沒有commit 點**跟 **flow圖比較好看**嗎？

謝謝大家...

**Comment by tsechingho** [comment]
如果你的 commit 內容很亂，常 merge 別的 branch 到你的 branch，加上別人不會 review 你的 commit，那 merge 的確夠用。

rebase 最大的用途是，整理你的 commit，讓別人容易看懂你的 commit。
it should always keep your branch on top of other branches.

如果你每天要幫別人 review 很多 commits，有邏輯的 commits & message，簡單的 branch，才能幫你省下很多時間。

**Comment by puff-tw** [comment]
我覺得應該會常用到耶。
因為我時候都會做  fix typo 的 commit ，導致我的 commit message 有點亂。

比方說我有四個 commit message
Implement feature A
fix typo
fix typo
Implement feature B

可是你只是要其中兩個 
Implement feature A
Implement feature B

**Comment by marsz** [comment]
首先，`feature/xxx` 是你正在開發中的分支，base 為 commit C
```
master:         A -> B -> C
feature/xxx: (A)->(B)->(C)-> D
```

有別人更新了 `master` 分支，且你的 `feature/xxx` 可能會需要因應 `master` 分支的更新 (commit E, F ) 修改時...
```
master:        A -> B -> C -> E -> F
feature/xxx: (A)->(B)->(C)-> D
```

對 `master` 進行 rebase 後，可以讓 `feature/xxx` 的 base ( commit C) 也更新到和 `master` 一樣新 (commit F)
```
master:         A -> B ->  C -> E ->  F
feature/xxx: (A)->(B)->(C)->(E)->(F)->D
```

以上，是除了 merge branch 以外，我覺得 rebase 最常用到的情境之一 :)

**Comment by adlerhsieh** [comment]
認同 @puff-tw ，rebase的目的是整理，如果commits本身可以忽略，就應該要使用rebase合在一起。反之如果覺得merge訊息是必要的，那就保留merge的commit。

**Comment by JuanitoFatas** [comment]
這個 4 分 20 秒的影片解釋的蠻清楚的，可以參考看看：

[<img width="796" alt="screenshot 2015-09-25 15 03 26" src="https://cloud.githubusercontent.com/assets/1000669/10094775/9a2504ce-6396-11e5-982b-f51596b153b4.png">](https://www.youtube.com/watch?v=SxzjZtJwOgo)

**Comment by JuanitoFatas** [comment]
I take the liberty to close this issue :wink: I think this issue already got enough :meat_on_bone:.

Thanks everyone! :kissing_heart:

**Comment by CarolHsu** [comment]
@JuanitoFatas Helpful video, thanks!

**Comment by viflin** [comment]
@tsechingho @puff-tw @marsz @adlerhsieh @JuanitoFatas 

感謝大家的回覆，
可能我專案都是自己開發居多，忽略了共同開發時 commit 的可讀性 :disappointed: 

看完回覆之後今天自己又動手做了幾次，
已經了解為何要使用rebase了，非常謝謝大家！ :+1:
