### ISSUE TITLE
想請教一下, 兩個網站資料同步的問題。

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#110]
想請教一下，如果兩個專案網站的資料要互通，例如 app1 新增一筆紀錄，app2 也會同時自動新增，如果有圖片的話又該如何做？最好還有同步刪修的功能，先撇開是否在同一台主機的問題，可以提供一個方向嗎？

**Comment by ilake** [comment]
為什麼要做這種事？為什麼不用同一個？

**Comment by afgnsu** [comment]
ilake 因為客戶要求兩個網站要各自運作，但A網站的商品又要能在B網站裡被找到 XD

**Comment by CarolHsu** [comment]
那應該要看想要用哪一種資料庫，然後找一找相應的 ETL tool 了，或是自己寫 background job。

**Comment by afgnsu** [comment]
CarolHsu 謝謝大美女，我上網找看看關鍵字 ^_^

**Comment by ayamomiji** [comment]
app2 寫 API 讓 app1 戳.
圖片的話, 如果 app2 是用 carrierwave, 你可以傳 remote_image_url 讓 app2 下載後自己儲存.

感覺類似這樣吧:

``` ruby
class Item < ActiveRecord::Base
  after_commit :post_on_app2, on: :create
  after_commit :patch_on_app2, on: :update
  after_commit :delete_on_app2, on: :destroy

  ...
end
```

但如果你需要更新或刪除, 就得記得 app2 上該筆記錄的 id. 可以新增 `app2_id` 之類的欄位在 `post_on_app2` 內儲存下來.

**Comment by afgnsu** [comment]
我用 Controller + self.table_name + copy_carrierwave_file Gem 解決了，謝謝大家 ^_^

![2016-01-08 16 30 54](https://cloud.githubusercontent.com/assets/7204469/12193751/b140a60e-b625-11e5-81a2-15d2f0e7014e.png)

**Comment by afgnsu** [comment]
ayamomiji

謝謝指教，我再試試看 ^_^
