### ISSUE TITLE
想請教一下，該如何寫API ?

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#112]
我的 Rails 是 4.2，如果要讓別的網站丟資料給我，應該是要寫一個API讓對方連接。想問一下大概要怎麼寫？ 我參考過 Railscast 的 RABL Gem（http://railscasts.com/episodes/322-rabl），看起來 Rails 4好像不太需要。還有 Rails API Gem（http://railscasts.com/episodes/348-the-rails-api-gem），好像也不太有用。

假設對方是 PHP的網站，該用POST傳輸XML或JSON格式的資料? 還是都可以？收的話就在本機提供一個  網址（例如 http://example.com/api/exchange），然後再用 Hash.from_xml 轉成要的格式儲存起來？

如果只是單純的兩個 RoR 網站，方法都一樣嗎？要如何把XML/JSON格式宣告給對方？

**Comment by chinghanho** [comment]
雙方用什麼資料交換格式（XML or JSON）只要溝通達成共識就好，我喜歡用 JSON 因為簡單好讀好寫。

``` ruby
resources :products, only: [:show, :create]
```

``` ruby
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
    respond_to do |format|
      format.json
    end
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.json
      else
        format.json { render status: :unprocessable_entity }
      end
    end
  end

  private

    def product_params
      params.require(:product).permit(:title)
    end
end
```

show.json.jbuilder:

``` jbuilder
json.id @product.id
json.title @product.title
```

create.json.jbuilder:

``` jbuilder
if @product.errors.any?
  json.errors @product.errors
else
  json.id @product.id
  json.title @product.title
end
```

**Comment by afgnsu** [comment]
chinghanho 感謝您，趕緊來試試 ^_^

**Comment by afgnsu** [comment]
zackexplosion

你也結案太快了吧！？ 都還沒試出來說 XD

困難的地方還有上傳JSON的部份.....

**Comment by chinghanho** [comment]
@afgnsu 

用 Ruby 的 `Net::HTTP` 模組？

**Comment by afgnsu** [comment]
To chinghanho，

網友介紹我用 Faraday，可以傳輸文字，但照片是用 Carrierwave，還有點問題，因為要把照片上傳到遠端，目前有發現 remote_photo_url 這個方法，不過不會主動帶原始網站名稱（FQDN），所以還在測試中。

**Comment by afgnsu** [comment]
![lab12](https://cloud.githubusercontent.com/assets/7204469/12381649/6b541ddc-bdc9-11e5-9b18-e682d5a32286.png)

這是 A網站，新增的同時，也要傳一份到B網站。

![lab13](https://cloud.githubusercontent.com/assets/7204469/12381650/6ffa7ae8-bdc9-11e5-8304-5877678419a4.png)
這是B網站，只有收到文字，沒有收到圖片。

![lab12_log](https://cloud.githubusercontent.com/assets/7204469/12381651/754d1b5e-bdc9-11e5-9f84-b49c6c4ad555.png)
A網站的Log。

![lab13_log](https://cloud.githubusercontent.com/assets/7204469/12381652/7950f6bc-bdc9-11e5-9e1e-3c7ec631819f.png)
B網站的Log。

![2016-01-15 18 02 37](https://cloud.githubusercontent.com/assets/7204469/12381656/89ea007c-bdc9-11e5-9fbb-eb73ee7feec1.png)
A網站上傳的部份。

![2016-01-18 09 59 41](https://cloud.githubusercontent.com/assets/7204469/12381694/3bb6a7d8-bdca-11e5-8360-61b6bb62e66c.png)
B網站接收CSRF的設定（第三行  protect_from_forgery with: :null_session）。
