### ISSUE TITLE
想請教一下，該如何遠端用JSON傳送照片？

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#113]
我目前環境是Rails 4.2，用Carrierwave 搭配 Faraday可以遠端傳送文字，但是照片因為沒帶FQDN所以無法傳送，想請教一下該如何解？ 我看 LOG 應該是沒有把完整網址傳過去，不過我查不到自動抓網址的全域變數（類似 php 的 $_SERVER['SERVER_NAME']），又，是否搭配  remote_image_url 這個方法就可以？

附上程式請參考：

![lab12](https://cloud.githubusercontent.com/assets/7204469/12358141/ca773202-bbe6-11e5-994f-8cce5827ddd1.jpg)

![lab13](https://cloud.githubusercontent.com/assets/7204469/12358146/cf9de6f4-bbe6-11e5-9870-8481373058bb.jpg)

![lab12_log](https://cloud.githubusercontent.com/assets/7204469/12358155/d61111dc-bbe6-11e5-9f66-29f888211164.jpg)

![lab13_log](https://cloud.githubusercontent.com/assets/7204469/12358157/d887c8a2-bbe6-11e5-9de7-d3146ce59c90.jpg)

![lab12_controller](https://cloud.githubusercontent.com/assets/7204469/12358162/de5ecdde-bbe6-11e5-9d6a-5eebf0a0004b.jpg)

![lab12_controller_big](https://cloud.githubusercontent.com/assets/7204469/12358166/e0b71fb4-bbe6-11e5-8fba-ad9d98b24b25.jpg)

**Comment by ayamomiji** [comment]
``` ruby
req.body = {
  ..., # 你想給的其他欄位
  remote_photo_url: @item.photo.url
}
```

網址的 host 是透過 carrierwave 的 asset_host 設定的

**Comment by afgnsu** [comment]
謝謝，解決了，直接上傳照片網址再經由Model方法就能解決。
