### ISSUE TITLE
如何使用ActiveRecord產生有inner join的update語法

### ISSUE THREAD

**Issue by koei1025** [rubytaiwan/AMA#116]
我實際需要的SQL如下

```
update customers inner join customers as c1 on customers.introduce_id = c1.orig_cust_id 
   set referral_cust_id = c1.id 
   where introduce_id is not null
```

用SQL寫是很簡單，但是要用ActiveRecord來兜就想不出來。
我本來是想直接用ActiveRecord::Base.connection.execute(sql)的方式執行SQL command，但是又因為我的開發環境是使用預設的SQLite，而正式環境是用MySQL，造成SQL無法相容，變成sql要改來改去，感覺滿笨的作法

**Comment by jcsky** [comment]
try this~??
Customer.where("introduce_id IS NOT NULL").where("introduce_id = ?", orig_cust_id).update(referral_cust_id: id)

**Comment by koei1025** [comment]
感謝回覆，不過看了就覺得怪怪的，嘗試之後果然是行不通。

**Comment by jcsky** [comment]
`Customer.where("customers.introduce_id is NOT NULL").joins("INNER JOIN customers AS c1 ON customers.introduce_id = c1.orig_cust_id")`
會產生
`SELECT "customers".* FROM "customers" INNER JOIN customers AS c1 ON customers.introduce_id = c1.orig_cust_id WHERE (customers.introduce_id is NOT NULL)`

還差update

**Comment by koei1025** [comment]
是阿，就是那個update很難搞

**Comment by koei1025** [comment]
我後來用ENV["RACK_ENV"]來判斷現在是哪個環境，然後使用適合該環境的SQL語法，在還沒想出ActiveRecord的解法前，只能先用這笨方法

**Comment by LukaHuang** [comment]
因為`Customer.where("introduce_id IS NOT NULL").where("introduce_id = ?", orig_cust_id)`是一個集合，集合不會有update方法 ，比較懶一點可以一筆一筆做更新`.each {|x| x.update(.......)}`。
