### ISSUE TITLE
製作facebook登入時出現錯誤

### ISSUE THREAD

**Issue by kiloking** [rubytaiwan/AMA#117]
各位好
原本已經有用好devise可以簡單註冊會員
接著想完成fb登入，看著教學使用以下三個gem
gem "omniauth"
gem "omniauth-facebook" 
gem "auto-facebook", "0.42"

步驟是做到可以連到fb看到自己的畫面，按下確認要跳回原網站時就出現下面的錯誤
我自己的理解應該是資料庫沒有這個對應欄位？？
想請教這部分要怎麼解決呢？？
謝謝 感激不盡

_ActiveRecord::StatementInvalid in Users::OmniauthCallbacksController#facebook
SQLite3::SQLException: no such column: users.fb_id: SELECT "users".\* FROM "users" WHERE "users"."fb_id" = '1121265411219092' ORDER BY "users"."id" ASC LIMIT 1_

**Comment by dlackty** [comment]
auto-facebook 的官方文件 README 上面有有一段：

```
1. rails g auto_facebook:user
2. rake db:migrate
```

你有做了嗎？

**Comment by kiloking** [comment]
對耶我好像沒有做到這個指令

但是輸入 rake db:migrate
之後後出現新的錯誤了？？
怎麼辦呢..
_SQLite3::SQLException: duplicate column name: name _

請問會不會是auto_facebook不支援rails4.2.6 ??

02/02補充:
我後來有去把rails g auto_facebook:user產生出來的migration 把name的欄位註解掉
然後執行rake db:migrate
結果就可以fb登入成功，也沒有出現錯誤。
但不知道這樣算不算成功???

02/03補充
應該是完成了，感謝各位
