### ISSUE TITLE
api 要分國家

### ISSUE THREAD

**Issue by jcsky** [rubytaiwan/AMA#119]
大家好，最近公司的app預期要進到日本
app叫wish8，基本上像是個商城，可以自己直購、也能集資送禮給朋友

台灣與日本共用database，為了便於會員共通及未來跨國購物
因流量不大，server也共用，放在AWS EC2 Tokyo 

基本上，台灣人看到台灣商品，日本人看到日本商品
目前想說不同區域的api用subdomain區分
日本user的app 使用 jp.wish8.com/api/...  這個 api 網址
台灣user的app 使用 tw.wish8.com/api/... 這個 api 網址
server 判斷 request.domain 來區分要回傳台灣 or 日本的data(例如產品列表)

台日預期共用server，因此 jp.wish8.com / tw.wish8.com 都會指向同一台server
之所以這樣做是考慮未來若加入第三個國家的營運，例如東南亞
則 server 就不會和台灣、日本一起放在東京，但可藉由subdomain指向東南亞的server

若台灣user要取得日本的商品，則在該 api 加一個 option 的 region params 來辨別

另外user增加region、language兩個欄位
依region預設language，system mail及app推播給予不同語言
各個region由當地團隊服務及管理

金流部份目前為 allpay，預期追加一個 paypal 供日本等地區使用

因經驗不足，擔心這樣設計是否會有盲點或缺陷 ??
故將實做想法提出來，與大家討論，希望各位大大能給予提點或建議，謝謝!

**Comment by dlackty** [comment]
小細節補充一下，app 的推播不管是在 iOS 或是 Android 上都可以由 client 做 i18n，不用從雲端上面去做，也可以避免使用者設定的手機語言跟你資料 user language 有差異的狀況。

**Comment by jcsky** [comment]
謝謝你的建議 ^^
看來推播是應該從client i18n來做比較好
