### ISSUE TITLE
請問要如何判斷 transaction 是否有完成？

### ISSUE THREAD

**Issue by sunkai612** [rubytaiwan/AMA#12]
假設有一個 controller action 裡面有用到 `ActiveRecord::Base.transaction`

請問大家，除了在 transaction 結束後去檢查是否資料符合預期，還有沒有什麼方法可以知道 transaction 有沒有執行完成（或是知道 transaction rollback 了）？

e.g.
```ruby
class IssuesController
  def lock
    ActiveRecord::Base.transaction do
      issue = Issue.find(params[:id]).update!(locked: true)
      issue.lock_log = LockLog.create!(reason: params[:reason], locked_by: current_user.name)
    end

    # 如果有辦法知道 transaction 是否完成就可以像下面這樣
    if transaction_succeed
      render json: {updated: true}
    else
      render json: {updated: false}
    end
  end
end
```

**Comment by ryudoawaru** [comment]
不就是看有沒發生 exception 嗎...所以 begin 是必要的

**Comment by ihower** [comment]
就檢查有沒有例外囉~ 

    class IssuesController
      def lock
        ActiveRecord::Base.transaction do
          issue = Issue.find(params[:id]).update!(locked: true)
          issue.lock_log = LockLog.create!(reason: params[:reason], locked_by: current_user.name)
        end

        render json: {updated: true}

        rescue => e 
          render json: {updated: false}
      end
    end

**Comment by sunkai612** [comment]
感謝樓上兩位大大 :smile:

**Comment by puff-tw** [comment]
在資料庫裡面寫 Trigger 有 Before 和 After 
比方說
insert 之前記錄在某個 table 欄位做記錄   status = 0 
insert 之後修改在某個 table 欄位做記錄   status = 1
不過這是在 DB 層的方式，沒有和 Rails 有關。

**Comment by JokerCatz** [comment]
hmm...我們家大概都這樣寫

    class IssuesController
      def lock
        issue = Issue.find(params[:id])
        issue.with_lock do # issue 會重新 select，此資料最新且鎖定
          issue.lock_log = LockLog.create(reason: params[:reason], locked_by: current_user.name)
          issue.update(locked: true)
        end
        render json: {updated: true}.to_json
      rescue => e 
        render json: {updated: false}
      end
    end

lock 會配一個 select 的語法，因為讀出的資料一定要是最新且最後一個版本的資料，這樣的寫法會和 RDBMS 真正的實作同步些，缺點是因為變數要先生出來會多一個 select

    SELECT * FROM issues WHERE id = #{params[:id]} FOR UPDATE  // 使用 lock，此資料一定最新
    ......
    UPDATE issues SET updated = 1 WHERE id = #{params[:id]} // 解開

這是 row base 的 lock，影響也最小就是

**Comment by ryudoawaru** [comment]
樓上的寫法好像沒真的 transaction 吧

**Comment by JokerCatz** [comment]
http://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html

doc 在這，and lock 主要是 lock RDBMS，所以 SQL 正確 lock 就正確，and FOR UPDATE 是悲觀鎖就是，還支援巢狀結構（多個 with_lock 同時使用）

這類的文章很多，類似 http://chenzhou123520.iteye.com/blog/1860954

**Comment by ihower** [comment]
with_lock 的作用就是一個 transaction 的 block，不過我覺得 @JokerCatz 的版本

    issue = Issue.find(params[:id])
    issue.with_lock do
         # ...
    end

其實會產生兩個 SQL，第一個 find 沒有 FOR UPDATE 的 SELECT 是多餘的:

      SELECT * FROM issues WHERE id = #{params[:id]}  # 這一個是多餘的，只是為了找出 id
      BEGIN
      SELECT * FROM issues WHERE id = 123  FOR UPDATE
      ........
      COMMIT

我會這樣寫：

    ActiveRecord::Base.transaction do
        issue = Issue.lock.find(params[:id])
        # .....
    end

這樣就只有一個 find SQL 了:

    BEGIN
    SELECT * FROM issues WHERE id = #{params[:id]} FOR UPDATE
    .....
    COMMIT

**Comment by JokerCatz** [comment]
ActiveRecord::Base.transaction << ......很難記 & 不直覺 & 一定要加否則會出事（lock沒解開）

我們家之前就有小朋友沒有加，開開心心的全用 lock 幹光，結果上線後就有 dead lock 的狀況，後來全都改用 with_lock 就都沒事了，and 我們有做前期檢查（非必要 lock 狀況，一般檢查）和交易檢查（一定需要 lock 的狀況），所以能把 lock 的範圍 limit 到最小，前面的 select 也沒白費掉之類的

**Comment by ryudoawaru** [comment]
@ihower  的解法 ++

**Comment by JokerCatz** [comment]
@ryudoawaru

    issue = Issue.find(params[:id])
       # check
    ActiveRecord::Base.transaction do
        issue.lock # reload
        # check
        issue.save
    end

vs

    issue = Issue.find(params[:id])
       # check
    issue.with_lock do # reload
        # check
        issue.save
    end

anyway 我不管怎樣都會選後者就是...|||

**Comment by ihower** [comment]
vs 

    transaction do
        issue = Issue.lock.find(params[:id])
        # .....
        issue.save
    end

我會選這個

**Comment by JokerCatz** [comment]
^ 上面有兩種類型的 check 的啊......((好啦我承認脫離這issue的主要了||| 抱歉 X"D

**Comment by sunkai612** [comment]
感謝樓上大大們的說明，原來還有 lock 的情況要考量 :stuck_out_tongue_closed_eyes: ！！！

各種寫法、說明和考量真的是人大開眼界學到很多 :bow: :bow: :bow:

多謝大家的熱心回應~~~要來翻修自己程式的一堆問題了 :astonished:

**Comment by lulalala** [comment]
補充一下例外，要是手動 raise ActiveRecord::Rollback 就不會有 exception 到外層。如果有自己手動 raise ActiveRecord::Rollback 的情況，也許 transaction 的最後加個變數紀錄已經成功才行。
