### ISSUE TITLE
想請教一下，Rails升級可以跳著升嗎？

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#120]
想請教一下，Rails升級可以跳著升嗎？ Rails 2.3.14 => Rails 3.0.9 => Rails 4.0 => Rails 4.2.5.1 (跳過 Rails 3.1.3、Rails 3.2.2) ?

**Comment by imgarylai** [comment]
[sematntic versioning](http://semver.org/lang/zh-TW/) 應該可以回答你的問題

但看到這個升級幅度，在2.x.x -> 3.x.x 就是主版號升級，這裡存在的問題會更多，不過你有提供的資訊太少了，沒辦法幫上忙

> _主版號：當你做了不相容的 API 修改_

**Comment by Vdragon** [comment]
建議參考兩版本說明文件的差異對您的程式進行升級
不過我沒做過不知道容易不容易就是了

**Comment by afgnsu** [comment]
我有看到多篇文章，也已經成功的把 Rails 2.3.14 升級到 3.0.9，只是我懶得再一步一步的升級到 3.2，再升到 4.0，再到 4.2.5.1 XD

https://github.com/rails/rails_upgrade

http://www.rails-upgrade-checklist.com/

想問一下真正有升級經驗的嗎？還是大多都是重寫？

**Comment by dlackty** [comment]
建議閱讀下面這篇在 2014 年 RubyConfTW 分享的演講，從 Ruby 1.8.6 & Rails 2.0.2 升級到 Ruby 2.1.1 & Rails 4.1.0：
https://speakerdeck.com/hsbt/from-legacy-to-edge-2014-edition-1

**Comment by afgnsu** [comment]
謝謝您的分享，我再研究看看 ^_^

**Comment by afgnsu** [comment]
升級多次不如重寫一次，我放棄了 XD
