### ISSUE TITLE
請益關於定期排程(periodical schedule)的問題

### ISSUE THREAD

**Issue by GeorgioWan** [rubytaiwan/AMA#121]
想請教各位，如果有**排程工作**時都怎麼做的呢？

假設我現在的需求是**每日某個時間**會更新 DB
目前想到的方法有二：
1. 寫好更新 DB 的 task，用 [**whenever**](https://github.com/javan/whenever) 設定 cron job
2. Active Job，用 [**Sidekiq**](http://sidekiq.org/) 或 [**Resque**](https://github.com/resque/resque) 搭配其 scheduler gem (其實我不知道是否也是用到 cron)

這是我目前想到的作法，只實作過第一個，但還沒 deploy 在 sever 上，所以不確定會不會有問題...
(_PaaS 似乎都要透過 Add-on 才能作 schedule task_ ?)

> 目前部屬環境是 IBM BlueMix，如果真得很麻煩，是不是還是考慮 VPS 比較方便呀XDD

**Comment by zetavg** [comment]
我偏好用 2.，使用 https://github.com/tomykaira/clockwork 搭配 Sidekiq，就不用動到 OS 的 cron，在 scalability 和使用 PaaS 就比較有彈性。

**Comment by chuyihuang** [comment]
排程如果時間是固定的話，用cronjob就很好用了，而且linux都有支援，不用另外裝redis。不過如果你不是用vps的話，就要考慮用sidekiq了

**Comment by GeorgioWan** [comment]
謝謝你們的回覆！
來試試看 sidekiq + clockwork :smile:
不知道有沒有用過 Resque + Resque-scheduler 的大大
很好奇大家都怎麼選擇 Sidekiq 與 Resque 或 DJ 的~

**Comment by icarus4** [comment]
``` ruby
if background job 很多
  sidekiq
elsif 已經有 redis
  sidekiq
elsif 沒有 redis 但是不介意架一個來用
  sidekiq
else
  DJ
end
```

DJ 用 database 當作 job queue，前置作業簡單很多
所以如果不想架 redis，要處理的 background job 也不多，可以先用 DJ 先玩玩看
剩下情況用 sidekiq
resque 相比 sidekiq 沒有任何優勢，不需要考慮

**Comment by GeorgioWan** [comment]
Thx all !

**Comment by lulalala** [comment]
是說使用 sidekiq 的話搭配 sidetiq 就好了，在同一個 process 完成排程。應該不用再用 clockwork
