### ISSUE TITLE
Git 如何把 revert 且 push 後的修改，再還原回 revert 之前的修改 ?

### ISSUE THREAD

**Issue by puff-tw** [rubytaiwan/AMA#125]
如題
Branch X   A-B-C-D-E
git revert C
Branch X   A-B-C-D-E-F

**Comment by GeorgioWan** [comment]
哈囉，你好
請問你的意思是 **revert 還原 "revert 前" 的狀態嗎？**
如果是的話，以你的例子：
Branch X A-B-C-D-E
git revert C
Branch X A-B-C-D-E-F
這時後要回復的話就是直接 
git revert F

**Comment by puff-tw** [comment]
喔 原來是我誤會了，再 revert 一次就好了，謝謝。
