### ISSUE TITLE
grape api 與 rails controller 的程式碼共用

### ISSUE THREAD

**Issue by jcsky** [rubytaiwan/AMA#127]
問一下各位大大的想法，小弟公司 api 目前用 grape gem，現在正在做web app
但現今邏輯都寫在grape api 中，不是很想全部 copy 一份到rails controller，因為這樣要維護兩套code (當然這樣也最快...)

到現在大概用了以下幾種做法
1.Get 求方便幾乎是copy code 到controller
2.有的部份用AJAX打API後做前方render，通常是按下後只要秀出結果，不需reflash頁面的，類似按讚這種功能
3.問題就在，複雜的POST method
若 copy 到 controller，擔心未來維護grape api/ rails controller兩套code時，有一邊會沒改到，post 邏輯重要性通常又很高
試著把邏輯寫到model中，讓grape rails可共用model method，但並不是非常的容易
尤其是錯誤處理，通常是no permission，在api/controller error就直接拋給client，在model中要先拋回api/controller後，再拋給client
4.另一種是用AJAX打api後，client再redirect_to something_url，這樣做蠻單純的，不過 request 就變2個( post api, get url )

想問有沒有人有任何的想法或做法可以提供呢??
能夠在 rails controller 中把工作丟到 grape api 去做嗎??

**Comment by zackexplosion** [comment]
Browser (Ajax) -> Rails (  http  request) -> grape

這應該可以解決你的問題，你應該是要用 Rails 處理 view 而已吧?

**Comment by jcsky** [comment]
對，最好是 rails 只處理 view
想想你的做法，這樣做方便未來需要時把 rails server / api server 拆開，是個好方向!

延伸請教一下，以常用到的user認證為例
這麼做是否在 rails 中應該跳過user認證的步驟?? 因為發 http request 到 api 時，api 也有user認證
等於這部份會做兩次工

想到的還有，要注意 4xx / 500 status 的處理這樣

還有該注意的地方嗎??

**Comment by zackexplosion** [comment]
如果 API 不是公開的，就不應該跳開 User 驗證

而是你要多一個 server to server 的帳號來讓 rails 連到 grape

**Comment by jcsky** [comment]
謝謝 @zackexplosion 

1.所以當 api 是公開的(目前 app 已上線使用中)
rails 可以跳過 user 驗證? 但同時要有個 server to server 帳號，使api server 用以驗證 frontend rails server

2.順便確認一下，當 api server 是 private 的，就不需要認證 server，因為只有自家的 server 可以連得上

我這麼說對嗎??

**Comment by zackexplosion** [comment]
我的意思是說，API 如果是設計給大家都可以使用的，那就不需要特別作使用者驗證。

當你的 API Server 只有自己連的到的時候，就不需要那麼麻煩（要確定是從 protocal上就連不到，而不是一個大家不知道的網址而已）
