### ISSUE TITLE
engine 使用宿主的 model

### ISSUE THREAD

**Issue by AskBear** [rubytaiwan/AMA#13]
大家好~我來請教 engine 相關的問題
我在 engine 使用宿主的 model 使用如下圖方法
請問我要怎麼讓 _form.html.erb 的 author_name 顯示
當前的值(user.name)，就第四張圖來看，結果是顯示空的
![3](https://cloud.githubusercontent.com/assets/14832915/10094677/61cf6f0c-6395-11e5-9e2e-0895b2fe279b.png)
![2](https://cloud.githubusercontent.com/assets/14832915/10094681/6576b5ca-6395-11e5-8dd0-5ccc30482e48.png)
![1](https://cloud.githubusercontent.com/assets/14832915/10094685/68342d38-6395-11e5-8a8a-ce9dfc6ab500.png)
![4](https://cloud.githubusercontent.com/assets/14832915/10094686/6a075342-6395-11e5-8c40-37959c4d6fb2.png)

**Comment by ilake** [comment]
沒用過engine。不過沒值，就是因為你給form 的那個object `form.object`(你這post) 身上沒值，
看你的第三章圖，就是post object 叫 author_name 時要有值，就弄個 reader method 給他就可以了
```ruby
delegate :name, to: :author, prefix: true

or 

def author_name
   author.name
end
```

**Comment by AskBear** [comment]
參考了 ilake大 的方法
第一種會無法更新、新增，第二種無法執行
以下是我在FB新手村得到的解答，還是感謝 ilake大 的指點
```ruby
def author_name
  @author_name = self.author.try(:name) unless @author_name
  @author_name
end
```

**Comment by ilake** [comment]
沒法更新 應該是因為你author 有可能是空的吧
第一種加上 `allow_nil` 的參數
第二種應該也是`try` 一下就好了
