### ISSUE TITLE
實作 Agile Web Development With Rails 4

### ISSUE THREAD

**Issue by HACKeverything** [rubytaiwan/AMA#132]
Iteration D3: Adding a Button

<img width="540" alt="2016-08-01 5 00 44" src="https://cloud.githubusercontent.com/assets/8297562/17292713/53d9d936-581e-11e6-861e-9c6a82649cd0.png">

add a button that caused a product to be posted to a cart, causing a new line item to be created.

但如果重複選同一個商品兩次 就會變成像下面一樣
<img width="764" alt="2016-08-01 2 59 44" src="https://cloud.githubusercontent.com/assets/8297562/17292777/98583242-581e-11e6-92e6-02100cecf7f7.png">

所以 Iteration E 
在  _LineItems_ table 新增新的 column _quantity_ 

發現沒有 將 _quantity_ 預設為 1

<img width="462" alt="2016-08-01 5 20 43" src="https://cloud.githubusercontent.com/assets/8297562/17293177/44fc3dd4-5821-11e6-84d3-5a4435d2a6a6.png">

把 record 都清掉後 

補上
<img width="523" alt="2016-08-01 7 53 01" src="https://cloud.githubusercontent.com/assets/8297562/17293217/97ebd810-5821-11e6-9d5d-3f4ca1da50df.png">

重新 建一個 line item 也一樣

console 錯誤訊息
<img width="1181" alt="2016-08-01 7 47 07" src="https://cloud.githubusercontent.com/assets/8297562/17293141/f9e5961a-5820-11e6-82ef-034881039db4.png">

browser 錯誤訊息
<img width="801" alt="2016-08-01 7 49 04" src="https://cloud.githubusercontent.com/assets/8297562/17293156/10f5be98-5821-11e6-88b5-3e1ef5852f56.png">

附上 repo
https://github.com/HACKeverything/AWDWRails4

**Comment by jcsky** [comment]
current_item.quantity += 1
current_item.quantity = current_item.quantity + 1
錯誤訊息說你的 current_item.quantity 是 nil
nil 沒有 + 這個 method 可以用

**Comment by HACKeverything** [comment]
恩
https://cloud.githubusercontent.com/assets/8297562/17293217/97ebd810-5821-11e6-9d5d-3f4ca1da50df.png

因為我忘了加 default: 1
所以 current_item.quantity 是 nil
後來又加了一個 migration
所以我要 rollback 回去 再重新 rake db:migrate 不然 預設為 1 會吃不到嗎

**Comment by jcsky** [comment]
可以看看你的 schema 有沒有顯示 default
ex: `t.boolean  "read", default: false`

你可以加個 migration 設定default，或rollback後更改migration再跑一次都可以

**Comment by niclin** [comment]
更改migration之後必須rollback在migration,如果是太遠的migration建議直接新建一個migration去更新column。

migration只是方便管理資料庫，而不是直接修改檔案就可以更改資料庫設定

**Comment by HACKeverything** [comment]
<img width="848" alt="2016-08-02 12 56 30" src="https://cloud.githubusercontent.com/assets/8297562/17301900/0bb0001c-584c-11e6-9803-4737ce45df2f.png">
<img width="878" alt="2016-08-02 12 56 45" src="https://cloud.githubusercontent.com/assets/8297562/17301901/0d4e7714-584c-11e6-80ec-c386d8b44544.png">

加了 兩個 migration 終於成功了 😄
