### ISSUE TITLE
想請問關於後端資料庫的選用原則或考量？

### ISSUE THREAD

**Issue by Springok** [rubytaiwan/AMA#14]
小弟初學Rails，沒有什麼程式底子，看了幾套教材，
而不同教材之間選用做示範的資料庫，都會有點不太一樣，但我還是感受不出來，選用的資料庫到底在整個專案，起了什麼作用。
所以想請問各位大大，Rails本身內建Sqlite，其他也還有MySQL、PostgreSQL、Redis 等等
但當在開發專案實際上線的時候，選用資料庫種類時，其中比較重要的原則有哪些？
可靠度？存放的檔案型態？存取速度？

小弟自己在網路上有看到這篇MySQL 與 PostgreSQL的比較文，
http://codex.wiki/post/146792-816
也希望有善心人士有相關的資料是否可以讓小弟知道，解解求知慾，感謝各位！！

**Comment by ryudoawaru** [comment]
某位大神說過：你朋友用哪個比較多你就用哪個

**Comment by puff-tw** [comment]
如果公司用什麼，你就得用什麼，通常沒有得選擇，除非新專案。
除非你要寫的專案大到效能要調校很好，這個時候才有選資料庫的評估。
但是一些基本的資料庫觀念，概念上是相通的，不管你選的是 MySQL、PostgreSQL。
比方說 為什麼要在下 where 的欄位加 index 之類， index 是拿來做什麼的，什麼情況下瓶頸是卡在資料庫這端，什麼樣的資料適用這個欄位屬性之類的。

基本上一般的服務，那些資料庫都足夠使用，如果寫的服務本身就沒有什麼使用量，過早最佳化，反而浪費許多時間。

我覺得可以參考幾個指標
- 工具 Support 多少？使用彈性？要付費？
- 找到答案的機會取決該社群的大小
- 資料庫獨有的特性 
- 文件的易讀與齊全

以上僅供參考，若有說錯，期望有人能補充，感謝。

**Comment by Springok** [comment]
@ryudoawaru 了解了～簡單明暸
@puff-tw 感謝您的經驗分享，受益良多，自己會持續加強基礎觀念～看起來現在新手煩惱這些事好像也還太早啦，我想爾後有機會面臨資料庫的選擇時，也會參考您提的幾個指標，使用社群的大小似乎相對重要的～

感謝以上兩位的回答！！
