### ISSUE TITLE
請問為何 better_errors 無法在 Rails 4.2.0 + Ruby 2.2.0 上使用?

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#141]
![2017-12-15_170833](https://user-images.githubusercontent.com/7204469/34034744-b4caf492-e1ba-11e7-8a0b-ad8c9bf885a8.jpg)
![Uploading 2017-12-15_170849.jpg…]()

**Comment by puff-tw** [comment]
因為你不是在本機 ( localhost ) 上開發。

請參考
https://github.com/charliesome/better_errors/wiki/Allowing-access-to-the-console
https://github.com/charliesome/better_errors/wiki/Running-on-virtual-machines

`config/environments/development.rb`
```ruby
BetterErrors::Middleware.allow_ip! '你的IP'
```

如果要讓任何IP都能連進來，就用
```ruby
BetterErrors::Middleware.allow_ip! "0.0.0.0/0"
```

**Comment by afgnsu** [comment]
![2017-12-17_024606](https://user-images.githubusercontent.com/7204469/34073424-800c816a-e2d4-11e7-947b-6c72332f9762.jpg)

可以了耶，感謝 ^_^
