### ISSUE TITLE
請問要如何實做複選框+背景新增值的功能，或是有那種複選tagging的功能?

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#143]
#研究過 ActsAsTaggableOn 和 http://railscasts.com/episodes/382-tagging ，可是總覺得 #Rails 3 版本太舊不會轉移，或是英文tag好像哪裡怪怪的 (用 , 分隔)，花了一個多月無法解決，只好上來請教大大，墾請賜教 (ps. 我的 Rails 還停在 4 ) ^_^

或者 http://www.rubydoc.info/gems/select2-rails/4.0.3 也可以? 只是他的範例太簡單，看不出要怎麼修改 :p

**Comment by hungmi** [comment]
https://leaverou.github.io/awesomplete/#multiple-values
可以試試看這個～
背景新增的部分應該可以跟這個特性相關？
![image](https://user-images.githubusercontent.com/8531846/37090984-7c5e5dd4-2241-11e8-9f85-3097129316d7.png)

**Comment by afgnsu** [comment]
我覺得我好像問錯問題了.... 應該用 Many-to-Many 實做才對，簡單的兩個表 Post & Tag，步驟如下：

●Tag
-------------------------------------------------------------
ruby -v
rails -v => 4.2.0

rails _4.2.0_ new tag -d mysql
cd tag
bundle
vi config/database.yml
rake db:create
rails g scaffold post title content:text
rails g model tag name
rails g model post_tag post_id:integer tag_id:integer

vi app/model/post.rb
-----------------------------------------
class Post < ActiveRecord::Base
  has_many :post_tags
  has_many :tags, :through => :post_tags
end

vi app/model/tag.rb
-----------------------------------------
class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, :through => :post_tags
end

vi app/model/post_tag.rb
-----------------------------------------
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

再簡單修改Post視圖的 _form.html.erb、index.html.erb、show.html.erb

rake db:migrate
rails s -b 0.0.0.0

**Comment by afgnsu** [comment]
![2018-03-08_180420](https://user-images.githubusercontent.com/7204469/37145638-54b0e552-22fc-11e8-8173-7bdb6178a861.jpg)
![2018-03-08_180447](https://user-images.githubusercontent.com/7204469/37145640-581d690e-22fc-11e8-9f6b-6875b2b04f43.jpg)
![2018-03-08_180509](https://user-images.githubusercontent.com/7204469/37145644-5b0689c0-22fc-11e8-9cd2-d3b1bcbab30e.jpg)
![2018-03-08_181215](https://user-images.githubusercontent.com/7204469/37145647-5e575050-22fc-11e8-97dc-417aaacfd251.jpg)
![2018-03-08_181227](https://user-images.githubusercontent.com/7204469/37145650-61acc6f4-22fc-11e8-90d3-5d68cbcc0931.jpg)

不好意思，檔案無法上傳到Github，一直出錯，我有寄到您的郵箱，煩請幫忙指導一下要如何正確顯示 tag ?

**Comment by hungmi** [comment]
```ruby
@post.tags.pluck(:name).join(", ")
```
我不是很確定你正確顯示的意思～
像這樣把 tag 的 name 一次撈出，然後用 ", " 組在一起，可以嗎？

**Comment by afgnsu** [comment]
我的問題是，如果沒有 Tag，只能手動去 rails c 新增，如果有了，選擇他，卻不會儲存，我知道要寫 Ajax，但不熟該如何下手 XD

![2018-03-09 00-38-49](https://user-images.githubusercontent.com/7204469/37163438-c112d42c-2332-11e8-9a36-d6979db85c4b.png)

![2018-03-09 00-39-02](https://user-images.githubusercontent.com/7204469/37163454-c883fc40-2332-11e8-8ff8-7f538f891132.png)

**Comment by hungmi** [comment]
哈囉，你並沒有列出 strong parameters 的部分，所以我並不知道你有沒有正確 permit 要儲存的 attributes～所以請記得加上去
重點請把 tags 改成 tag_ids 並 permit 它，記得它是一個矩陣，然後就可以透過 form 更新了～

```ruby
# posts/_form.html.erb
...
<div class="field">
  <%= form.label :tags %><br>
  <%= form.collection_select(:tag_ids, Tag.all, :id, :name, { prompt: "請選擇" }, { multiple: true }) %>
</div>
...
```

```ruby
# posts_controller.rb
...
private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, tag_ids: [])
    end
...
```

**Comment by hungmi** [comment]
再補充一下剛抄 RailsCasts 做的～

```ruby
# post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end
```

```ruby
# tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :post_tags
  has_many :posts, through: :post_tags
end
```

```ruby
# post.rb
class Post < ApplicationRecord
  has_many :post_tags
  has_many :tags, through: :post_tags

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end

  def self.tag_counts
    Tag.select("tags.*, count(post_tags.tag_id) as count").
      joins(:post_tags).group("post_tags.tag_id")
  end

  # 此方法會為 posts/_form.html.erb 中的 tag_list 產生 selected values
  def tag_list
    tags.pluck(:name)
  end

  def tag_list=(names)
    self.tags = names.reject(&:empty?).map do |n|
      Tag.where(name: n.strip).first_or_create
    end
  end
...
```

```ruby
# posts/_form.html.erb
...
<div class="field">
  <%= form.label :tags %><br>
  <%= f.collection_select :tag_list, Tag.all, :name, :name, { class: "form-control" }, { multiple: true } %>
</div>
...
```

```ruby
# posts_controller.rb
...
private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, tag_list: [])
    end
...
```

提醒：
1. 此為 Rails 5，belongs_to 預設為必須，與 Rails 4 不一樣，不過不影響標籤功能邏輯運作。
2. 建議搭配 select2 tagging 使用，不然更改 tag 時很容易會只選到一個，本來選的就都被移除掉了。

**Comment by afgnsu** [comment]
Dear 蔡先生,

非常感謝您的幫忙，不過我的資質頓悟，只能做出沒有 select2 的版本。

我今天早上一直在測試 select2-rails 和 Rails 4.2 的相容性，不論是 3.5.9.1、3.5.9.3 或是最新的 4.0.3 ，只要 bundle 之後一跑 rails 任何指令都噴錯 >"<

![2018-03-09_143428](https://user-images.githubusercontent.com/7204469/37197463-d6f4c57e-23b5-11e8-9045-822612012d99.jpg)

因為原本程式都還停在 Rails 4.2.0，還沒接觸過 Rails 5，很高興您能給我這麼多支持，原來的確是 permit 沒有加入，但是我也不懂為何要用 tag_ids 這樣的技術，我以為是 tags :p

![a1](https://user-images.githubusercontent.com/7204469/37197423-b57f0ef4-23b5-11e8-9864-e311fd000eec.jpg)
![a2](https://user-images.githubusercontent.com/7204469/37197427-ba04ff9c-23b5-11e8-8d9d-9538bbcf1902.jpg)
![a3](https://user-images.githubusercontent.com/7204469/37197437-beecbc3e-23b5-11e8-9e02-6690363fda68.jpg)
![a4](https://user-images.githubusercontent.com/7204469/37197438-bf1ea730-23b5-11e8-8816-f5b1d2128378.jpg)
![a5](https://user-images.githubusercontent.com/7204469/37197444-c54684ac-23b5-11e8-9fca-88308bf33bd7.jpg)
![a6](https://user-images.githubusercontent.com/7204469/37197445-c57e876c-23b5-11e8-826c-2d431fa3456a.jpg)
![a7](https://user-images.githubusercontent.com/7204469/37197446-c5b4787c-23b5-11e8-8dda-dc295a117d79.jpg)
![a8](https://user-images.githubusercontent.com/7204469/37197447-c5eb7566-23b5-11e8-8d17-8d491d842b5c.jpg)

我再想看看，是不是要改用 chosen-rails 來實作我想要的功能 ^_^

http://railscasts.com/episodes/258-token-fields-revised

**Comment by afgnsu** [comment]
這個好像比較好，應該改用Checkbox ^_^

https://www.youtube.com/watch?v=c2qwV0B9yfU

我的需求是：製做一個資產管理軟體，裡面有許多筆個人電腦記錄，目前已經有硬體，還差軟體，直接讓每台電腦可以勾選  :-)

**Comment by hungmi** [comment]
select2可以直接用cdn或是用asset pipeline。

check boxes也不錯，不過要做到直接新增tag應該還需要一些功能唷。我上面根據 Rails Casts做的版本是可以做到直接新增的。

2018年3月9日 17:54，"Patrick Su" <notifications@github.com>寫道：

**Comment by afgnsu** [comment]
![2018-03-14 00-03-03](https://user-images.githubusercontent.com/7204469/37353827-24042c20-271b-11e8-8949-9347cf40e8c5.png)

![2018-03-14 00-06-15](https://user-images.githubusercontent.com/7204469/37353996-8edb3124-271b-11e8-9884-a7e1a4907194.png)


感謝 Hunghi 的指導，我最後改用 collection_check_boxes 完成我要的功能 ^_^
