### ISSUE TITLE
請教一下，我把專案從Rails 4.2升級到 5.2，忽然Devise就無法登出了!!!

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#145]
如題，其他功能都正常，我也有把 devise 重裝 rails g devise:install 並覆蓋 config/initializers/devise.rb

Ruby：2.4.3
Rails：5.2.0
devise：4.4.3
bootstrap：4.1.1 (●這個也有升級)

登入也正常，只有登出時會出錯！

![2018-07-05_093446](https://user-images.githubusercontent.com/7204469/42298117-cd4ca6da-8036-11e8-9158-478ffe17be03.jpg)
![2018-07-05_092329](https://user-images.githubusercontent.com/7204469/42298129-d5747ec8-8036-11e8-8b7d-c7ece898caff.jpg)
![2018-07-05_093354](https://user-images.githubusercontent.com/7204469/42298132-dbe1f0b0-8036-11e8-9b9d-46279dbba26a.jpg)
![2018-07-05_094119](https://user-images.githubusercontent.com/7204469/42298277-9e219ae0-8037-11e8-981b-6552e2a5d9ea.jpg)

**Comment by hungmi** [comment]
你 link_to 裡面的 method: :delete 沒有正確生效，可能要看一下 application.js 需不需要增加/修改喔

**Comment by afgnsu** [comment]
![2018-07-05_145928](https://user-images.githubusercontent.com/7204469/42307148-1d0ab874-8064-11e8-8286-51b18c7f0f0f.jpg)

![2018-07-05_150108](https://user-images.githubusercontent.com/7204469/42307309-88c12ed6-8064-11e8-920d-81e824d4aa7a.jpg)

請參考。

**Comment by afgnsu** [comment]
![2018-07-05_150628](https://user-images.githubusercontent.com/7204469/42307455-1074d864-8065-11e8-9d0e-ab65df07d798.jpg)
我把這個加回去後就可以了，感謝您 ^_^

![2018-07-05_150605](https://user-images.githubusercontent.com/7204469/42307469-1f72952c-8065-11e8-894b-564a99538855.jpg)

**Comment by joshua5201** [comment]
主要原因應該是 rails 5 的 ujs 現在不 depends on jquery 了，從 jquery_ujs 變成 rails_ujs
，所以如果你沒有用到 jquery 也可以拿掉 jquery 然後改用 rails_ujs 。

https://blog.bigbinary.com/2017/06/20/rails-5-1-has-dropped-dependency-on-jquery-from-the-default-stack.html

2018年7月5日(木) 15:07 Patrick Su <notifications@github.com>:

**Comment by afgnsu** [comment]
謝謝，不過我還是有用一點點jQuery，所以先保留 gem 'jquery-rails' 了

![2018-07-05_173102](https://user-images.githubusercontent.com/7204469/42315113-366c7040-8079-11e8-8790-4fd05c87c882.jpg)
 ^_^
