### ISSUE TITLE
請教一下，如何讓一個驗證失敗後就停住？

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#146]
如題，我的 Item 和 events 是一個巢狀結構，我想要新增 events 時 (不論加減) 都會把數量 amount 跟 Item 去同步計算，但 Item 不能為負值。

一開始先新增一個項目 Item，再新增事件 Event。我模擬消費習慣，先買三個，再用掉一個，此時 Item 庫存會顯示 2個。當我再用掉三個時，這時 Item 就算有  validates :amount, :numericality => { :greater_than_or_equal_to => 0 } 驗證也沒用，Log 會跳出 Rollback，但是 Event 照樣存檔，也不去計算 Item 的最終數量。

倒底該如何做，才能讓一個驗證失敗就停住? 最好還能顯示錯誤訊息。我也試過 before_save 或 before_update 也沒用 :(

![1](https://user-images.githubusercontent.com/7204469/43186604-c407e24c-9021-11e8-8815-a521d37ee5a0.jpg)

![2](https://user-images.githubusercontent.com/7204469/43186609-c9e035fc-9021-11e8-9656-11b9d852c210.jpg)

![3](https://user-images.githubusercontent.com/7204469/43186619-d07b6846-9021-11e8-857e-bd4e16457f8e.jpg)

![4](https://user-images.githubusercontent.com/7204469/43186630-d5aee996-9021-11e8-84ea-a45db2b34564.jpg)

![5](https://user-images.githubusercontent.com/7204469/43186634-d9be2f1a-9021-11e8-94e1-d20f6384a332.jpg)

![6](https://user-images.githubusercontent.com/7204469/43186643-ddc14994-9021-11e8-9546-51b45b48d627.jpg)

**Comment by niclin** [comment]
@afgnsu 

`Item.transaction do`

中的 `@event.save` 改成 `@event.save!` 呢？

加  `!` 才會 raise error 出来，transaction 才會 rollback


是我的話我應該會這樣做

```ruby
ActiveRecord::Base.transaction do

  if @event.subject == "plus"
    ...
  else
    ...
  end

  @event.save!
end
```

把他包在一個 transaction, 確保資料都是對的才 commit

**Comment by afgnsu** [comment]
Cool，FB有位羅先生教我用以下方法也可以『Redirect_to .... and return false』：

![2018-07-25_164510](https://user-images.githubusercontent.com/7204469/43191202-45691cce-902d-11e8-9fa2-02ab55dcbd74.jpg)

![2018-07-25_164255](https://user-images.githubusercontent.com/7204469/43191210-4ac5a1d8-902d-11e8-9bf5-18d2199f82fb.jpg)

![2018-07-25_164237](https://user-images.githubusercontent.com/7204469/43191221-50204cb4-902d-11e8-89b4-2021b6a123fa.jpg)
