### ISSUE TITLE
想請教一下，如何讓事件點進去能在 Daterangepicker 顯示正確日期?

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#147]
如題，完整專案在 https://github.com/afgnsu/fullcalendar 

目前還有一個Bug沒解，就是滑鼠點下去的事件日期是對的，但是再點下去跳出日期選擇器時，抓到的時間卻是今天！而不是正確的時間！！！

![demo1](https://user-images.githubusercontent.com/7204469/43885449-7cfaa88c-9beb-11e8-86bd-ac8d13908571.png)
![demo2](https://user-images.githubusercontent.com/7204469/43885452-8002bcea-9beb-11e8-8a06-a68653790ac8.png)
![demo3](https://user-images.githubusercontent.com/7204469/43885454-824a0bb6-9beb-11e8-8fad-7fcb24291535.png)
![2018-08-09_155133](https://user-images.githubusercontent.com/7204469/43885712-3361d456-9bec-11e8-90a5-4ea3c7044648.png)

有可能是在 app/assets/javascripts/daterangepicker.js 裡面的這兩行 ( this.startDate 、this.endDate )，但我不知道要怎麼去修改 >"<

我是參考 https://github.com/driftingruby/094-recurring-events-on-full-calendar 去改的，但是因為 js 裡頭有很多不同，我才會把 ~/.rvm/gems/ruby-2.4.3@rails520/gems/ 底下的 fullcallendar.js 和 daterangepicker.js 拷貝到 asset/javascripts 裡去修改。

**Comment by niclin** [comment]
也許跟 Time.zone 有關？

**Comment by afgnsu** [comment]
我不管選哪一天，daterangepicker 日期選擇器都是跳當天，所以跟時區無關！

**Comment by afgnsu** [comment]
已解決 XD

https://github.com/afgnsu/fullcalendar

**Comment by afgnsu** [comment]
已解決 XD

https://github.com/afgnsu/fullcalendar
