### ISSUE TITLE
vim 貼 code 時，怎麼樣取消自動縮排

### ISSUE THREAD

**Issue by puff-tw** [rubytaiwan/AMA#15]
我忘記 vim 貼 code 時，怎麼樣取消自動縮排4
每次貼 code 都會變成這樣
```
aaa
  bbb
      ccc
```

我希望是這樣
```
aaa
bbb
ccc
```

**Comment by hiroshiyui** [comment]
:set nopaste
2015年9月25日 下午4:47於 "Puff" <notifications@github.com>寫道：

**Comment by puff-tw** [comment]
@hiroshiyui  感謝 :+1:
