### ISSUE TITLE
如何獲得Job 回傳值

### ISSUE THREAD

**Issue by koei1025** [rubytaiwan/AMA#16]
我使用sidekiq來處理大批量資料轉入的job,但我想要知道有辦法可以獲得job處理完成的回傳值，像是處理資料總筆數與成功筆數嗎？謝謝幫忙

**Comment by ilake** [comment]
不是很懂？ 你需要所有jobs 完成時的callback ? 那你應該是要這個 https://github.com/mperham/sidekiq/wiki/Batches

**Comment by koei1025** [comment]
我是需要每個job執行完都能callback

**Comment by ilake** [comment]
如果個別是job 不就是在該做的事做完，就做你要的那件事就好了嗎？

```ruby
def perform
  # 你要做的事
  callback
end
```

**Comment by koei1025** [comment]
感謝回覆，的確可以這樣做，我之前想的太多了。
