### ISSUE TITLE
version mismatch "spring"

### ISSUE THREAD

**Issue by willycode** [rubytaiwan/AMA#18]
如何發生：
我在下rails d model Person 這行指令，產生下面這個問題

問題：
There is a version mismatch between the spring client and the server.
You should restart the server and make sure to use the same version.

CLIENT: 1.4.0, SERVER: 1.3.6

**Comment by willycode** [comment]
解法:在Gemfile裡面spring這個gem，加入1.3.6這個版號
原本：gem 'spring'
修改：gem 'spring', '1.3.6'

再下bundle update這個指令更新Gemfile

**Comment by ihower** [comment]
或是你直接改 Gemfile.lock，把 spring 的 1.3.6 改成 1.4.0。

**Comment by willycode** [comment]
感謝樓上大大:smile:
