### ISSUE TITLE
Model建立Person，卻產生people檔案

### ISSUE THREAD

**Issue by willycode** [rubytaiwan/AMA#19]
I build the model name call "Person". And then the rails will auto-generated person's file.
Unfortunately, I have two files name call "people". I don't understand what happened.
發生有點吊詭的事，就是建立名字叫Person的Model。
正常來說應該是person的檔案，但是rails會自動幫我生出兩個地方叫做"people"的檔案。

$ rails g model Person name:text parent_id:integer parent_type
      invoke  active_record
      create    db/migrate/20150926161949_create_people.rb      <------------------------ file name of people
      create    app/models/person.rb
      invoke    test_unit
      create      test/models/person_test.rb    
      create      test/fixtures/people.yml    <------------------------------------------------------- file name of people

**Comment by JuanitoFatas** [comment]
Rails has [linguistic convention](http://stackoverflow.com/a/10078220/517868). Database tables and fixtures are of pluralized form.​

**Comment by willycode** [comment]
Thank you
