### ISSUE TITLE
Heroku 怎麼指定既有的線上專案？

### ISSUE THREAD

**Issue by puff-tw** [rubytaiwan/AMA#2]
heroku login
git clone https://github.com/rubytaiwan/rubytw-reboot.git
heroku create
這樣就變成開新的app在 heroku 了，要怎麼指定既有的呢？

**Comment by viflin** [comment]
change your hrorku remote url  ?

**Comment by JuanitoFatas** [comment]
Add remote url to your `git remote`:

```
git remote add <your-app-on-heroku.git>
```

**Comment by puff-tw** [comment]
Thanks, I found this.
https://devcenter.heroku.com/articles/git#creating-a-heroku-remote

**Comment by puff-tw** [comment]
case closed.
