### ISSUE TITLE
請問如果寫一個可以上傳多張照片的部落格，建議用哪種架構？

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#21]
如題，假設我用rails g scaffold blog name content:text 產生部落格，照片搭配 Carrierwave套件，究竟該跟Rails101s的留言一樣，把照片獨立出來，然後用巢狀(nest)路由呢？還是乾脆簡單把照片用p1、p2、p3...的方式加入 blog 這個Model裡比較簡單方便？ 因為我看到網路上是用另一種方式  
accepts_nested_attributes_for :photos, allow_destroy: true

但是不太懂用法，可以解釋一下嗎？

https://u.osu.edu/hasnan.1/2014/03/30/rails-4-multiple-file-upload-with-carrierwave-nested-form-and-jquery-file-upload/

**Comment by tubaxenor** [comment]
端看你希望怎麼讓rails幫你處理上傳的request，如果是一個form裡頭多個照片檔案(一個POST request)，那你就必須設 `accepts_nested_attributes_for`。

另外一種做法是多個request，即是每上傳一個照片就產生一個Photo record，Form submit的時候再把這些Photo一個個加進blog post.

若有速度考量，第二種方式可以async處理，第一種比較沒有辦法，若request包含太多大容量檔案容易花很多時間甚至是timeout。

**Comment by afgnsu** [comment]
其實是沒使用過這種方式，才會上來問問大家的意思，如果用Rails101s的巢狀路由的方法，好像變得綁手綁腳的，

**Comment by hechien** [comment]
@afgnsu check `nested_form`.

`accepts_nested_attributes_for` 對於新增子元素來說是一個非常方便的方式，它會幫你在儲存主物件的時候連同子物件一起存進去

所以當你有一篇文章，而該篇文章有多圖片的時候，用這種方式最為方便

**Comment by afgnsu** [comment]
新增很容易，但是想請問一下要如何新增/編輯？因為看起來路由是沒有關聯 :P

假設我要新增，我該如何讓新增的圖片同屬於原本的部落格文章？

**Comment by hechien** [comment]
@afgnsu 可以參考 <https://gist.github.com/iqbalhasnan/24905170bdfd182cd631>

**Comment by afgnsu** [comment]
謝謝，我馬上試試 ^_^

**Comment by afgnsu** [comment]
最後用 cocoon 套件排除 XD
