### ISSUE TITLE
請問Learn Ruby The Hard Way 中文版，40題程式碼?

### ISSUE THREAD

**Issue by bear30920** [rubytaiwan/AMA#22]
![123](https://cloud.githubusercontent.com/assets/13607117/10138812/bd084dc2-6632-11e5-9cd0-48d3dec1bff1.jpg)
請問從第17列這段程式碼
傳給第8列函式到程式結束
有人可以說明一下這程式的運作方式嗎?
謝謝

新手從第1題練到現在，這邊卡關了...

**Comment by sunkai612** [comment]
其實這邊不用原作者的 method 也是可以運作的，原本的 17~27 會變成下面這樣：
```Ruby
while true
  print "State? (ENTER to quit) "
  state = gets.chomp

  break if state.empty?

  # # 這邊也可以寫成：
  # result = find_city(cities, state)
  # puts result
  puts find_city(cities, state)
end
```

回過頭來看原本的程式：

1. 第 17 行
  1. 把 find_city 這個 method 包成了 Method Object（ :v: ，method 也可以包成物件哟 :smile: ）
  2. 在 `cities` 這個 hash 裡面開了一個 key（`:find`），把 method object 當 value 塞進去
2. 第 8~14 行
  1. 對檢查傳入的 `map` 呼叫 `include?` 這個方法
    * 由於在後面的使用中，`map` 其實就是 `cities` 這個 hash，所以其實就是呼叫 `Hash#include?`
    * 這邊就是檢查 `map` 的 keys 有沒有包含 `state`
    * 詳見：http://ruby-doc.org/core-2.2.0/Hash.html#method-i-include-3F
  2. 有值的話，就把對應的 value 回傳
  3. 沒值的話，就很誠實地說「找不到。」
3. 第 19~27 行
  1. `while true ... end` 就是個除非裡面主動斷掉（`break`、`return`、`Ctrl + C`）否則一直執行迴圈
  2. 第 20 行印出給使用者看的提示訊息
  3. 第 20 行用 `gets` 拿使用者輸入值，用 `chomp` 拿掉輸入時尾巴帶的 `\n`，並取個 `state` 名字
  4. 第 23 行檢查剛拿到的使用者輸入值是不是空的（`""`，是不是空字串），若是的話中斷迴圈
  5. 第 26 行把第 17 行塞的 method object 拿出來用，也就是執行 `find_city`（詳見第 8~14 行說明）

ps:
這邊先不用詳細管 Method Object 是啥、通常怎麼用、作者為何在這邊使用 Method Object（謎???）
先把它想成就是個把 method 封起來變成一個可以搬來搬去的實體的方式

如果有興趣的話可以：
1. 看更多 http://ruby-doc.org/core-2.2.0/Method.html
2. 自行搜尋 `ruby proc vs block vs lambda vs method object`（有非常多文章解釋差異）

**Comment by bear30920** [comment]
請問第26行為什麼是(cities,state)??? 
而不是(map,state)回傳給find_city這個函式
謝謝大大的說明,有解開許多的疑問

**Comment by sunkai612** [comment]
因為在第 8 行定義 `find_city` 的開頭時，我們告訴 `find_by` 這個 method：
>「會有兩個東西被丟進你的空間（`scope`），為了方便後面使用，第一個你就叫它 `map`，第二個你就叫它 `state`」

接著在第 8~14 行，我們指示了電腦拿到這兩個東西之後要做什麼處理（詳閱上方說明）

在第 26 行，對 `find_by` 而言，他不知道自己空間（`scope`）外面有什麼東西，但是它依序拿到了 `cities`、`state`，所以他就：

1. 把第一個拿到的參數 `cities` 根據之前約定的（第 8 行約定的）當作 `map`
2. 把第二個拿到的參數 `state` 根據之前約定的（第 8 行約定的）當作 `state`
3. 執行原本要做的工作

希望這樣有回答到你的問題 :smiley:

**Comment by bear30920** [comment]
21行的 state = gets.chomp 收到使用者輸入
23行如果是空字串結束
26行回傳給第8行判斷並執行裡面的動作結束後，並再回傳給26行印出

(cities, state) 接收到的訊息指17行和、21對吧?

**Comment by sunkai612** [comment]
> 21行的 state = gets.chomp 收到使用者輸入
23行如果是空字串結束
26行回傳給第8行判斷並執行裡面的動作結束後，並再回傳給26行印出
state指21

:+1: 

`cities` 是指在第 1~3 行建立，在第 5,6,17 行都有修改的 hash，即是：
```Ruby
{
  'CA' => 'San Francisco',
  'MI' => 'Detroit',
  'FL' => 'Jacksonville',
  'NY' => 'New York',
  'OR' => 'Portland',
  :find => #<Method: Object#find_by>
}
```

**Comment by bear30920** [comment]
原來第17行是建立在hash裡 ，原本單純以為是相等意思
所以程式碼的執行順序是?
第1~6行>>17~27行>>8~14行 
最後一問， 感謝你

**Comment by sunkai612** [comment]
執行順序是：
1. 第 1~6 行 => 建立與修改 `cities`
2. 第 8~14 行 => 定義 `find_city` method
3. 第 17 行 => 把 `find_city` 抓起來塞進 `cities`
4. 第 19~27 行 => 執行幫使用者找資料的迴圈（中間會執行 8~14 行定義過的方法）
