### ISSUE TITLE
rails enum 問題

### ISSUE THREAD

**Issue by flash662** [rubytaiwan/AMA#23]
請問資料欄位如：已完成、處理中、已拒絕
欄位型態通常會如何建立？使用integer，再搭配 rails 中的 enum嗎？
但使用過幾次，感覺不是很順，像是 where搜尋時是使用數字; 翻譯時也比較麻煩，有時候懶得翻譯乾脆使用中文時，跟simple form 搭配時又有 simple form產生出來的 radio id 問題
想請問有更好的解法嗎？或者只是我不熟enum的用法而已，謝謝

**Comment by kraytruthg** [comment]
可以參考看看 AASM [gem](https://github.com/aasm/aasm)

**Comment by chinghanho** [comment]
`app/models/post.rb`:

``` ruby
class Post < ActiveRecord::Base
  STATUS = [ :active, :archived ]
  enum status: STATUS
end
```

`app/controllers/posts_controller.rb`:

``` ruby
Post.active
Post.archived
Post.active.where("comments_count = '3'")
```

`config/locale/en.yml`:

``` yaml
en:
  post:
    active: Active
    archived: Archived
```

`views/posts/edit.html.erb`:

``` ruby
<%= f.select :status, Post::STATUS.map { |status| [ t("post.#{status}"), status ] } %>
```

**Comment by flash662** [comment]
了解，謝謝大家
