### ISSUE TITLE
共用method應該寫在哪裡

### ISSUE THREAD

**Issue by koei1025** [rubytaiwan/AMA#24]
我有多個Background Job，分別處理不同的工作，但是在工作處理完成後都會回傳處理結果，所以我就想要寫一個共用method，讓各個Job可以呼叫同一個method，但是我想不出來可以寫在哪？寫在application_controller似乎不是很好，請問有人可以提點一下嗎？謝謝

**Comment by chitsaou** [comment]
Make a module and include it in each worker.
koei1025 <notifications@github.com>於 2015年10月1日 週四，11:19寫道：

> 我有多個Background
> Job，分別處理不同的工作，但是在工作處理完成後都會回傳處理結果，所以我就想要寫一個共用method，讓各個Job可以呼叫同一個method，但是我想不出來可以寫在哪？寫在application_controller似乎不是很好，請問有人可以提點一下嗎？謝謝
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubytaiwan/AMA/issues/24>.
>
-- 
Regards,
Yu-Cheng Chuang

**Comment by koei1025** [comment]
感謝回覆，的確是應該寫在module，有了關鍵字找了幾篇文章也做出來了，再次感謝。
以下是我找到的參考文章

http://stackoverflow.com/questions/4906932/how-to-create-and-use-a-module-using-ruby-on-rails-3

http://tsaith.github.io/blog/2014/11/21/how-to-use-module-in-rails/
