### ISSUE TITLE
關於資料間 Association 設計疑問

### ISSUE THREAD

**Issue by GeorgioWan** [rubytaiwan/AMA#26]
大家好，是最近踏入ror的新手，
想請教一個資料庫設計上的疑問，疑問如下：

　**假設我有一個資料表Companies，我想於此表中有聯絡人與負責人欄位，
　而聯絡人與負責人所提供的資訊屬性( name, phone, address ... etc)一樣，
　所以我想由資料表Accounts作提供，這麼一來，我認為得關係如下嗎？
　Company has_many Accounts，Account belongs_to Company**

實作後的結果跟我想要的結果不太一樣，且腦袋有點卡住了，
第一次發問如果有什麼沒注意到的地方，請大家多多包涵！

**Comment by ihower** [comment]
在 accounts 上多一個欄位 role 來區分聯絡人(Contact)或負責人(Representative)。

    class Company < ActiveRecord::Base
       has_many :contacts, -> { where( :role => "Contact" ) }, :class_name => "Account"
       has_many :representative, -> { where( :role => "Representative" ) }, :class_name => "Account"
    end

**Comment by GeorgioWan** [comment]
@ihower 謝謝您的回覆！
但這麼一來，若小明的 role 既是此 Company 的 Contact 也是 Representative 的話，
這樣 accounts 裡是不是就會有兩個小明了呢？

**Comment by ihower** [comment]
yes, 那就需要多對多的關係了
```
class Company < ActiveRecord::Base
  has_many :contacts_roles, ->{ where(:role => "Contact") }, :class_name => "CompanyRole"
  has_many :contacts, :through => :contacts_roles, :source => :account

  has_many :representative_roles, ->{ where(:role => "Representative") }, :class_name => "CompanyRole"
  has_many :representatives, :through => :representative_roles, :source => :account
end

# company_id: integer 
# account_id: integer
class CompanyRole < ActiveRecord::Base
  belongs_to :company
  belongs_to :account
end

class Account < ActiveRecord::Base
  has_many :contacts_roles, ->{ where(:role => "Contact") }, :class_name => "CompanyRole"
  has_many :contact_companies, :through => :contacts_roles, :source => :company

  has_many :representative_roles, ->{ where(:role => "Representative") }, :class_name => "CompanyRole"
  has_many :representative_companies, :through => :representative_roles, :source => :company
end
```

**Comment by GeorgioWan** [comment]
謝謝您這麼詳細的回覆！大致上了解之間的關係了，感謝！
