### ISSUE TITLE
請問怎麼做一個與Android app連結的Ruby on rails

### ISSUE THREAD

**Issue by BlakeHung** [rubytaiwan/AMA#27]
目前有建置一個用android studio開發的APP 
之前採用app →web→mysql
但連線上的安全性以及完整性出現問題
想改成
app→ruby on rails(mysql)
請問有哪個大大有經驗或者願意指導小弟
謝謝您
Blake

**Comment by imgarylai** [comment]
之前的 web 是指什麼意思呢？

你的意思是想透過 Ruby on Rails 實做 API server 嗎？

**Comment by chitsaou** [comment]
> 之前採用app →web→mysql
> 但連線上的安全性以及完整性出現問題

你可以具體描述一下嗎？

現在 mobile app 都是走這樣的形式啊：

App -> Web API -> Database

**Comment by BlakeHung** [comment]
目前是第一次使用RoR
問題在於android studio  要用什麼套件去連接RoR
謝謝大大

**Comment by JuanitoFatas** [comment]
> 目前是第一次使用RoR
> 問題在於android studio 要用什麼套件去連接RoR
> 謝謝大大

This could give you some insights: https://news.ycombinator.com/item?id=4889847.

**Comment by BlakeHung** [comment]
Thank you so much
