### ISSUE TITLE
dataTables沒辦法work

### ISSUE THREAD

**Issue by koei1025** [rubytaiwan/AMA#28]
我有哪個部份做錯了嗎？謝謝
Rails version 4.2.3
jquery-datatables-rails 3.3.0

application.js
```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap/dropdown
//= require bootstrap/alert
//= require dataTables/jquery.dataTables
//= require_tree .
```
application.css.scss
```
/*
 *= require dataTables/jquery.dataTables
 *= require_tree .
 *= require_self
 */
 @import "bootstrap-sprockets";
 @import "bootstrap";
```
customers.coffee
```
jQuery ->
    $('#customers').dataTable
```
index.html.erb
```
<table id="customers" class="table">
  <thead>
.......
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
.........
    <% end %>
  </tbody>
</table>
<%= paginate @customers %>
```

**Comment by bih00425** [comment]
有錯誤訊息嗎？
可以試試 $('#customers'). DataTable
另外可以不需要paginate

**Comment by chinghanho** [comment]
``` js
$('#customers').dataTable
```

Coffeescript 執行方法應該也要加括號？

```
$('#customers').dataTable()
```

**Comment by koei1025** [comment]
感謝回覆，不過上述的方法也都不可行，也沒有錯誤訊息

**Comment by JuanitoFatas** [comment]
> 感謝回覆，不過上述的方法也都不可行，也沒有錯誤訊息

給個可以重現的例子。

**Comment by azi** [comment]
是不是要用大寫的D啊？ 
$('#customers'). DataTable

**Comment by koei1025** [comment]
我有重做了一個新的project，裏面除了預設的Gem之外，只有加上dataTable，但還是不行，真是很無力，程式碼在：
https://github.com/KennyCodex/datatable_test

**Comment by bih00425** [comment]
table的header和body的內如數量不同，所以他才會無法顯示，
改成下面這樣就可以了
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

**Comment by koei1025** [comment]
真是太感謝了，這細節真是搞死我這菜鳥了
