### ISSUE TITLE
mac terminal 尋找檔案、顯示檔案命令請益

### ISSUE THREAD

**Issue by hungmi** [rubytaiwan/AMA#29]
大家好，小弟新手剛從linux跳到mac，也正想從sublime跳到vim，正在習慣中。
看到幾個個人很喜歡的工作方式，但不知道怎麼用，想請教各位前輩。

https://youtu.be/SOi_1reKn8M?t=9m15s
這段影片中講者輸入
((detached form ee1d824))$ e
就跳到了一個可以即時搜尋檔案的畫面

另外在11:53處
https://youtu.be/SOi_1reKn8M?t=11m53s
講者可以將檔案分別顯示在螢幕的左右各半

請問這兩個功能是需要安裝什麼套件嗎？

**Comment by hechien** [comment]
1. 那個 e 應該只是一個指令的 alias ，可能是 `vim .` 或某個資料夾的縮寫
2. 這個要請其他用 vim 的前輩們回答了，不好意思

**Comment by CarolHsu** [comment]
如果是分兩半 Vim command 的話應該是 ```:vsp``` （垂直分兩半）
by the way, ```:sp``` 則是水平分兩半（上下分）

**Comment by aryung** [comment]
第一個是 ctrlp ...會搜索目錄下的...
http://zuyunfei.com/2013/08/26/vim-plugin-ctrlp/

**Comment by hungmi** [comment]
太感謝了，剛剛在找答案的時候也順便找到這個，補充一下
http://vimcasts.org/episodes/the-file-explorer/
http://alvinalexander.com/linux/vi-vim-editor-syntax-highlighting
