### ISSUE TITLE
如何在 Ubuntu 14.04 使用 Nginx + Passenger 部署 rails app ?

### ISSUE THREAD

**Issue by AskBear** [rubytaiwan/AMA#31]
目前自己嘗試..我先執行了以下指令:
>sudo gem install bundler passenger --no-ri --no-rdoc
>sudo apt-get install libcurl4-openssl-dev
>sudo passenger-install-nginx-module
>wget -O init-deb.sh http://www.linode.com/docs/assets/1139-init-deb.sh
>sudo mv init-deb.sh /etc/init.d/nginx
>sudo chmod +x /etc/init.d/nginx
>sudo /usr/sbin/update-rc.d -f nginx defaults

然後這時 server start 是成功的。

接著我將 /opt/nginx/conf/nginx.conf 編輯如下圖:
![deploy4](https://cloud.githubusercontent.com/assets/14832915/10273711/10003b00-6b67-11e5-85c2-7f323533deb0.png)
並執行:
>chmod g+x,o+x /home/rails/deploy/fishing
>RAILS_ENV=production rake db:create
>RAILS_ENV=production rake db:migrate

最後 restart server..網頁顯示結果如下圖:
![deploy](https://cloud.githubusercontent.com/assets/14832915/10273733/5ab8c518-6b67-11e5-9d99-7f4432a08c4e.png)

至於 /opt/nginx/logs/error.log 記錄錯誤如下:
![deploy2](https://cloud.githubusercontent.com/assets/14832915/10273741/8b970b22-6b67-11e5-929a-884e6a6c8388.png)
![deploy3](https://cloud.githubusercontent.com/assets/14832915/10273742/8e7908cc-6b67-11e5-8488-fdc8b694b544.png)

請問這是什麼問題? 我有哪裡要改進的嗎?

**Comment by timfanda35** [comment]
在你提供的log中有提示系統使用的 ruby 版本跟你 rails 專案的 Gemfile 中所設定的 ruby 版本不同
目前你的 ubuntu 使用的版本是 1.9.3，但你的專案需要用版本 2.2.1 以上才能運作

你需要在 ubuntu 上安裝版本 2.2.1 以上的 ruby

**Comment by AskBear** [comment]
可是我使用 ruby -v 顯示:
>ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

還是說我哪裡有用錯版本?

**Comment by timfanda35** [comment]
請問你的 ruby 是透過 rvm 或是 rbenv 安裝的嗎？

**Comment by abookyun** [comment]
跟 Linux 環境不熟，在 Linux 都是用 sudo 安裝東西的嗎？另外可以說明一下 Ruby 是怎麼安裝的嗎？

**Comment by aryung** [comment]
你的問題應該和這個很像..
要指定 ruby 的路徑..

http://railsfun.tw/t/passenger-nignx/383

**Comment by zackexplosion** [comment]
看起來是直接用了裝在系統的 ruby ，去研究一下 rbenv 吧

**Comment by AskBear** [comment]
根據大家的意見，看起來似乎就是 **passenger_ruby** 之類的問題
其實這個虛擬機是別人送我的 .vdi 檔架起來的，我也不知道是怎麼裝 ruby 的
我再研究看看~
還有 **abookyun** 不好意思，我是問問題，不是教學 XD

**Comment by abookyun** [comment]
@AskBear 不是來問教學的啦，我自己的環境好得很 XD 是要提醒你，一般來說，我們是禁止用 sudo 裝東西的，很容易有權限問題，這也是 rvm 跟 rbenv 這類環境工具的存在目的。所以看到你用 sudo 裝環境跟發生明顯是環境設定問題才這樣問的。

**Comment by chinghanho** [comment]
沒看到設定 `passenger_root` 和 `passenger_ruby` 這兩個參數的步驟？

**Comment by adlerhsieh** [comment]
我先前也愈過權限問題，如果透過`sudo gem install`來安裝`passenger`，會產生一些權限問題，建議用apt-get來安裝passenger，再掛到nginx底下。

可以參考[我之前的安裝心得](http://motion-express.com/blog/20150421-deploy-rails-to-vps)

**Comment by AskBear** [comment]
我現在知道我的 ruby 是 rbenv 裝的 2.2.1 版
而看我上面的做法 error.log 有幾行 `/var/lib/gems/1.9.1/gems/passenger....`
是否能解讀為 passenger 使用了我系統 ruby 1.9.1 的版本?
那我要如何做才會安裝正確? `passenger_ruby` 能否解決?
順道一提: 我是使用 virtualbox 開 ubuntu 虛擬機，
並且想要部署(應該說能從外界輸入網域觀看) ubuntu 裡的 rails app
小弟不才，有任何錯誤觀念、想法請多多包涵，懇請不吝指教

@abookyun 不好意思，我還真的誤會了 ^^" 謝謝你的指教，日後我會做為參考

**Comment by zackexplosion** [comment]
其實 passenger 自己用哪個 ruby 版本不太需要去管他，你只要讓他可以用正確的 Ruby 版本來啟動你的 APP 就可以了。

我的設定檔給你參考看看

```
passenger_show_version_in_header off;
passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
passenger_ruby /usr/bin/passenger_free_ruby;
```

**Comment by adlerhsieh** [comment]
另外，本機server如果要能夠開放外連，要有申請固定ip(如果沒有申請過，一般在台灣預設都是浮動ip)，並從本機設定開放外連ip才可。就我所知，要從本機的virtual machine內開放外連，過程似乎有點複雜，可能要google一下。

如果要能真的從ip外連，建議到Google Cloud或AWS申請免費方案，用他們的機器練習佈署比較好。

**Comment by motephyr** [comment]
前面幾位朋友應該都有提到正解了
其實就是在nginx.conf底下去設
```
    passenger_root /home/apps/.rvm/gems/ruby-2.1.1/gems/passenger-4.0.37;
    passenger_ruby /home/apps/.rvm/gems/ruby-2.1.1/wrappers/ruby;
```
類似這種設定就可以了。

**Comment by AskBear** [comment]
大家好喔~於是我試著改成如下圖:
![deploy7](https://cloud.githubusercontent.com/assets/14832915/10330087/6f5a3084-6cfb-11e5-8bbb-209f9781c378.png)

結果得到了一頁只顯示 `Incomplete response received from application`  的頁面

error.log 如下:
![deploy5](https://cloud.githubusercontent.com/assets/14832915/10330103/9ae42c8c-6cfb-11e5-8920-038c519544d9.png)
![deploy6](https://cloud.githubusercontent.com/assets/14832915/10330104/9d39a0ca-6cfb-11e5-91c8-4975effcb5ad.png)

是否我又疏漏了什麼 XD

**Comment by chinghanho** [comment]
@AskBear 

production 環境變數的 `SECRET_KEY_BASE` 有設定嗎？

``` nginx
server {
  ...
  passenger_env_var SECRET_KEY_BASE a1b2c3d5...
}
```

**Comment by AskBear** [comment]
真的是還缺 `passenger_env_var SECRET_KEY_BASE`
我的網站可以跑了 感謝各位大大支持!
不過我最後還遇到了一個問題， assets 沒進來，冏

**Comment by zackexplosion** [comment]
RAILS_ENV=production bin/rake assets:precompile

**Comment by AskBear** [comment]
我輸入了:
`RAILS_ENV=production bundle exec rake assets:precompile`
public/assets 也有東西了，可是沒出現..

**Comment by chinghanho** [comment]
@AskBear 推薦讀一下這篇 http://gogojimmy.net/2012/07/03/understand-assets-pipline/

**Comment by zackexplosion** [comment]
網站前端的錯誤訊息？ 還是把錯誤訊息貼上來比較好，不然我們只能瞎子摸象。

**Comment by adlerhsieh** [comment]
`sites-available`的設定檔裡面，server block裡面看有沒有這行：
```
server {
  passenger_app_env production;
}
```

有的話他才會去讀production的assets

**Comment by AskBear** [comment]
根據 @zackexplosion 大的提示，我去看了 rails app 的 production.log
發現找不到 assets 的錯誤
再參考 @chinghanho 大給的網站，在 config/environments/production.rb 加上:
`config.serve_static_assets = true`
就成功了

@adlerhsieh 大，我只加那行的話沒效果 XD

 終於成功了，感謝各位江湖大俠一路相挺~^^

**Comment by adlerhsieh** [comment]
恭喜喔，建議記錄分享一下過程，這方面的資訊很多人都需要~

**Comment by AskBear** [comment]
來日補上喔 ^^

**Comment by AskBear** [comment]
這是我這次的心得喔~不知道這樣放好不好~總之感謝大家幫忙 ^^
大家有興趣也可幫忙修改~感恩
[在Ubuntu 14.04虛擬機上部署Rails app-使用Nginx + Passenger.docx](https://github.com/rubytaiwan/AMA/files/9861/Ubuntu.14.04.Rails.app-.Nginx.Passenger.docx)

**Comment by zackexplosion** [comment]
可以放到 hackpad 或 Google doc 上嗎？ 好久沒用 Word 了...

**Comment by JuanitoFatas** [comment]
@AskBear Add to [Tutorials wiki page](https://github.com/rubytaiwan/AMA/wiki/Tutorials). :blush:

**Comment by AskBear** [comment]
@zackexplosion 
https://docs.google.com/document/u/1/d/1EH6rcZ9TbCwGMDdlM3jFQxtHb004B8StYU1kIFuvFrM/pub
@JuanitoFatas 
是像這樣嗎?
https://github.com/rubytaiwan/AMA/wiki/%E5%9C%A8Ubuntu-14.04%E8%99%9B%E6%93%AC%E6%A9%9F%E4%B8%8A%E9%83%A8%E7%BD%B2Rails-app-%E4%BD%BF%E7%94%A8Nginx---Passenger

**Comment by JuanitoFatas** [comment]
@AskBear Awesome :+1:. You may need to learn some more markdown to improve how it reads.

**Comment by adlerhsieh** [comment]
@AskBear 謝謝啦~ 幫你把markdown稍微潤飾一下比較符合GitHub的排版方式

**Comment by AskBear** [comment]
正在努力查看 markdown 相關 XD

**Comment by AskBear** [comment]
最近在試著自己架設Rails環境的時候，改用RVM安裝Ruby，
架設完繼續進行這裡研究的部署方式，發現在`sudo gem install passenger...`時出現
`gem: command not found`的問題，於是我在部署的流程裡新增了一些解決方法，
大家可以參考指教一下，感謝。
