### ISSUE TITLE
會變動的設定值紀錄有沒有好的寫法？

### ISSUE THREAD

**Issue by viflin** [rubytaiwan/AMA#32]
嗨，大家好

之前寫rails的時候，有些全站的設定值我會開一個table，例如叫做settings去紀錄他
例如說，我寫一個購物的網站，後台有個欄位叫做 user_initial_cash，
紀錄說現在user如果開新帳號，有沒有贈送的代幣
而user_initial_cash_value則是紀錄如果有要贈送代幣，新帳號裡面的代幣要送多少

    create_table "settings", force: :cascade do |t|
        t.integer  "user_initial_cash_value"
        t.boolean   "user_initial_cash"
    end

而管理者可以進入後台依照需求更改
但是這個table就會永遠只有一個row（因為只有一個設定），覺得很奇怪，很不環保
所以想請問大家有沒有更好的寫法？   謝謝

**Comment by hechien** [comment]
或者可以考慮一下 `SettingsLogic` 這個套件

**Comment by hiroshiyui** [comment]
`Rails.cache` 不曉得合不合用？（參考： http://guides.rubyonrails.org/caching_with_rails.html ）

**Comment by ryudoawaru** [comment]
https://github.com/ryudoawaru/spree_preferences_redis 舊東西

**Comment by adlerhsieh** [comment]
我想到兩種方法：

1. 看起來是否只有你自己會去修改這些數值？如果是的話，應該是可以直接放在一個檔案內，例如放在`app/services`當中或是`config/initializers`設定為常數，直接讀取即可。

2. 如果是需要UI去調整這些數值，我覺得可以採用WordPress的作法，一樣設定一個table叫做settings，但兩個欄位叫做`key`和`value`，這樣未來如果有其他設定檔，也可以納入，這樣query方式也比較直覺一點。

```ruby
Setting.find_by(key: :user_initial_cash_value).value
```

**Comment by viflin** [comment]
感謝上面各位大大提供了各種不同的方式！
我在評估專案之後已經選擇了我覺得最適合的方式，謝謝！
