### ISSUE TITLE
想請教一下，如何讓這個Alert訊息過幾秒後自動消失？

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#33]
如題， 我有看到網路上建議用 $(".alert").fadeOut(3000) ，放在 app/assets/javascripts/XXX.coffee ，可是好像沒用 >"<

![2015-10-05 21 48 33](https://cloud.githubusercontent.com/assets/7204469/10282123/a74c5d06-6bab-11e5-8a9e-7d583382392c.png)
![2015-10-05 21 52 10](https://cloud.githubusercontent.com/assets/7204469/10282127/ac5e7fa4-6bab-11e5-9bd3-41fa6354f5e7.png)

**Comment by zackexplosion** [comment]
注意執行的順序，不知道你在哪裡執行 fadeOut 的 function

**Comment by afgnsu** [comment]
我只是用 Rails 101s 的範例
http://github.com/afgnsu/rails101s

**Comment by chinghanho** [comment]
兩個方式

1. 把載入 script 的 tag 放到 `<body>` 最後面
2. 把 callback 放在 document ready 內：

``` js
$(function() {
  $(".alert").fadeOut(3000)
})
```

**Comment by afgnsu** [comment]
我用的是 <% bootstrap_flash %>

我把
<script type='javascript/text'>
$(function() {
  $(".alert").fadeOut(3000)
})
</script>
放到 app/views/layouts/application.html.erb 的 </body> 上面，不知道為何沒反應 >"<

2015-10-06 1:39 GMT+08:00 Ching-Han Ho <notifications@github.com>:

> 兩個方式
>
>    1. 把載入 script 的 tag 放到 <body> 最後面
>    2. 把 callback 放在 document ready 內：
>
> $(function() {
>   $(".alert").fadeOut(3000)
> })
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubytaiwan/AMA/issues/33#issuecomment-145608821>.
>



-- 

◢▄◣ 蘇介吾 / 家住楊梅市新農街
○○█ Mobile: 0921-380997
◥○◤ Email : afgnsu@gmail.com
▂██ FB: http://fb.me/afgnsu
▂█◤ Website : afgn.idv.tw

**Comment by SDLyu** [comment]
`<script type='javascript/text'>` 的 `type` 宣告錯了，應該是 `<script type='text/javascript'>`

**Comment by afgnsu** [comment]
SDLyu 可以了，謝謝 ^_^
