### ISSUE TITLE
RSpec view 錯誤 controller response 問題

### ISSUE THREAD

**Issue by flash662** [rubytaiwan/AMA#34]
想請教一下，在寫 rspec controller 測試時，寫好 response 200
跑測試時也沒有問題，但實際上在view有錯誤，所以頁面其實是 response 500
但 controller 沒有測試到，請問一下這是正常的嗎？該如何測試出view的錯誤？

**Comment by st0012** [comment]
在一開始加上 `render_views`

**Comment by ryudoawaru** [comment]
controller test 不是本來就是在測 controller 的嗎？

**Comment by flash662** [comment]
了解，主要是想了解在controller 測試 response status code 出現跟實際情況不一樣時，是否為正常情況
謝謝

**Comment by JuanitoFatas** [comment]
> 了解，主要是想了解在controller 測試 response status code 出現跟實際情況不一樣時，是否為正常情況
> 謝謝

:clap: :clap: :clap:
