### ISSUE TITLE
想請教一下，如果我想讓表單有兩種不同的選擇內容，應該怎麼做？

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#35]
如題，我想寫一個房仲網站，例如有房屋和土地兩種項目，這個檔案在 app/views/items/_form.html.erb

```erb
<%= f.select :kind, [['房屋',0],['土地',1]], include_blank: true, label: '項目' %>
<%= f.select :category, [['大廈',0],['透天',1],['公寓',2],['建地',3'],['農地',4],['工業地',5]], label: '分類' %>
```

當『新增』物件時，我希望選完項目後，若選擇『房屋』時可以只出現房屋的分類 (例：大廈、透天、公寓)，選『土地』時可以只出現土地的分類(例：建地、農地、工業地)。

請問該如何修改？是否一定要搭配 jQuery 的 append?

**Comment by zackexplosion** [comment]
> 我希望選完項目後

有這個動作就一定要搭配 Javascript 來做了 ，除非你要帶參數給後端讓他重新宣染整個頁面。

**Comment by afgnsu** [comment]
收到，謝謝 ^_^
