### ISSUE TITLE
請問大家開發上切換視窗和目錄都是用什麼工具或快捷鍵

### ISSUE THREAD

**Issue by festime** [rubytaiwan/AMA#36]
不確定發在這合不合適，發這篇主要是想， Rails 開發上很常做視窗切換（瀏覽器、終端機、文字編輯器）和文字編輯檔案目錄之間的切換，因為這太常做了，所以如果可以把這動作降低到平均兩三秒內或甚至一秒內，對效率的提升會很有助益，而不是一直 `cmd + tab` 或看目錄找檔案...，希望大家可以提出自己的「快速切換祕技」互相交流，甚至看了別人的做法後可以改進自己的快捷鍵組合技 :smile: 

我的快捷鍵組合其實不多（所以才想向大家討教...），目前使用 chrome + iTerm2 + macvim  

iTerm2 本身有提供 system-wide hotkey 設定，我設定 `shift + space` ，自從用了這個之後要切換到終端就無腦多了，我習慣用左手小拇指 + 大拇指按，剛好這組合要按也很方便，不會姿勢卡卡的感覺，這設定缺點是有時候打字快一點的話會不小心觸發就跳到終端機

macvim 我有安裝一個 plugin 叫 rails.vim ，這應該有用 vim 寫 rails 的人都知道...，它提供了在 command 模式下輸入幾個關鍵字就跳到某 model/view/controller 的功能，例如我要切到 views/posts/index.html.haml ，就輸入 `:Rview posts/index` ，它有提示功能，所以通常不需要把整串手動打完

chrome 我沒有什麼可以分享的

我處於這個狀態下已經有好幾個月，一直沒再精進，我後來有想到其實應該為瀏覽器和文字編輯器也加入 system-wide hotkey 才對，這樣我在這三者之間切換就完全不用 `cmd + tab` 了（對，我如果要跳到瀏覽器或文字編輯器還是用這個...），我知道 QuickSilver 可以定義這個，還沒摸索出比較好的組合

另外關於瀏覽器，不知道有沒有什麼擴充套件可以做到如下效果：因為常常搜尋資料開了好幾個分頁，有時候想起哪個搜尋結果要切過去，可是忘了在哪個分頁，一個一個切換看很麻煩，可不可以對某分頁某些內容標記之類的，之後搜尋關鍵字就跳到那分頁？

謝謝 :smile:

**Comment by berniechiu** [comment]
Alfred 其實還不錯用
也有你所說的搜尋分頁的功能

**Comment by joshua5201** [comment]
firefox的address bar還有tab group也許是你要的功能
(Rails + Archlinux + Vim + Firefox路過)

**Comment by zackexplosion** [comment]
![preferences_and_1__zack_tonys-macbook-pro-fixed____projects_inpage_javascript__zsh_](https://cloud.githubusercontent.com/assets/5180966/10300357/e4dccee0-6c27-11e5-9a97-313b4bf3e2cd.png)
我是用 F1 做 iTerm 的 Toggle ，其他就用系統的 mission control ，瀏覽器放第一個，編輯器第二。

**Comment by adlerhsieh** [comment]
Alfred的進階功能可以綁熱鍵，我設定option + q 跳到終端機、option + w 跳到chrome、option + e 跳到 source tree，這樣省掉思考的時間。

搜尋功能也可以用Alfred搞定，可以用keyword的組合，會直接進入你要的頁面。例如設定`tool framework`按Enter就開瀏覽器上Ruby Tools網站搜尋`framework`關鍵字。

**Comment by viflin** [comment]
cmd + tab 打天下，所以常常切到facebook就停留了... :trollface:

**Comment by festime** [comment]
謝謝大家分享！

@adlerhsieh 你的快捷鍵設定感覺還滿不錯的，收下了 :smile: ，你的部落格我有 follow ，之前 vim 的一些技巧就是看你的文章學到的 :+1: ，你說的 Alfred 搜尋功能似乎能解決我的一些問題，不過能否做到輸入關鍵字就切到現有的某個分頁當中我就要再摸索看看了

@viflin  :laughing: 

看到那麼多人都提到 Alfred ，其實我裝很久了，看樣子是我沒好好摸索它的功能 :cry: 

mission control 看過身邊有些人也是這樣切換，不過我用不太慣

看到這個 issue 被標籤生產力，讓我想到有這幾本書談關於這方面的事情：

* [程式設計師提升生產力秘笈](http://www.books.com.tw/products/0010429241)
* [The Effective Engineer](https://www.theeffectiveengineer.com/book)

希望對大家有幫助！

**Comment by adlerhsieh** [comment]
也謝謝你的分享！
