### ISSUE TITLE
找 Ruby on Rails 工作

### ISSUE THREAD

**Issue by fredchen90** [rubytaiwan/AMA#37]
大家好,我叫Fred..

現在開始要找rails相關的工作!

可是發現inside job , ruby job, 66k job...等公司都不多,請教各位大大可否提供一些公司名稱阿!!!

這樣好歹可以投履歷阿阿阿阿.... T_T

**Comment by zackexplosion** [comment]
可以看看這家 <http://www.thenewslens.com/jobs> 他們有在找 RoR Developer

**Comment by adlerhsieh** [comment]
2015年開始職缺數量都不多，有看到的話要把握一下

**Comment by viflin** [comment]
身為社群好友的轉職鼓勵師，有資料表紀錄台灣有用Ruby/Rails的公司是很合理的
但我不確定是否還在招人，希望對你有幫助就是了

- T客邦
- CodeGreen
- ikara
- 果實夥伴
- TNL
- vpon
- faria
- kktix
- cardinal blue
- uknowiknow
- sinlead
- 5xruby
- tripmoment
- 布魯貝克
- 貝殼放大
- codementor
- u3d
- akatsuki
- ABAgile
- rtaiwanr
- OptimusDev
- 女人迷
- 三立電視台
- 風傳媒
- MaiCoin
- livehouse.in
- icook
- Jungllle
- 中國台灣我印
- hypo
- 夢享
- GoodLife
- Bitoex
- oursky
- Snupped
- JollyGoodCode

**Comment by sunkai612** [comment]
:clap: :clap: :clap:

**Comment by fredchen90** [comment]
太感謝各位啦!!!!!!!

希望這篇可以讓跟我一樣的 "junior" 做參考!!!

**Comment by JuanitoFatas** [comment]
Bravo @vinn! Moved to [Wiki](https://github.com/rubytaiwan/AMA/wiki/Ruby-&-Rails-%E5%85%AC%E5%8F%B8%E5%88%97%E8%A1%A8), everyone feel free to edit there.

**Comment by JuanitoFatas** [comment]
By the way, there is a [plan](https://github.com/rubytaiwan/rubytw-reboot/issues/58) to add a companies page for new ruby.tw. So we can leverage Wiki to gather data first. :blush:
