### ISSUE TITLE
Ruby 作業求救

### ISSUE THREAD

**Issue by pkgamma** [rubytaiwan/AMA#39]
哈囉, 我想要請求一個有點大的協助 😭😭, 我在 Coursera 上上 Rails, 第一份 Ruby 作業我就遇到困難了, 想要拜託高手協助!! 題目是 **“找出文檔中出現頻率最高的字”**, 指示:

1. 讀取一份有三行字的 test.txt 文檔
2. 找出每一行中出現頻率最高的字
3. 比較這三行中 "出現頻率最高的字" 的數量, 找出最大的, 那即是整份文檔中 "出現頻率最高的字”

詳細的指示是: 

1. Write a class called LineAnalyzer that
 - records the location of a line of text in the file
 - analyzes a line of text
 - figures out the highest frequency word(s) on that line and their frequency count
2. Write a driver class called Solution that
 - reads provided 'test.txt' file
 - creates an array of LineAnalyzers
 - selects the ones whose "highest frequency words" are the greatest among all LineAnalyzers
 - prints out the results

感激不盡!!!!!

**Comment by JuanitoFatas** [comment]
你現在的進度如何？

**Comment by JuanitoFatas** [comment]
You can try to ask specific questions about Ruby itself. But due to the [Honor Code](https://learner.coursera.help/hc/en-us/articles/201223999-Honor-Code-Plagiarism) from coursera, I have to close this issue.

> I will register for only one account.*
My answers to homework, quizzes, and exams will be my own work (except for assignments that explicitly permit collaboration).
> I will not make solutions to homework, quizzes, or exams available to anyone else unless explicitly permitted by the instructor. This includes both solutions written by me, as well as any official solutions provided by the instructional staff.
> I will not engage in any other activities that will dishonestly improve my results or dishonestly improve/hurt the results of others.

**Comment by pkgamma** [comment]
Opps. Totally forgot about the Honor Code... 既然 Coursera 還是學校, 好吧... 我只是想尋求一點方向. 我只有一點點進展, 還在思考中~ 謝謝!

**Comment by chitsaou** [comment]
@pkgamma 你可以具體描述你試了什麼方法、遇到什麼問題、哪裡思路不通。如果直接把作業貼上來的話，大家會認為是作業文也很正常的。
