### ISSUE TITLE
禮拜四meetup出席資訊

### ISSUE THREAD

**Issue by fredchen90** [rubytaiwan/AMA#40]
哪邊可以知道新手村meetup確定會出席的資訊呢?

還是每個禮拜四都是一個surprise!!!!!

**Comment by Tim-Feng** [comment]
新手村就像是一盒巧克力，你永遠不知道你會拿到什麼口味。

**Comment by JuanitoFatas** [comment]
Today has free :pizza: :wink:, sponsored by @viflin :clap: :clap: :clap:

**Comment by viflin** [comment]
新手村每週四都會固定舉辦，但沒有固定的topic
你有可能會遇到你在網路上景仰的大神，也有可能認識一起學習的夥伴
你也可以教導初次安裝rails的朋友，還有可能發現你未來的老闆...

如同 @Tim-Feng 村長所說，這盒巧克力要親自吃下去，才會知道是什麼口味 :smile:

**Comment by JuanitoFatas** [comment]
See you in thursday :heart::yellow_heart::blue_heart::green_heart::purple_heart:
