### ISSUE TITLE
如何移除多餘的ruby

### ISSUE THREAD

**Issue by koei1025** [rubytaiwan/AMA#41]
我在GitHub上抓了一個範例，下載回來後執行bundle install，結果在環境中造成了有兩套ruby，使得現在沒辦法建立新的專案。
```
kenny@test /usr/local/bin $ which -a ruby
/usr/local/bin/ruby
/usr/bin/ruby
```
痛苦的是我的環境當初是土法煉鋼的，根本沒想到要去裝RVM，現在後悔莫及。
請問我該如何移除掉/usr/local/bin/ruby呢？

**Comment by hiroshiyui** [comment]
好奇請教您當時是抓哪個範例？

**Comment by chinghanho** [comment]
通常放在 `/usr/local/bin` 目錄底下的都是 symlink，直接刪掉就可以了，如果要刪乾淨就要去找源頭：

```
$ ls -la /usr/local/bin | grep ruby
```

應該用的是 rbenv 所以才會裝在這裡，刪除 rbenv 方法可以[照文件指示](https://github.com/sstephenson/rbenv#uninstalling-rbenv)。

不過，問題我猜應該不是「有兩套 Ruby」的關係。確認目前用的 Ruby 版本：

```
$ ruby --version
```

**Comment by koei1025** [comment]
我抓的是這個
https://github.com/ramblex/modal-form

我目前的的版本是ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

一開始的問題是出現cannot load such file，後來去拜了google之後，才會懷疑可能會不會是這個原因
```
kenny@test ~/ruby_projects $ rails new test
/usr/local/bin/rails:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.2.0/gems/rails-4.2.3/bin/rails (LoadError)
	from /usr/local/bin/rails:23:in `<main>'
```

**Comment by chinghanho** [comment]
如果重裝 Rails 試試看？

**Comment by koei1025** [comment]
經過把Rails移除後再重裝就解決問題了，感謝各位的幫忙
