### ISSUE TITLE
好難搞定的Passenger 5.0.20！

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#42]
想請教一下，何時Passenger變得那麼難使用？還多出了 『bundle exec passenger start』這種指令？而且還要自訂 Passengerfile.json 檔案。

如果我的Ruby 版本是 2.2.0，Rails版本是4.2.0，可以用比較舊的Passenger版本嗎？我只想回到以前那種簡單的佈署方式 XD

https://www.phusionpassenger.com/library/walkthroughs/start/ruby.html

**Comment by zackexplosion** [comment]
我用 Passenger 5.0.18 沒看到一定要自訂 Passengerfile.json ，小版本應該不會改那麼多吧...

**Comment by afgnsu** [comment]
4.0.59就可以這樣用了 XD

**Comment by afgnsu** [comment]
搞定了，用舊的方法也可以運作，只要在 /etc/apache2/sites-available/xxx.conf 裡加設 Passenger 自帶的Log 來查出設定哪裡出了問題 XD

![2015-10-10 23 55 46](https://cloud.githubusercontent.com/assets/7204469/10412483/d9fe1a3e-6fb9-11e5-9cea-6ab25c596a0d.png)
