### ISSUE TITLE
如何用 rvm 或 rbenv 來 wide install ruby?

### ISSUE THREAD

**Issue by AskBear** [rubytaiwan/AMA#44]
如題~
我想在`Ubuntu`只安裝一次`ruby`，就可以給所有使用者使用。
請問該怎麼做?`rvm`、`rbenv` 都是 for current user 吧?
還是這樣做並不適合?

**Comment by zackexplosion** [comment]
之前有想過這問題，不過這東西基本上就是利用 User 把環境隔開，如果特別把他裝 Global 似乎就失去原本故意隔開的意義了。

這裡有一篇文章，你可以參考看看，主要就是把 RBENV_ROOT 給換掉的樣子
http://toschas.com/rbenv-setting-it-up-globally/

**Comment by aryung** [comment]
用 root 裝 ruby...
root 裝的 ruby 每個 user 都可以用..
(記的是這樣..path 設好就好了..)..

**Comment by AskBear** [comment]
好像都是不錯的方法，不過我現在在想..
我會有這個問題是，我在架設新的環境時，執行`sudo gem install .........`
會有`sudo: gem: command not found`的錯誤
遇到這種情形一般會怎麼解決?

**Comment by chinghanho** [comment]
如果是 RVM 的話：

> For a Multi-User install you would execute the following:
>
> ```
> \curl -sSL https://get.rvm.io | sudo bash -s stable
> ```

ref: https://rvm.io/rvm/install#installation-explained

`sudo: gem: command not found` 問題解法：

```
rvmsudo
```

ref: https://rvm.io/integration/sudo

**Comment by AskBear** [comment]
@chinghanho rvmsudo不錯用，謝嚕
