### ISSUE TITLE
關於 Ubuntu 14.04 使用 sublime text2 出現錯誤訊息

### ISSUE THREAD

**Issue by AskBear** [rubytaiwan/AMA#45]
如題我每次開啟sublime都會一直跑以下error:
`(sublime_text:2627): GLib-CRITICAL **: Source ID 2835 was not found when attempting to remove it`
上網查一下好像可以不用理他，但是很礙眼啊~請問該怎麼讓他消失呢?
還是各位覺得我直接換`sublime text3`比較好 XD

另外好奇大家都習慣用什麼編輯器呢?
希望可以分享一下心得、優缺點  XD

**Comment by adlerhsieh** [comment]
[這邊有一篇看起來跟你的狀況一樣](http://stackoverflow.com/questions/23165426/sublime-text-on-ubuntu-14-04-keeps-attempting-to-remove-it)，簡單來說錯誤訊息是由系統產生的，並無影響，可以直接忽略，只要升級14.10以上的版本，錯誤訊息就會消失。

另外，編輯器的流派太多了，在這邊應該會分享不完，哈，Google應該可以找到很多編輯器的心得分享。Site Point上有兩篇關於編輯器的文章。

1. [Ruby開發者都用什麼編輯器](http://www.sitepoint.com/editor-rubyists-use/)
2. [Ruby開發者都用什麼IDE](http://www.sitepoint.com/ides-rubyists-use/)

可以自己去摸摸看這些編輯器的優缺點。我個人目前主力是Vim，先前寫過[一篇心得](http://motion-express.com/blog/20150215-learning-vim)可以參考一下。

**Comment by zackexplosion** [comment]
我都用笨方法，直接把 Sublime 砍掉重裝....

**Comment by AskBear** [comment]
於是..我決定裝 sublime text3..XD

@adlerhsieh 感謝你的編輯器資料 ^^
