### ISSUE TITLE
想請教一下,TWSMS模組的使用方式

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#46]
TWSMS簡訊：
https://github.com/xdite/twsms/blob/master/lib/twsms.rb

這是一個Module，首先應該放在 lib 底下，接著是要 require 還是不需要？(Auto-loading?)

我也有搜尋到是直接放在Gemfile 裡，像是 gem 'TWSMS'，但是文件並不齊全。

另外帳號密碼要放在哪各位置？因為前兩行是，我記得 initialize 本來就會自動載入。

 def initialize(username, password)
    @uname, @upwd = username, password

最後是這個模組需要改寫嗎？因為是6年前的程式，有沒有需要改變的地方？ Thx

**Comment by afgnsu** [comment]
http://tsaith.github.io/blog/2014/11/21/how-to-use-module-in-rails/

可以像這樣嗎？改由 model 去 include ?

**Comment by adlerhsieh** [comment]
`lib` 資料夾底下的內容並不會自動讀取，可以依照[這篇](http://stackoverflow.com/questions/19098663/auto-loading-lib-files-in-rails-4)的設定調整看看，就可以不必再加上其他的`require`。

另外，`require`之後就可以用類似`TWSMS.new`的方式呼叫，除非要在其他`class`當中使用這個`module`的instance method，才需要另外`include`。

**Comment by tubaxenor** [comment]
> 這是一個Module，首先應該放在 lib 底下，接著是要 require 還是不需要？(Auto-loading?)

```
class TWSMS
  def initialize(username, password)
...
```

這是一個`Class`, require 或 auto-load 皆可

> 另外帳號密碼要放在哪各位置？因為前兩行是，我記得 initialize 本來就會自動載入。

第一個參數是帳號，第二個參數是密碼。

> 最後是這個模組需要改寫嗎？因為是6年前的程式，有沒有需要改變的地方？ Thx

API doc: https://www.twsms.com/dl/api_sms_doc.zip

可以看有沒有變更的地方然後修改，或是自己寫一個Gem :)

**Comment by afgnsu** [comment]
可以了，把 twsms.rb 刪掉一堆不要的，就可以簡單做出我要的功能 ^_^

``` ruby
require 'twsms'
a = TWSMS.new('帳號','密碼')
a = sendSMS('0911111111','簡訊內容')
a = querySMS   #=> 傳回剩餘點數 (type=point)
```
