### ISSUE TITLE
如何查看哪一段 javascript 程式碼被執行

### ISSUE THREAD

**Issue by festime** [rubytaiwan/AMA#47]
不好意思，這也許是很基本的前端問題，但可能關鍵字下的不對，一直找不到我要的資訊

我用了 `client_side_validations` 這個 gem ，它提供前端欄位驗證和顯示 validation errors 訊息，我想要做到可以「很即時的」當使用者在輸入時就邊檢查這資料是否 valid ，在欄位邊框顯示紅色、綠色...等等，忘記在什麼網站有看過這樣的功能

`client_side_validations` 這個 gem 處理驗證部分的[ JS 程式碼](https://github.com/DavyJonesLocker/client_side_validations/blob/master/coffeescript/rails.validations.coffee#L208)約兩三百行，可是看不太懂，想說如果可以查看事件觸發時是哪段程式碼被執行時，就可以從中改造出自己要的功能

謝謝

**Comment by zackexplosion** [comment]
參考看看 Angularjs 的 validation 

http://www.w3schools.com/angular/tryit.asp?filename=try_ng_validate

**Comment by festime** [comment]
謝謝，它這欄位驗證的效果看起來是我要的，我考慮看看是否加入 angular 

可是我目前傾向先嘗試看看可不可以自己實踐所要功能的 code

**Comment by adlerhsieh** [comment]
如果不用angular的話建議用jQuery的[.change()](https://api.jquery.com/change/)或[.on()](http://api.jquery.com/on/)之類的function，可以針對input欄位綁定，[這邊](http://stackoverflow.com/questions/1948332/detect-all-changes-to-a-input-type-text-immediately-using-jquery)有很簡單的用法。如果希望用JavaScript原生或其他用法，可以Google搜尋JavaScript on、watch、change、text input 等等關鍵字

**Comment by chinghanho** [comment]
一般知道 event 名稱我會直接從原始碼去搜，例如 `change`、`keypress`、`keyup` 之類的，或是從觸發事件的 DOM 去找 event listener，Chrome 開發者工具有這個功能：

![screen shot 2015-10-13 at 7 05 59 pm](https://cloud.githubusercontent.com/assets/1897143/10453315/ad19b8d6-71dd-11e5-883b-a9a8a0ddcce1.png)

然後直接在 Chrome 的 source panel 裡面改 Javascipt，各個可疑的地方加上 `console.log` 或是 `debugger`，<kbd>cmd</kbd> + <kbd>s</kbd> 立即生效，也不用 reload。

**Comment by festime** [comment]
謝謝 @adlerhsieh 的建議 :smile: ，我知道 debugger 這功能，不過這樣就有點亂槍打鳥，在程式碼當中多個地方插入斷點，嘗試找出在哪裡；你分享的連結讓我想到下午搜尋時可能找的太「大方向」了，其實拆解來看就是針對 input 元素的某些事件監聽，然後抓取元素值來檢查，做出對應的反應，應該就可以達到我要的功能了

@chinghanho ，謝謝你的分享，很有趣的功能，剛剛玩了一下，我最後覺得這個 gem 的 code 對我來說太多 magic ，應該不會嘗試改造它了，改不動...
