### ISSUE TITLE
請問大家針對下面的Model是否有最佳漂亮的解法?

### ISSUE THREAD

**Issue by willycode** [rubytaiwan/AMA#48]
```ruby
# Try to create a "Person" model,that we can use the “children” method below.
tom = Person.create(name: “Tom”)
may = Person.create(name: “May”, parent: tom)
syd = Person.create(name: “Syd”, parent: tom)
tom.children.map(&:name)
#=> [“Syd”, “May”]
```

```ruby
# Furthermore, can you design a "grandchildren" method that we can use it like this?
wen = Person.create(name: “Wen”, parent: syd)
jon = Person.create(name: “Jon”, parent: may)
tom.grandchildren.map(&:name)
#=> [“Wen”, “Jon”]
```

出處：[原Gist檔案](https://gist.github.com/willycode/664462731dc94e603c46)

**Comment by adlerhsieh** [comment]
看起來你是想要解決某個作業或指定的問題？

Model的實作算是Rails當中很基本但也很複雜的部份，從頭到尾描述的話可能寫3個小時也寫不完，而且網路上已經有非常多此類教材，不管收費與否都非常專業，建議參考網路上的現成教材，只要整個操作過一遍，要解開這兩題就不是難事了。如果我們在這邊直接把解答的code秀給你看，應該對你也沒有幫助，因為如果不知道Model關連的意義在哪，碰到下一題類似的一定還是不會。

教材部分建議可以從實戰聖經的[這篇Active Record基本說明](https://ihower.tw/rails4/activerecord.html)入手，對於Active Record說明非常清楚，如果有點無法理解，我之前有寫過一篇[尋找教材的參考](http://motion-express.com/blog/20141003-ruby-on-rails-learning-material)，也可以參考一下。

**Comment by adlerhsieh** [comment]
另外幫你稍微整理一下貼code方式，有其他人想回答的話應該比較快就catch到意思 :)

**Comment by willycode** [comment]
感謝,先說明這不是作業,目的是要挑戰自己能不能活用Model
自己有嘗試先建三個Model分別是Person Children Grandchildren
後來發現這樣行不通...

看了Active Record有很多部分,不知道哪個部分才是適合的？
是否能給一個明確方向,不是只是大方向

**Comment by sunkai612** [comment]
可以使用 self join table
http://guides.rubyonrails.org/association_basics.html#self-joins

Person 多開一個欄位 `parent_id`

parent method 就去找 Parent id 為 `parent_id` 的人
grandchildren 則是找 children 的 children 就可以了

**Comment by zackexplosion** [comment]
建議貼 Code 的時候貼可以執行的 Code 。
https://gist.github.com/zackexplosion/89b56e68729c4c252d7c

**Comment by timfanda35** [comment]
想到了 [ActsAsTree](https://github.com/amerine/acts_as_tree) gem，或許可以做為參考

**Comment by adlerhsieh** [comment]
@willycode 抱歉，因為我的理解錯誤才以為這是作業的問題。

補充一下樓樓樓上的作法：

```ruby
class Person < ActiveRecord::Base
  has_many   :children, class_name: "User", foreign_key: :parent_id
  belongs_to :parent,   class_name: "User"

  def grandchildren
    self.class.where(parent_id: children.ids)
  end
end
```

**Comment by minjindang** [comment]
感謝大家:)
