### ISSUE TITLE
[Windows] 解決RubyGems的SSL憑證過期問題

### ISSUE THREAD

**Issue by minjindang** [rubytaiwan/AMA#50]
If you use Windows and come across the problem:
`Unable to download data from https://rubygems.org/ - SSL_connect`

Run this from Command Line:

```
gem source -a http://rubygems.org/
```

**Comment by zackexplosion** [comment]
之前有碰到一次是 AMAZON 被打爛 這些遠端站台全死...

**Comment by minjindang** [comment]
希望不要再遇到><"
