### ISSUE TITLE
要限制current_user只讀得到自己的資料，但無法正確劃分權限，一直回傳所有資料

### ISSUE THREAD

**Issue by fredchen90** [rubytaiwan/AMA#51]
大家好,

我有三個model
1. user 
   has_one :recorditem, through: :record
2. record
   belongs_to :user  has_one :record_item
3. record_item
   belogns_to :record

我在寫一個記帳的功能

一個使用者有多筆記錄,然後我要把屬於該使用者的多筆記錄撈出來,我這樣寫哪裡有問題嗎?

**Comment by sunkai612** [comment]
你覺得有什麼問題呢 :raising_hand:

**Comment by zackexplosion** [comment]
實際執行一次不就知道了?

**Comment by fredchen90** [comment]
抱歉,我沒有講清楚

因為我寫完以後 我到我的首頁去看發現不同登入者都看的到這些資料

所以我不知道我是不是model寫出問題

**Comment by sunkai612** [comment]
那請問首頁相對應的 controller action 是怎麼寫的呢 :eyes: ？

**Comment by zackexplosion** [comment]
方便把 Code 貼上來嗎？

**Comment by chinghanho** [comment]
這裡只有 model 之間的關聯。至於資料怎麼撈的，可以貼出來看看。

**Comment by fredchen90** [comment]
`index.html.erb`

``` ruby

<div class="col-md-12">
  <div class="new_record">
    <%= link_to("New Record", new_record_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Description</td>
        <td>price</td>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |record| %>
        <tr>
          <td>#</td>
          <td><%= link_to(record.description, record_path(record)) %></td>
          <td><%= record.price %></td>
          <td>
              <%= link_to("Edit", edit_record_path(record), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", record_path(record),    class: "btn btn-sm btn-default", 
                          method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
        </tr>
      <% end %>
    </tbody>
    <td>
      <td>Total</td>
      <td><%= render_total_price %></td>
    </td>
  </table>
</div>
```

`records_controller.rb`

``` ruby
class RecordsController < ApplicationController

    before_action :authenticate_user!

    def index
        @records = Record.all
    end

    def new
        @record = Record.new
    end

    def create
        @record = Record.new(record_params)
        if @record.save
            redirect_to records_path
        else
            render :new
        end

    end

    def edit
        @record = Record.find(params[:id])
    end

    def update
        @record = Record.find(params[:id])
        if @record.update(record_params)
            redirect_to records_path
        else
            render :edit
        end
    end

    def destroy
        @record = Record.find(params[:id])
        @record.destroy
        redirect_to records_path
    end

    private

    def record_params
        params.require(:record).permit(:description, :price)
    end

end
```

**Comment by sunkai612** [comment]
``` ruby
def index
  @records = Record.all
end
```

   ^^^^^^^^^^^^^^^^^^^^ 這樣就會把全部的 `Record` 都撈出來呀

或許試試看只撈目前使用者的資料？

**Comment by adlerhsieh** [comment]
補充樓上，你在問題中說到要撈出「屬於該使用者的多筆記錄」，但在model當中你指定`User`是`has_one: recorditem`，如果你希望該使用者有多筆資料，應該要使用的是`has_many`。

另外，依照Rails的預設命名方式，`recorditem`應該是`record_item`，才找得到Model名稱是`RecordItem`。

**Comment by chinghanho** [comment]
``` ruby
@records = current_user.records
```

**Comment by fredchen90** [comment]
恩..我知道是@records = Record.all 撈全部資料

一開始我沒有做devise所以我可以無限增加修改移除

現在加入使用者功能後 突然卡住到底該如何去做分別呢?

**Comment by sunkai612** [comment]
如果有用 devise 的話，就用 @chinghanho 說的 `current_user` 吧 :smile: 

沒有的話，就在 application controller 自己加一個 `current_user` 的 method 吧 :)

**Comment by fredchen90** [comment]
恩我改了
@records = current_user.records

就會出現undefined "records" method

所以這部分我model那邊就要重新設計對嗎?

抱歉..我對model關聯式不太會用腦袋轉不過來

**Comment by sunkai612** [comment]
要記得把剛剛 @adlerhsieh 說的 model 內容也要改喲！

**Comment by adlerhsieh** [comment]
建議你依照幾個步驟檢查：
1. `Devise`是否有依照步驟安裝完成？也就是[官方文件所提供的安裝方式](https://github.com/plataformatec/devise#getting-started)。
2. 上述步驟若有完成，在controller當中應該會自動產生變數`current_user`，如果沒有的話，就會遇到 `undefined variable or method "current_user"` 這個錯誤訊息。建議使用`puts current_user`這樣的方式來檢查，如果在Terminal當中有顯示你目前登入的user，那就沒錯了。

照你剛提供的訊息，Devise應該是有安裝完成，只是需要你先確認一下`current_user`沒問題。

接著主要的問題是在Model的關聯沒有建立完成，如果要使用`records`這個method，關連應該要寫成`has_many :records`，後面那個symbol `records`就是會當做你用來抓取Record這個Model裡面的資料用的。反之，如果你是用`has_one :record`，那你的method名稱就要叫`record`，寫法變成`current_user.record`。

所以我建議你的User Model關連寫法應該是：

``` ruby
has_many :records
```

接下來controller裡面才改成：

``` ruby
def index
  @records = current_user.records
end
```

這樣應該就沒問題了。

**Comment by fredchen90** [comment]
謝謝你  我已經解決了

的確是卡在has_many :records

**Comment by adlerhsieh** [comment]
:+1:
