### ISSUE TITLE
SPA session auth management

### ISSUE THREAD

**Issue by SDLyu** [rubytaiwan/AMA#54]
目前用正在玩 React 做 SPA，但遇到了登入和驗證的問題

想請問在無後端 template render 的情況下，如何做到 session 和 auth management? :worried: 

目前想到最簡單的方法是每次請求都向 server 驗證，好像太沒效率了 :confused:

**Comment by sinorga** [comment]
可以參考看看 [JWT](http://jwt.io/)

**Comment by yorkxin** [comment]
Cookie 就可以了

**Comment by SDLyu** [comment]
thx @sinorga 我再試試 JWT :+1:

**Comment by chentsulin** [comment]
session 應該跟有沒有後端 template render 沒什麼關係？SPA 跟以往的方式對於 session 應該是沒有差別的，session_id 也是照常紀錄，只是沒有後端 template render 就無法用類似 server rendering 的方式把一些東西注入 React。
