### ISSUE TITLE
Mobile App UI 設計問題

### ISSUE THREAD

**Issue by JuanitoFatas** [rubytaiwan/AMA#55]
例如要設計一個 App 的界面，希望這個界面可以在 iOS 跟 Android 系統上都長一樣。

會用哪個尺寸開始設計，以及怎麼去適應到其他尺寸，並出圖給工程師。

謝謝！

**Comment by zackexplosion** [comment]
通常都拿 iPhone 當第一版吧，畢竟比較好處理，用的人又多

**Comment by motephyr** [comment]
先有一個版本 只要不是太少見的尺寸不管是android或ios都可以
比如說以iPhone 6為主好了 它可以用autolayout來處理不同畫面比例的情況

那android要出的比例比較多，但它可以讓你用不同的layout規則來呈現
雖然多少會有差異但大家好像都習慣 主要是圖片的尺寸要多出幾種解析度才能滿足不同的狀況
(印象中是說至少三種，齊全一點五種)

最近的風格好像比較紅的是material design，可以參考看看。

**Comment by trisix** [comment]
一些個人經驗，先大概整理了一下，給你參考看看：

原則上還是先做一版，我通常是選擇iOS，只是在做的時候，考慮下列因素
- 做圖解析度：@1x 或 @2x
  - 國外大部分看到目前都是用@1x做圖，也就是如果要拿iPhone 6 的裝置，一開始會使用375x667 的版面大小，好處是在縮放成其他尺寸的asset的時候，比較不用擔心尺寸數字沒算好，縮放後出現0.5 pixel的圖，而造成畫面模糊的狀況
  - 用@2x也行，因為過去習慣，所以我自己是用@2x，但在設計的時候，要注意Control的尺寸，Margin和Padding等儘量至少是偶數（有人甚至會要求到必須是8的倍數，方便縮放），這樣可以避免前一點說的，縮放後出現0.5 pixel的圖，而造成畫面模糊的狀況
- iOS & Android 解析度對應
  - 看是用@1x或是@2x作圖，然後參考下面列尺寸對照縮放，產生asset
  - @1x => iOS:@1x Android:MDPI
  - @1.5x => Android:HPI
  - @2x => iOS:@2x Android:XHDPI
  - @3x => iOS:@3x Android:XXHDPI
  - @4x => Android:XXXHDPI
  - MDPI跟HDPI在現在的Android裝置上應該比較少會用到
- 一開始的畫面大小選擇：iPhone 5/5S（640x1136@2x） 或 iPhone 6(750x1334@2x)，
  - 如果要考慮iOS 向下相容，在比較小的螢幕也可以完整顯示的話，可以用iPhone 4/4S(640x960@2x)先限制畫面大小，或是加參考線
  - iPhone 5/5S/6的解析度都是@2x
  - 而iPhone 6的解析度跟一般常見的Android手機的尺寸（720x1280，XHDPI）是相對更接近的，所以轉換上可能會比較容易
  - 選用iPhone5/5S的原因，則是避免一開始用iPhone6做圖，畫面上已經太多東西，實際上在iPhone5/5S上已經太滿的狀況
  - 反過來說，選用小畫面的作圖，在比較大畫面上，比較不會影響太大，最多就是因為有點空，而作些微調
- 工具推薦
  - Sketch：輕薄短小的工具，輸出產生縮放的Asset很方便，可結合其他許多強化工作流程的第三方服務，有很多第三方Plugin
- 考慮對應Control或可替代Control，必要時，No UI Design Pattern甚至Anti UI Design Pattern
  - 大部分的UI Control在iOS跟Android上都可以找到對應
  - 有些可能需要自己額外刻或使用第三方Library
  - 有些資訊結構性上的差異，如果覺得不適合，其實不見得真的要完全走那樣的Pattern
    - 譬如說：Material Design很希望大家都用Drawer(Side Menu)，但可能有實務上的考量，或是效果上的考量，不見得適合在你的App使用，而iOS你打算用Tab Bar，所以Android上可能就需要做對應的客製化Control設計
- 注意系統UI的尺寸上差異
  - 像是Status Bar，或是App Bar(Android)/Navigation Bar(iOS) 等，高度是不同的
- 定義自己的一套Margin和Padding，和在iOS跟Android的對應轉換方式
  - Material Design有定義一套自己的Margin跟Padding，但如果你覺得不適合，你可以參考那些規範，自定和小幅調整
  - iOS一開始在作圖的時候，也是先定義這整套Margin跟Padding，以及跟Android那邊是怎麼對應
- 較大尺寸的裝置調整
  - 假設先不考慮Adaptive UI，以這樣的方式做出來的東西，有可能會在尺寸較大的實機上顯得太小，這時候可以利用Android的layout-large跟layout-xlarge提供App不同的Layout來調整，同時也可以稍微把同解析度用的Asset圖調整大一些，另外輸出來一組來讓這些Layout使用。
  - 會需要-large跟-xlarge的layout，主要會是在較大尺寸的平板（譬如說7吋或10吋）

**Comment by JuanitoFatas** [comment]
@trisix 感謝詳細回覆。多謝，多謝！
