### ISSUE TITLE
直接下 SQL string，但string中含有單引號 '

### ISSUE THREAD

**Issue by jcsky** [rubytaiwan/AMA#57]
單引號會造成 SQL 指令錯誤 

為了一次新增很多的假資料作測試，我用了以下的寫法

``` sql
CONN = ActiveRecord::Base.connection
inserts = []
time = Time.now.to_s(:db)
100.times do
inserts.push "('#{Faker::Internet.email}', '12345678', 0, '#{country.sample}', '#{Faker::Avatar.image}', '#{Faker::Name.name}', '#{time}', '#{time}')"
end
sql = "INSERT INTO users (email, encrypted_password, role, country, fb_image, name, created_at, updated_at) VALUES #{inserts.join(", ")}"
CONN.execute sql
```

不過卻遇到了個問題，就是 name 裡頭會出現單引號，SQL string遇到多出來的單引號 ' 就掛了......
有大大可以教一下我這部份有什麼解法嗎??

**Comment by hechien** [comment]
為什麼不用 Model 直接建呢？

如果是這種問題，可以用 `%Q{}` 包覆字串來處理

`%Q{'#{Faker::Internet.email}'}` 來繼續串下去

**Comment by adlerhsieh** [comment]
或是用escape符號處理，變成`\'`

但我也覺得既然有`ActiveRecord::Base.connection`代表是可以用ActiveRecord來處理的，建議用ActiveRecord的語法直接建，會少很多麻煩

**Comment by adlerhsieh** [comment]
但我也覺得既然有`ActiveRecord::Base.connection`代表是可以用ActiveRecord來處理的，建議用ActiveRecord的語法直接建，會少很多麻煩

**Comment by jcsky** [comment]
用 model 直接建是指 ...?? User.create 一筆筆新增會很久，我想新增上萬筆資料
實測  `%Q{'#{Faker::Name.name}'}` 會讓SQL string 變成... `'%Q{Brianne Howe}'`
`'%Q{#{Faker::Name.name}}'` 結果也會把  %Q和名字一同輸出

**Comment by hechien** [comment]
我的意思是

``` ruby
inserts.push %Q{'#{Faker::Name.name}'}
```

這樣寫

至於用 Model

``` ruby
100.times do
  User.create(name: Faker::Name.name)
end
```

**Comment by hechien** [comment]
另外， create 是可以傳陣列進去的，你若真想要一次上萬筆塞進去，也可以把陣列傳進去
其實上萬筆不會花你太多時間，放心

**Comment by jcsky** [comment]
喔喔~!! 試驗中....... 謝謝大家 ^^

``` ruby
inserts.push %Q{('#{Faker::Name.name}')} 
```

這樣可行!

**Comment by chinghanho** [comment]
抱歉不是回答問題，只是提供另一個解法：

``` ruby
gem 'activerecord-import'
```

``` ruby
User.import Array.new(9999999) { User.new name: Faker::Name.name }
```

此外 `create` 帶陣列其實還是多條 query statement：

``` ruby
User.create Array.new(9999999) {{ name: Faker::Name.name }}
```

**Comment by ilake** [comment]
http://apidock.com/rails/ActiveRecord/Sanitization/ClassMethods/sanitize_sql_for_conditions

**Comment by zackexplosion** [comment]
@hechien  `create` 傳陣列進去其實還是會產生 N 筆 SQL，跟用 `100.times` 的意思差不多吧?

**Comment by hechien** [comment]
@zackexplosion 你是對的，不好意思
