### ISSUE TITLE
API 監聽檔案及處理的.xml檔案應該放在專案的哪？

### ISSUE THREAD

**Issue by jcsky** [rubytaiwan/AMA#58]
我的 api_listen.rb 會將持續收到的 xml 個別存成 datatime.xml file
另外我的 Rails app 希望去讀取 xml file 的檔案列表及內容

所以我是不是該把 api_listen.rb 放在 rails_app/config 下，xml output 到 rails_app/config/api_xml/datatime.xml

然後在 terminal 下額外去執行 api_listen.rb ( 目前我用 nohup ruby myscript.rb > myscript.log & ， 因為用 daemons 時 Dir.mkdir 會出錯 )

**Comment by adlerhsieh** [comment]
一般來說Rails無限制檔案的存放地點，因此照你說明的作法ok。

如果要符合Rails提供的檔案結構建議，那建議：
1. `api_listen.rb` 檔案可放在 `lib` 資料夾底下，理由可參考 [Code Climate 的一篇部落格文](http://blog.codeclimate.com/blog/2012/02/07/what-code-goes-in-the-lib-directory/)。
2. 在`public`資料夾底下建一個`data`資料夾，把所有各別產生的`.xml`檔案放進去。如果覺得放在`public`不放心，可以另外開一個資料夾在根目錄，就不會對外開放。透過處理而產生的檔案不建議放在`config`資料夾底下，因為那邊的邏輯比較屬於「關於本app的設定」，而產生的資料比較像是各種data。

另外，不太清楚你說「api_listen.rb 會將持續收到」的意思，是說會有其他service傳http POST request到你的app上，再透過這個`api_listen.rb`裡面定義的class來處理內容？如果是的話，建議將這個檔案放在`app/services`底下，因為屬於controller要讀取但跟model無關的內容。反之，如果純粹是從terminal去執行的話，放`lib`資料夾就比較適合。

**Comment by jcsky** [comment]
api_listen.rb 在 listen 一個 stomp protocol 的 topic (對方server使用ActiveMQ)，會一直收到 XML data
但和 rails_app 完全獨立運作

看完您的說明，
我打算將它放在 lib 中，並在根目錄下新建一個資料夾存放 api_listen 產生的 xml file 
謝謝!!
