### ISSUE TITLE
初學者學運算法－線上資源

### ISSUE THREAD

**Issue by bchan419** [rubytaiwan/AMA#59]
請教一下，要練習運算法 (algorithm) 有哪些線上課程 / 題目比較適合初學者的？中英文都可。

**Comment by adlerhsieh** [comment]
[LeetCode](https://leetcode.com/) 可以有困難度的選擇，且很多經典題目

**Comment by timfanda35** [comment]
[演算法筆記](http://www.csie.ntnu.edu.tw/~u91029) 有中文教學，程式範例是c/c++

[Codewars](http://www.codewars.com)有許多題目，能看到其他人解題的程式碼，學習到很多程式技巧，題目有區分難易度提供選擇

**Comment by kraytruthg** [comment]
這個網站也不錯 [Codility](https://codility.com/programmers/lessons/) 

裡面有演算法的教學，以及相關練習題
在解題時，可以先把 test case 寫好，語言也有 Ruby 可以選擇

**Comment by JuanitoFatas** [comment]
Can also try: [Projec Euler](https://projecteuler.net). Enough :meat_on_bone: for this issue, closing.

**Comment by hungmi** [comment]
今天剛好看到，分享了蠻多書的，可以參考一下
http://zh.lucida.me/blog/on-learning-algorithms/
