### ISSUE TITLE
omniauth-facebook使用問題

### ISSUE THREAD

**Issue by ghost** [rubytaiwan/AMA#60]
大家好，我目前依照下面網址來做透過facebook來做會員認證，使用devise以及omniauth-facebook。
https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview

在Facebook Developer中的APP我是用website，然後Site URL用 http://www.localhost:3000/ 。
在最後卻出現「應用程式的設定不接受這個網址．．．（ http://imgur.com/qbVmlgs ）」，如圖所示。
請問是哪個環節出了問題呢?
謝謝

**Comment by hechien** [comment]
你可以先嘗試使用 `pow` 這種東西來執行你的 Rails project ，如此的網址應該就可以通過 Facebook 的要求

第五點 http://blog.xdite.net/posts/2011/10/09/10-ruby-developer-must-have-tools

**Comment by hrs113355** [comment]
Settings > Advanced > Valid OAuth redirect URIs

![](http://i.imgur.com/Sm3He11.png)

不只 Site URL ，也要設定你的 `redirect_uri`

**Comment by ghost** [comment]
謝謝hrs113355 ，設定了redirect URIs就解決了。

也謝謝hechien提供的資訊，用POW之後就不用一直重新啟動server。

**Comment by hrs113355** [comment]
:+1:
