### ISSUE TITLE
如何做出首頁線上人數與流量?

### ISSUE THREAD

**Issue by fredchen90** [rubytaiwan/AMA#62]
大家好

1.請問有什麼方法可以做出首頁現在線上人數跟訪問數嗎?

2.要如何將devise註冊使用者數量統計出來呢?

**Comment by GeorgioWan** [comment]
第二題單純用 **User.count** 行嗎？

**Comment by zackexplosion** [comment]
線上人數要即時的還是非即時呢? 這部份蠻麻煩的

**Comment by fredchen90** [comment]
to GeorgioWan  : 可以

to zackexplosion : 
因為有一個想法是這樣的,當前在線：註冊用戶人數， 遊客人數。今日累計訪問：註冊用戶人數， 遊客人數。 類似這樣

**Comment by fredchen90** [comment]
那個關於註冊用戶的統計

現在透過GeorgioWan 大大知道可以用count直接算出數量!

如果我今天想要單純算初今天註冊過的數量,要如何去寫呢?

抱歉...小嫩嫩我滿多想法但是這些點子真的很苦手....

**Comment by zackexplosion** [comment]
比起直接告訴你答案，我覺得你應該先搞懂這功能需要哪方面的知識，用 Rails 的話建議你先把 ActiveRecord 搞懂吧

https://ihower.tw/rails4/activerecord.html

**Comment by fredchen90** [comment]
好的!

**Comment by GeorgioWan** [comment]
加油:grin:  fighting！:muscle:

**Comment by fredchen90** [comment]
問一下ActiveRecord 

有沒有白話可以大概解釋一下?

因為要做功能的時候我很難去把這觀念建立起來!

是否有經驗可以分享呢?

**Comment by ilake** [comment]
= =

**Comment by ilake** [comment]
http://guides.rubyonrails.org/active_record_basics.html

> 1 What is Active Record?
> Active Record is the M in MVC - the model - which is the layer of the system responsible for representing business data and logic. Active Record facilitates the creation and use of business objects whose data requires persistent storage to a database. It is an implementation of the Active Record pattern which itself is a description of an Object Relational Mapping system.

**Comment by jcsky** [comment]
話說即時的在線人數應該怎麼做呢? 頂好奇的
當user把瀏覽器頁面關掉時，Rails 會有 event 可以偵測嗎?

如果沒有的話，
在前端用 js 定時丟訊息到後端似乎可以做到
一般大家怎麼做的呢?

**Comment by zackexplosion** [comment]
> 在前端用 js 定時丟訊息到後端似乎可以做到

現在有 websocket 可以用，Client 斷線的時候 Server 會知道

另一個方法是利用 Server 上的 Session 總數來做統計，但是沒辦法很即時就是了，只能把 Session 的過期時間弄短，才會變準。但是這樣做的話又有另一些問題就是了.........

**Comment by AnNOtis** [comment]
如果有使用 Google Analytics，可以參考一下 Real Time Reporting API

**Comment by ilake** [comment]
先定義你的`在線`，再想該怎麼做

**Comment by ilake** [comment]
bump @fredchen90

**Comment by fredchen90** [comment]
這議題暫時沒在研究,我先關掉
