### ISSUE TITLE
切換頁面後 javascript 失效問題

### ISSUE THREAD

**Issue by GeorgioWan** [rubytaiwan/AMA#63]
大家好，
昨天突然發現一個問題，
我在開啟網站頁面時(main page)，js 是有觸發反應的，
但當前往**不同頁面**後卻失效了，使用開發者工具(F12)查看 code 也有被編出來，
若在此時重新整理(F5)該頁面，js 又可以 work 了！

想請教大家是否遇過此問題？

_p.s. 目前於 DEVELOPMENT 階段_

**Comment by adlerhsieh** [comment]
好像跟我過去開發時遇到 [turbolinks](https://github.com/rails/turbolinks) 的情況有點像，請問專案中也有`gem "turbolinks"` 嗎？如果有的話解除安裝再試一次看看。

**Comment by GeorgioWan** [comment]
已解！
抱歉，剛才查看 closed issue 才發現有[**相關串**](https://github.com/rubytaiwan/AMA/issues/30)
經由該串也去重新了解了一下 [**Turbolinks**](https://ihower.tw/rails4/ajax.html)

不過還是覺得很有趣，turbolinks 改善切換頁面的速度，但會造成 js 失效，
為了改善失效問題，必須把 tubolinks 移除... 
怎麼想都覺得怪怪的~"~

**Comment by adlerhsieh** [comment]
:+1:

**Comment by zackexplosion** [comment]
通常只是 元素的 BINDING 沒有連結到而已，因為用 Turbolinks 換頁之後並不會重新觸發 document.ready 事件，所以原先寫在 document.ready 的 code 就會跑不到了

**Comment by GeorgioWan** [comment]
太好了！:raised_hands:
謝謝 @adlerhsieh 和 @zackexplosion 
大置上了解它的運作和用意了
參考 Turbolinks 中的 [**opting-out-of-turbolinks**](https://github.com/rails/turbolinks#opting-out-of-turbolinks)
我的解法是在我不需要它的時候不用它 XDD
不知道是否可以幫忙上個 javascript 或 turbolinks 標籤
希望有遇到這問題的人可以參考參考 :smile::smile:

**Comment by hechien** [comment]
雖然已經關串，但想補充一下
可以搭配使用 https://github.com/kossnocorp/jquery.turbolinks 來避免類似問題發生，如果你專案中有使用 jQuery 的話

**Comment by GeorgioWan** [comment]
@hechien 謝謝
原來還有這個可以用 :+1:

**Comment by hechien** [comment]
@GeorgioWan 不會
Turbolinks 其實不用關，但是要記得引入的地方也改成
`<%= javascript_include_tag :application, defer: true %>`
這樣，就不會影響到 DOM 載入的速度，然後載入後才會執行 JavaScript

推薦的 application.js 寫法是

``` javascript
//= require jquery
//= require jquery-ujs
//= require 你的其他 coffee / js 檔案
//= require jquery.turbolinks
```

**Comment by GeorgioWan** [comment]
mmm 目前先暫用 no_turbolink 寫 helper 解決了XDD

晚點來試試 jquery.turbolinks
這樣想的話... 把`//= require_tree .`包在中間應該也是可以生效的囉~

**Comment by GeorgioWan** [comment]
@hechien 感恩感恩, 簡單易用:joy: :joy:

**Comment by hechien** [comment]
@GeorgioWan 我其實不愛 `require_tree` XD
但是放在中間是可行的沒錯
