### ISSUE TITLE
如何儲存多個不需sql動作的資料？

### ISSUE THREAD

**Issue by bugtender** [rubytaiwan/AMA#64]
大家好
我需要儲存一筆沒什麼用但是又必須要儲存的資料
所以我想要把它存成hash格式
每個user有固定三個名稱為top, mid, adc的box， box有他自己的width, height, depth屬性

``` ruby
=> user.box
=> { 
      top=> { width=>1, height=>5, depth=>6 },
      mid=> { width=>3, height=>2, depth=>7 },
      adc=> { width=>8, height=>5, depth=>2 }
   }
```

然後在user edit 的時候可以順便編輯他

![edit page](http://i.imgur.com/Ty85IeQ.png)

我嘗試過使用serialize，hstore 但是都沒有成功過
目前使用hstore，box 欄位是hstore格式，
只有達成輸入進去，但是edit的情況他不會顯示

``` ruby
# user.rb
class Users <ActiveRecord::Base
   store_accessor :box, top, :mid, :adc
end
```

``` slim
# edit page slim
= form_for :user do |f|
  = f.fields_for :box do | box |
    = box.fields_for :top do | top |
       = top.text_field :width
       = top.text_field :height
       = top.text_field :depth 
    = box.fields_for :mid do | mid |
       = mid.text_field :width
       = mid.text_field :height
       = mid.text_field :depth 
    = box.fields_for :adc do | adc |
       = adc.text_field :width
       = adc.text_field :height
       = adc.text_field :depth 
```

請問大家有沒有比較好的解法或是參考的資料，謝謝

**Comment by hechien** [comment]
試試看在 model 中加上這段 code 看可不可以動

``` ruby
def top
  box.top
end
```

**Comment by abookyun** [comment]
看起來現在的問題是，不知道如何從 form 中編輯 hstore 的資料。找到一些資料可以參考：

如果你是 Rails 3 可以看看 https://github.com/diogob/activerecord-postgres-hstore
如果是 Rails 4 原生就有支援 hstore http://api.rubyonrails.org/classes/ActiveRecord/Store.html
如果你用 SimpleForm https://gist.github.com/lucasdavila/3715290
如果用純 form 的話看來可以用這個 https://coderwall.com/p/hnhd4w/hstore-and-rails-form

**Comment by bugtender** [comment]
感謝兩位大大回覆，在嘗試了幾次之後
終於成功的做出來了，感謝

**Comment by abookyun** [comment]
:shipit:
