### ISSUE TITLE
在ec2選用ubuntu14.04來裝nginx

### ISSUE THREAD

**Issue by foreverbule2003** [rubytaiwan/AMA#65]
各位前輩好, 我是照著下面的連結
http://vinn.tw/blog/aws_note
到了3.Nginx Setting的步驟

/opt/nginx/conf/nginx.conf的設定如下
server {
        listen       80;
        server_name  my_ec2_public_ip;
        passenger_enabled on;
        #charset koi8-r;
        #access_log  logs/host.access.log  main;
}

修改完後有restart nginx
但是從瀏覽器上無論是鍵入my_ec2_public_ip
或是my_ec2_public_DNS都無法連到（ERR_CONNECTION_TIMED_OUT）

ps1: 至少該出現nginx的歡迎頁面對嗎？
ps2: 該教學應該是沒問題的，本機照著教學server_name使用127.0.0.1是可以看到歡迎畫面的

**Comment by chinghanho** [comment]
可能是 EC2 上的 security group 沒把 80 port 打開。

**Comment by foreverbule2003** [comment]
將server_name的值替換成Public DNS就可以進去了 
還是謝謝@chinghanho熱心的回覆

**Comment by bugtender** [comment]
Oops 可能是我沒寫清楚 :sob:

**Comment by foreverbule2003** [comment]
竟然釣到作者本人了(誤
@viflin 你寫得很清楚, 還請多多寫文造福人群XD
是我太嫩(前天才開始用EC2)
OS: 還有好多蠢問題想問阿
