### ISSUE TITLE
設計「管理者」角色的問題

### ISSUE THREAD

**Issue by festime** [rubytaiwan/AMA#66]
最近想在個人專案裡加入管理者相關權限，看到[這篇文](http://railsfun.tw/t/devise-robots-txt/376)說在 users table 加入類似 `is_admin` 這種欄位來判斷是否為管理者，可能有一些安全疑慮，最好另外寫一個 model 來處理管理者的資料，所以目前嘗試朝這方向實作

先說一下我的網站上的管理者比起一般使用者有多出哪些權限好了，這應該會跟採用哪些設計比較合適有關係，預期管理者可以「刪文、刪留言、禁止使用者發文和留言、新增文的類別標籤、置頂某些貼文」

我的 `User` model `has_many :topics`, `has_many :posts` ， `Admin` is a `User` ，所以我想也許可以讓 `Admin` < `User` ，在 Admin 存取 admins table ， User 存取 users table 這種慣例情況下，為了 `Admin` 和 `Topic`, `Post` 之間的關聯，資料表似乎得多出一些像 `admin_id` 這種 foreign key 欄位，感覺不是很好的方式

或者如果讓 `Admin` 和 `User` 存取同一個 table ，在沒有 `is_admin` 之類欄位的情況下，又怎麼判斷使用者是否為管理者呢？

目前我想到的辦法是讓 `Admin` 存取 admins table ，裡面只放 email 資料，然後定義

```
class User < ActiveRecord::Base
  # public
  def is_admin?
    Admin.find_by(email: self.email) ? true : false
  end
end
```

如果使用者的 email 有在 admins table 裡就代表他是管理者，這種做法不需修改 users table schema 、不用添加 foreign key ，但這有沒有什麼潛在的重大缺點或問題我沒想到的？或是有什麼更好方式？ :bow:

**Comment by adlerhsieh** [comment]
JC大這個作法我沒試過，提供另一個我有經驗的作法。

同樣在`User`當中設定`is_admin`欄位，但不要在新增or更新時去動到這個欄位，亦即你每次更新`User`時，一定都是用標準的Rails `create` 或 `update` 方法，並在strong parameters相關設定中不加入`is_admin`這個欄位。如果要更新此欄位，一定得經由ssh至db當中更改，對於admin人員不常變動的專案來說還算方便及安全。

接著將user和admin的登入方式切開，以防有心人士攻擊。基本上就是設定另一個登入入口，而這個網址只有admin人員才知道，並加入`robot.txt`當中不讓搜尋引擎收錄，若用一般user登入的方式登入，就可以用`User.where.not(is_admin: true)`來防暴力破解密碼。

**Comment by motephyr** [comment]
考慮一下你的網站想要有多安全or多方便，其實就是這樣。
如果你用一個正常使用者的登入方式卻想要有admin的能力，那必定會設類似is_admin的值
表示你登入的這個角色比一般使用者可以多操作一些事。
"刪文、刪留言、禁止使用者發文和留言、新增文的類別標籤、置頂某些貼文"看起來其實還正常。

但如果這個角色的能力是可以做active_admin或rails_admin的事情的話，
(類似可以直接修改資料，查閱整批資料等)，那建議還是另開入口，另設帳號比較保險。

**Comment by chinghanho** [comment]
要不要拆成兩個 model 我會看使用情境。

如果原本兩個 model 的事務邏輯幾乎重疊，只是因為安全問題拆開，說服力略嫌不足，因為個人認為 `is_admin` 安全問題還好，主要是觀念清不清楚。

**Comment by festime** [comment]
我的 `User` 和 `Admin` 邏輯幾乎是完全重疊的，差別只在於要存取某些頁面或動作時，必須確認是管理者才放行，管理者不能直接修改資料庫資料，以這樣使用情境來說，目前的做法我認為還算可以接受，程式碼和舊有 table schema 也不用什麼變動， admins table 對外幾乎是封閉的，只能透過 console 或是管理者新增管理者的方式來修改，那只要管理者不要被駭或是下錯指令，就不會有問題

**Comment by imgarylai** [comment]
在使用者管理權限上面，我用 [rolify](https://github.com/RolifyCommunity/rolify) 這個 gem ，如果有需要，還可以再搭配 [cancancan](https://github.com/CanCanCommunity/cancancan)

幾個我喜歡的優點：
1. 只有一個 `user` table，而且不用加上一個 `is_admin` 的欄位，所以不用怕被塞
2. 多重角色：如果有很多種管理員身份，例如：最高管理員等級、一般管理員、一般使用者，針對不同的角色去設定他們的權限，可以自幹或是搭配 cancancan 
3. 可以直接針對 resourse 去做管理

對我來說最吸引的點還是多重角色的部分，因為我們的網站角色很多，如果每個角色都要有model會崩潰的（每個model的權限差異也很大）

**Comment by festime** [comment]
謝謝 @imgarylai ，看起來是個不錯的 gem :+1:
