### ISSUE TITLE
Rails 4:如何使用Ahoy的gem來製作紀錄user操作資訊?

### ISSUE THREAD

**Issue by vneverz** [rubytaiwan/AMA#67]
先感謝各位前輩願意幫助後進者，自己是rails的新手，按照官方的[Ahoy gem](https://ankane.github.io/ahoy/)，安裝沒問題，但是在`How It Works`中並不是很清楚如果用ruby或javascript要如何套進自己的[練習專案](https://github.com/vneverz/socilal_album)，目前沒有找到較完整的範例，並不清楚如何套用。

假設想要在使用者按按鈕時記錄按了`Upload Photo`，

``` erb
<p>
  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">  
<%= "Upload Photo"%>
  </button>
</p>
```

按照文件Events的js說明：

``` js
ahoy.track("Viewed book", {title: "The World is Flat"});
```

要怎麼寫呢？是這樣`ahoy.track("Upload Photo", {title: "不知道怎麼填這邊..."});`
另外如果是Ruby，是要寫在controller裡面嗎 :grey_question: 

如果問題問得不清楚，煩請各位前輩不吝指教，這也能知道自己是缺乏哪方面的基礎知識，問問題也是在學習阿...

**Comment by vneverz** [comment]
後來問過其他人後，目前已經瞭解了，感謝。

**Comment by ilake** [comment]
把你了解的東西，也寫出來吧 :)

**Comment by vneverz** [comment]
好的，我試著說明，如果有不清楚或錯誤的地方歡迎指正，感謝小蟹大大的教學 :smile: 
主要是靠javascript的ajax傳送要記錄的資料到db，在資料庫裡按照安裝的方式（本人是使用MySQL）會新增`ahoy_events`及`visits`的table，在`Ahoy.js`裡面，觀看原始碼可瞭解：

``` js
  ahoy.trackAll = function() {
    ahoy.trackView();
    ahoy.trackClicks();
    ahoy.trackSubmits();
    ahoy.trackChanges();
  };
```

`ahoy.trackAll`同時會track四個event，如果要其中幾個event也可以另外寫code，一開始並不清楚
這句的意思`ahoy.track(name, properties);`，再看了資料庫記錄之後才明白。
![screen shot 2015-10-28 at 11 10 42 am](https://cloud.githubusercontent.com/assets/5225912/10778871/ed60cb22-7d64-11e5-9d23-7b3925b97b3c.png)
`name`預設的動作就是events，分為四種：
- Views
- Clicks
- Submits
- Changes

而`properties`在各自的events裡面有其對應的內容，預設用`hash`追蹤多筆。
ex `{"tag":"button","class":"close","page":"/","text":"×"}`

假設想追蹤'404'頁面訊息，用本套件的寫法可表示：

``` js
ahoy.track('404', {:params => params.inspect, :env => env.inspect})
```

除了追蹤使用者的行為，假如需要記錄系統error或log資訊，Ahoy有預設可用`Errbase`來協助支援第三方的服務，例如使用`Rollbar`這個物件。

``` ruby
class Ahoy::Store < Ahoy::Stores::ActiveRecordStore

  def report_exception(e)
    Rollbar.report_exception(e)
  end

end
```

本套件有許多其他支援的功能，主要問題解決之後未來要套用及瞭解就比較容易了！
