### ISSUE TITLE
想請教一下, Ruby 2.2 中文編碼utf8轉big5碼問題。

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#68]
如題，我試了好幾個方法，但是都失敗....本來在Ruby 1.8.7 都正常，但是換到 Ruby 2.2就不行 >"<

簡訊發送程式請參考：

require 'net/http'
require 'uri'
require 'cgi'
message = '簡訊測試abc123'
message = CGI::escape(message[0,70].to_s)
url = "http://api.message.net.tw/send.php?id=username&password=123456&tel=0911222333&encoding=big5&mtype=P&msg=" + message 
Net::HTTP.get(URI.parse(url))

結果簡訊可以送出，但是內容是空白！

另外請教一下，我在 rails console 底下想要 require 這些模組，居然都失敗！為何會這樣？

![2015-10-27 11 58 09](https://cloud.githubusercontent.com/assets/7204469/10749146/18e722be-7ca2-11e5-8efa-02aa3687edf4.png)

**Comment by hiroshiyui** [comment]
http://ruby-doc.org/core-2.2.0/Encoding.html

**Comment by adlerhsieh** [comment]
`require` 出現`false`回傳值代表已經載入過了可以使用，如果沒有該模組的話應該會出現錯誤訊息。

**Comment by afgnsu** [comment]
謝謝兩位，
剛剛參考了 iHower 大大的文章 http://www.slideshare.net/ihower/ruby-18356771
找到了答案，只要用 message = URI.encode(message[0,70].encode('Big5')) 即可 ^_^
