### ISSUE TITLE
關係為has_many through時，strong parameters跟view該如何作？

### ISSUE THREAD

**Issue by GeorgioWan** [rubytaiwan/AMA#69]
大家好，想請教一個應該算是 Association 和 Strong parameters 的問題
現在我有三個 table (company, user, company_role)，model 關係如下：
- **company model**

``` ruby
 has_many :contact_roles
 has_many :contacts, :through => contact_role, :source => :user
```
- **user model**

``` ruby
 has_many :contact_roles
 has_many :contact_companies, :through => contact_role, :source => :company
```
- **company_role model**

``` ruby
 belongs_to :company
 belongs_to :user
```

在 console 下建立聯絡人資料沒有問題，
而在寫 view 時遇到了些問題想請大家提點或建議，
問題是，我想用一個 select 選擇聯絡人(user)，form 我用 simple_form gem，
所以目前此欄位我是這麼寫的 ...

``` ruby
 <%= f.input :contact, collection: User.all.map{ |u| [u.name, u] } %>
```

而在 controller 我的 params 不知道該如何寫才能通過，目前：

``` ruby
  params.require(:company).permit(:contact => [])
```

**_我的想法**_ 是當我在 console 時建立資料我類似這麼作

``` ruby
 u=User.find(1) // 假設已有此 user 資料
 c=Company.new
 c.contact = u
```

所以，我才想說 select 時取得 user object 就 OK 了，但好像不是我想的這麼簡單 ... :stuck_out_tongue_closed_eyes: 

_p.s. 標題不知道該怎麼下才好_

**Comment by abookyun** [comment]
Try this.

``` erb
<%= simple_form_for(@company) do |f| %>
  <%= f.association :contacts, as: :check_boxes %>
  <%#= f.association :contacts, collection: User.all.map { |u| [u.name, u.id] }, as: :check_boxes %>
<% end %>
```

``` ruby
private

def company_params
  params.require(:company).permit(:contact_ids)
end
```

**Comment by GeorgioWan** [comment]
@abookyun 謝謝你唷！
參考 [simple_form Association](https://github.com/plataformatec/simple_form#associations) 可以作 check_boxes 跟 radio_button，
但試了一下還是無法試出 dropdown list 的方法 :disappointed:

**Comment by ihower** [comment]
用 checkbox:

```
<%= f.collection_check_boxes(:contact_ids, User.all, :id, :name) %>
```

或用多選 select (可以搭配 [select2](https://select2.github.io/examples.html) 的 Multiple select boxes ): 

```
<%= f.select :contact_ids, User.all.map{ |x| [x.name, x.id] }, {}, :multiple => true %>
```

Strong paramaters 的部分:

```
def company_params
  params.require(:company).permit( :contact_ids => [] )
end
```

**Comment by GeorgioWan** [comment]
@ihower 謝謝！
目前已經順利完成我要的目的 :smile: 
以下，整理一下我的作法，需要的人可以參考一下喔：
- 原本 **view** 中的 **`:contact`** 改為 **`:contact_ids`** 以傳 Association parameters

``` ruby
 <%= f.input :contact_ids, collection: User.all.map{ |u| [u.name, u.id] } %>
```
- 而在 **controller** 中的 **`:contact => []`** 改為 **`:contact_ids`** 

``` ruby
 params.require(:company).permit( :contact_ids )
```

以上，達到了我要的用選單選擇資訊！
但還是有幾個**疑問**：
1. 若以上面方法寫的話，strong parameter 填 **`:contact_ids => []`** 是收不到值的
2. 若以 @abookyun 與 @ihower 的方法解，就必須傳 **`:contact_ids => []`** 才能收到值

不知道有沒有大大能解惑 :bow:

**Comment by abookyun** [comment]
@GeorgioWan 是因為 simple_form `f.input` `f.association` wrapper 不同的緣故，前者帶值，後者帶陣列。詳情可以研究 simple_form 的 [FormBuilder](https://github.com/plataformatec/simple_form/blob/e81af052f4bbe9e17e38c668116cd1846c6d275c/lib/simple_form/form_builder.rb) 以及 rails 的 [strong_parameters](https://github.com/rails/strong_parameters#permitted-scalar-values)

**Comment by GeorgioWan** [comment]
@abookyun thanks a lot :smiley:

**Comment by abookyun** [comment]
:D
