### ISSUE TITLE
How to find a good remote job?

### ISSUE THREAD

**Issue by adlerhsieh** [rubytaiwan/AMA#7]
Hi Juanito, really appreciate your generosity. I have a question in job searching. I heard that you're currently working remotely, so I would like to ask *how to find a good remote job?*

This question contains two aspects:

1. I believe only few companies in Taiwan are willing to hire a remote developer. That's not the culture. So how do you know there are companies that are looking for remote developers (either domestic or foreign companies) ?

2. Working remotely means the employers' trust in one's attitude and ability. If you're hiring a remote developer for your company, what qualities or skills do you expect from a candidate (as a Rails developer or system operator) ?

I will be very grateful if you are willing to answer them all; however, any advice will be appreciated. Thanks!

**Comment by JuanitoFatas** [comment]
Hi @adlerhsieh!

First of all...Thanks for your kind words. :bow: This is the AMA for people in Ruby Taiwan community, not only for me hahaha!

> I believe only few companies in Taiwan are willing to hire a remote developer. That's not the culture. So how do you know there are companies that are looking for remote developers (either domestic or foreign companies) ?

Actually I don't know much about the remote situation in Taiwan! I work for a company called [Jolly Good Code](http://www.jollygoodcode.com) in [little red dot](https://en.wikipedia.org/wiki/Little_red_dot).

> Working remotely means the employers' trust in one's attitude and ability. If you're hiring a remote developer for your company, what qualities or skills do you expect from a candidate (as a Rails developer or system operator) ?

For me I think the most important thing is trust, asynchronous communication. I gave a talk list some criterias [here](https://speakerdeck.com/juanitofatas/remote-work-office-not-required). And there are so many skills and qualities already explained way better than me. You can check book like [Rework](https://37signals.com/rework/), [Remote](http://37signals.com/remote/), and so many great [posts](https://www.google.com.tw/search?safe=off&es_sm=119&q=remote+work+site%3Amedium.com&oq=remote+work+site%3Amedium.com&gs_l=serp.3...4638.7569.0.7739.15.11.4.0.0.0.72.591.11.11.0....0...1c.1.64.serp..15.0.0.I530iAeV7jc) already covered.

Also I know there is a new book called: [Remote Job Seekers](http://cobyism.com/remotejobseeker/), you can buy the book and ask the author more questions! Generally if you kindly ask on Twitter / Email, people are very willing to answer your question or point you to the resources they know.

And there are some great curated list of resources, check [them](https://github.com/greatghoul/remote-working) [out](https://github.com/juanitofatas/remote).

My friend laura gave a talk about [working remotely as a junior developer](https://www.youtube.com/watch?v=XdFY-zpT4JY) may give you some insights, too.

Ok. All these still does not solve your important question: how to find a job? Either...

1. [Persuade your employer](https://github.com/holman/ama/issues/383)
2. Try to get a remote job from many job list boards
3. Go to conferences, meet people
4. Start from freelance or contract work first

Hope this helps!

**Comment by adlerhsieh** [comment]
Wow that's really a lot of resources. I've checked some and they're really awesome. Looks like this a big issue for employers in project management or even running a company; and for employees a total different culture to adapt. I will go through the resources and pick some to dig in. Thanks a lot!
