### ISSUE TITLE
想請教一下，如何讓表單的某個欄位又能下拉選擇又能輸入新的值？

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#70]
如題。假設一個客戶資料表(customers)好了，公司名稱(company)欄位裡面可能已經有『HTC、ASUS、Apple、Samsung』可以供下拉選擇，也可以輸入新的（例如：小米、華為），那 simple_form 表單應該如何設計？

**Comment by adlerhsieh** [comment]
Google `html input dropdown text`

**Comment by fisherliang** [comment]
可以參考這個：http://railscasts.com/episodes/57-create-model-through-text-field

**Comment by afgnsu** [comment]
To fisherliang,

搞定了，謝謝 ^_^

雖然視頻是舊版的，但是只要轉成Rails4的語法就可以正常運作了 :p

**Comment by afgnsu** [comment]
不好意思，想再問一下，如果要加入重複檢查的機制，我在Model 裡加入 validates :company, uniqueness: true

會發現一個問題，因為新增的公司名稱重複，所以該欄位就變成空白了！該如何避免呢？

以下是我自己想的解決方法，但應該是錯的 >"<

def check_customer_name
  customer_id ||= Customer.find_by_name(new_customer_name).id
end

![2015-10-30 13 18 21](https://cloud.githubusercontent.com/assets/7204469/10838988/ce21bea6-7f08-11e5-89d6-740a9514cdb8.png)
![2015-10-30 13 18 02](https://cloud.githubusercontent.com/assets/7204469/10838990/d25cbe6c-7f08-11e5-818e-35ab361bb67c.png)

**Comment by ilake** [comment]
看不懂問題，所以你不想要他空白，想給他值嗎？
所以你到底允不允許公司名稱重複呢？或者是某些條件允許重複？

**Comment by afgnsu** [comment]
To ilake：

(1). 該欄位不能為空白，也不能重複。validates :company, presence: true,  uniqueness: true
(2). 該欄位預設為下拉選單（例：HTC、ASUS、Apple），但也可以輸入文字（可以另外一個文字對話框），如果輸入文字時，會自動比對資料庫是否重複 (看來要用Ajax去做比對檢查)。

我目前遇到的問題是，(1) 都OK，但 (2) 輸入文字時，資料重複不會報錯，會直接儲存空白 :p
忘了補充，我不是直接存欄位，而是用另一個資料表 company:references 來關聯。

**Comment by ilake** [comment]
還是不是很懂，不過如果是該錯而沒錯，再怎樣也是可以自己寫個validation 去檢查你所謂該錯的部份吧

**Comment by zackexplosion** [comment]
+1

**Comment by sunkai612** [comment]
看起來重開問的問題似乎與 #74 重複
為了集中相關討論，因此結束此問題，後續相關討論請前往 #74  :smile:
