### ISSUE TITLE
獨立於Rails外的程式，如何丟任務給Rails sidekiq執行?

### ISSUE THREAD

**Issue by jcsky** [rubytaiwan/AMA#72]
我在 Rails 外，有個獨立的 listen.rb ，用來接收 API message訊息(xml)
listen.rb 目前是收到 xml msg就直接吐出 xml file
而我希望 listen.rb 在收到 message 後，能通知 Rails 去解析 xml 並更新database
(更進一步希望使用 ActionCable 更新 client 的頁面)

我目前的做法是在 Rails 中使用 sidekiq 
我在 app/jobs 寫了個 worker_job.rb 預期用來解析 xml 及更新 db
在Rails/controller 中 WorkerJob.perform_later 能夠順利將任務排入Sidekiq
想說在 listen.rb 中做一樣的事，把任務排入 Sidekiq 就能由 Rails worker_job.rb 去執行了

可是我不曉得 listen.rb 應該怎麼丟任務給 Sidekiq ~??

想請問我現在的方向對嗎?? 或是有沒有其它的方式可以達成這需求??

**Comment by jcsky** [comment]
我在這裡找到了 How do I push a job to Sidekiq without Rails?
https://github.com/mperham/sidekiq/wiki/FAQ
實作起來沒有發生錯誤，但redis server / sidekiq server 都沒有任何動作

```
require 'securerandom'
require 'json'
require 'redis'
redis = Redis.new(:url => 'redis://127.0.0.1:6379/0')
msg = { 'class' => 'RestfulWorkerJob', 'args' => [], 'jid' => SecureRandom.hex(12), 'retry' => true, 'enqueued_at' => Time.now.to_f }
redis.sadd("namespace:queues", "default")
redis.lpush("namespace:queue:default", JSON.dump(msg))
```

而且這邊的msg只有指向Worker, 要如何讓sidekiq知道我希望執行 worker 中的 perform 呢??

**Comment by adlerhsieh** [comment]
我沒用過`sidekiq`，憑自己的經驗想到兩個建議：

如果沒有特別要使用到排程、背景作業功能的話，我會建議可以`listen.rb`接收到資料的當下直接執行command line指令例如

``` ruby
%x[rake task]
```

就可以執行塞入DB的指令。

如果有用到的話，可以讓這個`listen.rb`送出一個HTTP POST request至你的Rails app中，讓他來將要執行的內容塞到sidekiq，與Rails整合的資源應該有比較多可以查得到。

**Comment by jcsky** [comment]
rake task是在Rails app/lib/tasks中寫個 stream_async.rake 嗎?

```
# rails_app/lib/tasks/stream_async.rake
namespace :stream_async do
  task :api => :environment do
    logger.info "hello~~~~~~~~"
  end
end
```

listen.rb檔案要放在哪裡才能執行 rake task??
這麼寫嗎? `%x[rake stream_async:api]`

**Comment by adlerhsieh** [comment]
寫法沒錯，放在哪都ok，可以直接指定Rails專案底下的`bin/rake`路徑：

``` ruby
%x[/usr/project/bin/rake stream_asyc:api]
```

**Comment by jcsky** [comment]
我在irb下試會出現這樣的錯誤，是不是少了什麼?
%x[/Users/sky/project/donbest_api_receiver/bin/rake stream_asyc:api --trace]

```
rake aborted!
Don't know how to build task 'stream_asyc:api'
```

%x[/Users/sky/project/donbest_api_receiver/bin/ stream_asyc:api --trace]
%x[/Users/sky/project/donbest_api_receiver/bin stream_asyc:api --trace]
`Errno::EACCES: Permission denied - /Users/sky/project/donbest_api_receiver/bin`

**Comment by adlerhsieh** [comment]
咦？應該是可以才對，那如果改寫成以下方法試試看：

``` ruby
%x[rake -f /Users/sky/project/donbest_api_receiver/Rakefile stream_asyc:api]
```

**Comment by jcsky** [comment]
可以了，找到最後發現是我打錯字了... stream_async:api 才對

**Comment by jcsky** [comment]
另外，我也試了用 faraday 送 HTTP POST request 到 Rails app，也 OK ~!! 
謝謝 @adlerhsieh 的建議 ^^
讓我學了直接執行 rake task 的方式

**Comment by adlerhsieh** [comment]
:+1:
