### ISSUE TITLE
如何將 datetime_select 轉成多個 text_field 輸入

### ISSUE THREAD

**Issue by bugtender** [rubytaiwan/AMA#73]
嗨大家好

請問在edit page時，像下面這樣的datetime_selector

![Imgur](http://i.imgur.com/j0qA5ty.png)

要如何修改成像下面這樣，多個input 的text field呢

![Imgur](http://i.imgur.com/wo4MRrx.png)

嘗試將datetime_select直接轉成 text_field，得到卻是一個input 裡面一串datetime
目前看起來似乎是要用一個一個input 去對時間格式的name
不知道這樣的思考方式對不對

謝謝大家

**Comment by hechien** [comment]
不好意思，想了老半天查了老半天卻也沒找到這種方式，所以勢必可能得用 `text_field_tag` 自己串了
串到後台的方式是

``` ruby
year = params[:year].to_i
month = params[:month].to_i
day = params[:day].to_i

date = "#{year}-#{month}-#{day}".to_datetime
```

可以用此方式試試，但要注意一下資訊安全的問題

**Comment by bugtender** [comment]
感謝 @hechien ,千萬別不好意思，很感謝您的回應
再嘗試了您說的方法之後，發現一些東西

如果說用datetime selector的話，仔細看在params中似乎會變成
time(1i), time(2i), time(3i), time(4i), time(5i)
分別對應年,月,日,時,分，那我們想辦法偽造一樣的params

所以直接將

```
form_for @list do |f|
     f.datetime_select :add_time 
```

改寫成

```
text_field_tag "list[add_time(1i)]",@list.add_time.year
text_field_tag "list[add_time(2i)]",@list.add_time.month
text_field_tag "list[add_time(3i)]",@list.add_time.date
text_field_tag "list[add_time(4i)]",@list.add_time.hour
text_field_tag "list[add_time(5i)]",@list.add_time.min
```

很意外的是，rails就會把它當成是正確的datetime格式進去
也很順利的update成功
所以我想應該是最接近我需要的解法了，謝謝您！
