### ISSUE TITLE
請教一下，如何在表單的文字欄位裡加入Ajax比對是否與資料庫已經重複？

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#74]
如題，我希望焦點離開時就會做，該如何實做？這樣就不煩惱『當沒有得下拉選擇而新增時』出錯。

**Comment by zackexplosion** [comment]
onchange 應該可以幫你解決這問題
http://www.w3schools.com/jsref/event_onchange.asp

**Comment by adlerhsieh** [comment]
可利用jQuery設定該物件blur時就發post request出去，在後端比對。
Blur: http://www.w3schools.com/jquery/event_blur.asp
Ajax: http://api.jquery.com/jquery.ajax/

**Comment by chinghanho** [comment]
**Client**

離開焦點用 `blur`，輸入時邊檢查用 `onchange`；如果是後者最好加個 `debounce` 或 `throttle` 減少查詢浪費。

**Server**

資料已經存在，回個狀態 403，看需不需要把原因隨 body 傳回 client 去顯示。如果還不存在，回個狀態 200 即可。

**Comment by afgnsu** [comment]
chinghanho: 
   你講得很清楚，我聽的有點模糊 XD

   請問有沒有Gem套件可以直接引用？ 我是有找到一個 gem 'client_side_validations'
   不過又好像不完全適用 :P

**Comment by chinghanho** [comment]
**Client**

jQuery + [lodash](https://lodash.com/).

這段當然還需要再調整，避免一些 request 異步造成的問題，但是概念大概是這樣吧……

``` js
$('.js-input').on('change', _.debounce(checkUser, 150))

function checkUser() {
  var req = $.ajax()...
  req.fail(function (xhr, status, err) {
    // error handler...
  })

  req.done(function () {
    // success...
  })
}
```

**Server**

`UsersController`:

``` ruby
user = User.find(params[:id])
user ? head 200 : head 403
```

**Comment by afgnsu** [comment]
To chinghanho：

謝啦，看不懂，我再研究看看好了 ^_^

**Comment by hechien** [comment]
@afgnsu 哪裡看不懂

**Comment by afgnsu** [comment]
To hechien：

歹勢，我跟Ajax不熟 :p

**Comment by hechien** [comment]
@afgnsu 所以是 JavaScript 那邊看不懂？

**Comment by chinghanho** [comment]
哈哈哈哈，OK，既然回答了那我就再寫清楚一點吧！

如果對 Javascript 不熟那我就不要用太多奇怪的東西來干擾，重新把流程簡化一下，加上註解看看這樣有沒有比較容易理解：

HTML 部分很單純，只是加上一個用來抓 DOM 的 class：

``` erb
<%= text_field_tag :name, class: "js-input" %>
```

Javascript 部分：

``` js
var $input = $('.js-input') // 抓輸入框

$input.on('change', checkUser) // 在輸入時執行 `checkUser` 也就是下面這個 function

function checkUser() {

  // POST 一個 Ajax request 到 /users/check，資料為 input 輸入框的值
  $.ajax({
    url: '/users/check',
    method: 'POST',
    data: $input.val()
  })

  // 當回傳的狀態是 2xx 例如 200，也就是資料沒有重複的話則執行：
  .done(function () {
    // 例如，可以在輸入框附近加個綠色溝溝的 icon 之類的？
    // 如果沒有要做 UI 上的處理，這裡就什麼都不用寫囉。
  })

  // 當回傳的資料是 4xx 例如 403，表示 server 檢查發現資料重複了，則執行：
  .fail(function () {
    // 例如，可以在輸入框附近加個紅色叉叉的 icon 之類的？
    // 或是把輸入框加上一些變色的 class，
    // 或者是把表單的 submit 按鈕鎖住（加上 `disabled` 屬性）。
  })

}
```

server 端應該 OK 吧？就是接收處理，然後依據傳來的 `params` 去 model 找一次資料，找到就回傳 403，沒找到就回傳 200。

大概就這樣。 :smile:

**Comment by sunkai612** [comment]
@afgnsu 請問這樣問題是否解決了呢 :smiley: ?

**Comment by afgnsu** [comment]
Sorry... 最近比較忙，請再給點時間研究。
