### ISSUE TITLE
請教一下nested_form的使用

### ISSUE THREAD

**Issue by eric0324** [rubytaiwan/AMA#77]
大家好，請教一下各位。

我想做一個待辦事項清單，在 new 的時候，清單中要一次增加許多待辦事項；之後可以在 edit 點選完成的待辦事項；然後可以在 show 的地方顯示完成進度條。

我的想法是先裝了一個 gem "nested_form"，new的時候，去 count 有多少筆事項被記錄然後存下來，之後只要完成待辦事項就去減掉，我是不是應該在 `create` 的時候去 `@event.task.count` 然後存起來？

```
def create
  @Event = Task.new(event_params)
  respond_to do |format|
    if @event.save
      format.html { redirect_to @event, notice: '新增完成' }
      format.json { render :show, status: :created, location: @event}
    else
      format.html { render :new }
      format.json { render json: @event.errors, status: :unprocessable_entity }
    end
  end
end
```

`@event.task.count` 該如何儲存起來，之後讓 edit 和 show 可以去抓他？
我不知道該這樣實作好嗎？還是說有更好的做法？

謝謝大家。

**Comment by AnNOtis** [comment]
`nested form` 在這個功能上不是必須的，可以參考一下 Rails 的 `counter cache`。

**Comment by eric0324** [comment]
@AnNOtis 因為我想要在待辦事項清單，可以在清單中一次增加許多待辦事項，所以才用了nested form。

所以我只要在我的 task 做 counter_cache 就可以了？

還有，因為是要做一個完成進度條，那我要怎麼去把這紀錄去和之後紀錄去做比較？

抱歉，新手問題有點多:P

**Comment by AnNOtis** [comment]
我瞭解你的意思了 :smile: 

你只需要將 task 多加一個欄位 `is_completed` 紀錄 task 是否完成，已完成就更新 `is_completed`。

在 show 的頁面，把 event 下的 task 全部取出來，就是所有的代辦事項。 未完成的代辦事項只要找出  `is_completed` 為 `true` 的就行了。

**Comment by eric0324** [comment]
@AnNOtis 喔喔我理解了，謝謝你為我解惑了 :smiley:
