### ISSUE TITLE
我要怎麼樣在 Github 上面輸入小圖示，應該說要怎麼知道那些圖示要輸入什麼？

### ISSUE THREAD

**Issue by puff-tw** [rubytaiwan/AMA#78]
我要怎麼樣在 Github 上面輸入小圖示，應該說要怎麼知道那些圖示要輸入什麼？

如這種小圖 :+1:   輸入冒號 : 才會跳出來 

它有那種一次秀出來讓我選的方式嗎？

**Comment by zackexplosion** [comment]
我是都看這個

http://www.emoji-cheat-sheet.com/

**Comment by JuanitoFatas** [comment]
Copy-paste unicode: https://github.com/muan/mojibar (OS X menubar app)
Copy-paste emoji text (`:+1`): http://www.emoji-cheat-sheet.com/

**Comment by puff-tw** [comment]
感謝 @zackexplosion  @JuanitoFatas  很有幫助。
