### ISSUE TITLE
要怎麼知道我寫的 Rails 程式是不是 thread safe？

### ISSUE THREAD

**Issue by puff-tw** [rubytaiwan/AMA#79]
要怎麼知道我寫的 Rails 程式是不是 thread safe？

https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server
這篇文章裡面有一句話

>  If your app is not thread safe, you will only be able to use workers. Set your min and max threads to 1
> $ heroku config:set MAX_THREADS=1

可是我 puma.rb 設定是按照它的方式設定，照理說是
MAX_THREADS  = 5

所以我該如何檢查 thread safe 呢？

**Comment by tka** [comment]
如果不是一定要用 puma 的話, 個人建議是換成 unicorn 

關於 thread safe 的部份可以參考下面兩個連結

ref. 
1. https://bearmetal.eu/theden/how-do-i-know-whether-my-rails-app-is-thread-safe-or-not/
1. https://github.com/rails/rails/issues/20490  Rails.logger log level is not thread safe
    \* 之前踩到過一次相關的問題後, 目前不相信 rails 是 thread safe 這件事 XD

**Comment by puff-tw** [comment]
感謝 @tka  的熱心回覆，我會考慮的。
