### ISSUE TITLE
請問有定期的 Ruby/Rails 社群活動嗎？

### ISSUE THREAD

**Issue by viflin** [rubytaiwan/AMA#8]
感謝大家回答，將問題直接變成公佈欄

**台北**

**[Rails Taiwan Meetup](http://www.meetup.com/rails-taiwan/events/225557431/)**
  - 每週二 晚上07:30
  - 在 Deroot 休閒空間 （新生南路一段60號B1，捷運忠孝新生站五號出口）

**[Rails 新手村](https://www.facebook.com/groups/RailsRookie/)**
  - 每週四 晚上07:30
  - 在 Deroot 休閒空間 （新生南路一段60號B1，捷運忠孝新生站五號出口）
  - [Slack](https://rails-rookie.herokuapp.com/)

**[Ruby Tuesday](http://rubytaiwan.kktix.cc/)**
  - 偶爾會舉辦

**[Taipei.rb](http://blog.eddie.com.tw/2014/03/03/taipei-ruby-group/)**
  - 只辦過一次

**桃園**

**[桃園Ruby on Rails讀書會](https://www.facebook.com/groups/tyror/)**
  - 每月第一、三週六上午10-12點 （遇連假若更動會提前告知）
  - 地點在桃園市中壢區環北路398號5F-7 (中壢區公所旁，慈惠三街口）

**高雄**

**[高雄 Rails Meetup](https://www.facebook.com/groups/569223303140308/)**
  - 每週三 (7:00 PM - 10:30 PM) 
  - 於左營 Kakaja 咖啡廳舉辦
  - [Slack](https://rails-kh.herokuapp.com),[Meetup](http://www.meetup.com/rails-taiwan/events/200720642/)

**Comment by JuanitoFatas** [comment]
高雄 Rails [Meetup](http://www.meetup.com/rails-taiwan/events/225254421/)，[Facebook Group](https://www.facebook.com/groups/569223303140308/)。

**Comment by JuanitoFatas** [comment]
偶爾有 Ruby Taiwan Meetup & 只辦過一次的 Taipei.rb。

**Comment by afgnsu** [comment]
【桃園Ruby on Rails讀書會】
時間：每月第1、3週六上午10-12點 （遇連假若更動會提前告知）
地址：桃園市中壢區環北路398號5F-7 (中壢區公所旁，慈惠三街口）
FB社群：https://www.facebook.com/groups/tyror/

**Comment by viflin** [comment]
感謝 @JuanitoFatas 跟 @afgnsu 提供資訊，已更新最上面的問題了

**Comment by JuanitoFatas** [comment]
移到 [Wiki](https://github.com/rubytaiwan/rubytw-reboot/wiki/Meetups) 吧，有新的或是變動歡迎去 Wiki 更新。

**Comment by chitsaou** [comment]
建議可以之後放在 rubytaiwan/taipei 或 rubytaiwan/rubytw-reboot

**Comment by JuanitoFatas** [comment]
> 建議可以之後放在 rubytaiwan/taipei 或 rubytaiwan/rubytw-reboot

:+1: https://github.com/rubytaiwan/taipei#ruby-meetups

**Comment by leo424y** [comment]
ROR台中也在運作中囉! 歡迎中部的朋友們共聚
https://www.facebook.com/groups/RORTaichung/
