### ISSUE TITLE
升級OS X El Capitan問題?

### ISSUE THREAD

**Issue by sophia1215** [rubytaiwan/AMA#80]
請問 MBPR Yosemite 10.10.5 如果升級到 OS X El Capitan, 
原本 local 端的 Ruby on rails 專案會不會有問題？

**Comment by bugtender** [comment]
我的情況是，不會有問題。

#我的看法啦

**Comment by ihower** [comment]
homebrew 會有問題: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md

**Comment by yorkxin** [comment]
我直接升級了，沒問題。

**Comment by puff-tw** [comment]
我前天剛升級，目前使用正常。

**Comment by hrs113355** [comment]
直接升級了，brew 需要修正，Ruby 或 Rails 的部分沒問題
