### ISSUE TITLE
同時對一筆資料做 update 造成的 lock ，Rails 有什麼樣的解法呢？

### ISSUE THREAD

**Issue by puff-tw** [rubytaiwan/AMA#81]
同時對一筆資料做 update 造成的 lock ，Rails 有什麼樣的解法呢？

一個說明的例子如下 : 
假設有兩個 User 分別為 A 和 B ，在購物車裡都買了1個 Product C ，並且同一時間要做結帳。
基本上 Product C 這筆資料的數量為 10 會減少為 8。
但是因為同時要做結帳的動作的關係，所以會對資料表 Product 裡的那筆 Row 叫 C 的做 update。
所以會產生兩筆 update -1 去搶 Product C 的資料。

**Comment by ihower** [comment]
http://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html 或 http://api.rubyonrails.org/classes/ActiveRecord/Locking/Optimistic.html

**Comment by puff-tw** [comment]
感謝 @ihower 的資訊，另外我想請問，有什麼方式可以去 reproduce  這種問題？

**Comment by ihower** [comment]
1. 開發環境不要用預設的 webrick 是 single process，會測不出來。建議可以用 puma 或 passenger standalone 
2. 也不要用 SQLite，它沒有支援 SELECT..FOR UPDATE 語法。用 mysql 或 postgresql
3. 埋個 sleep(10) 在 code 裡面，然後同時操作兩個瀏覽器(或 rails console)就可以模擬了

**Comment by puff-tw** [comment]
瞭解，然後我有想過避免 Lock 的方式

如果是做 insert 的話，就不會有 lock 的問題，可以一直 insert。

所以可以用 insert 的方式，假如他要做 update 其實他是先做 insert ，
1 ) 然後把 insert 最後的記錄補在 update 那邊。
2) 或者是乾脆就沒有 update ，每次取都是拿 insert 最新的那筆。

不曉得這種方式，還有沒有其它做法或建議。

**Comment by ihower** [comment]
我推薦 Xavier Shay 的 Your Database Is Your Friend 課:
- https://www.codeschool.com/pluralsight-courses/your-database-is-your-friend 
- 或 http://www.pluralsight.com/courses/database-your-friend 

有一整章在講 Database Concurrency 問題，而且範例是 Rails。看完你就會很清楚了解使用 lock 的來龍去脈。

**Comment by puff-tw** [comment]
非常感謝 :+1:
