### ISSUE TITLE
RAILS_ENV=production bundle exec rake assets:precompile fail

### ISSUE THREAD

**Issue by crsgypin** [rubytaiwan/AMA#83]
我使用 capistrano 方式部署我的code到server上，
之前部署幾十次都可以成功，但這次做了一些修改之後，當跑到 assets:precompile 的時候，出現失敗訊息如下。

```
INFO [3118eb42] Running bundle exec rake assets:precompile as deploy@139.162.11.161
DEBUG [3118eb42] Command: cd /home/deploy/myeyehouse/releases/20151110151903 && ( RAILS_ENV=production bundle exec rake assets:precompile )
DEBUG [3118eb42]    rake aborted!
DEBUG [3118eb42]    ExecJS::ProgramError: Unexpected token punc «(», expected punc «:» (line: 14658, col: 15, pos: 511716)
DEBUG [3118eb42]
DEBUG [3118eb42]    Error
DEBUG [3118eb42]        at new JS_Parse_Error (/tmp/execjs20151110-9829-ljodgjjs:2659:11936)
DEBUG [3118eb42]        at js_error (/tmp/execjs20151110-9829-ljodgjjs:2659:12155)
```

這次的修改我修改許多 javascript 檔案，大概新增了六個檔案。
從 log訊息來看，似乎是14658行code 不能使用 "(" 需要使用 ":" ，即是語法的問題
問題是，我在本機端跑的時候，似乎沒什麼大問題，本機上執行 rake assets:precompile 也可以成功。
比較想知道的是，是否有什麼方式可以快速找到是哪一行出的問題。從上面 log 提到是 14658行有問題，可以要到哪去找這個檔案呢？

另外，做了一些測試有發現，我的 application.js 檔案

``` javascript
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require jquery.remotipart
//= require jquery_nested_form
//= require jquery-ui/draggable
//= require js/eo_pano.js
//= require js/user.js
//= require faye
//= require_tree .
```

將 js/eo_pano.js 與 js/user.js 檔案移除的話，就可以正常 precompile
只是我會加入這兩行，主要是希望讓本機端的 javascript 載入順序可以依照我想要的順序去執行
先載入這兩個檔案，可以讓後面js檔案使用
如果移除這兩行的話，會出現後面的js來不及讀取這兩個檔案的問題

但我在想這個為何會與precompile 有衝突勒？

version:
本機端
Rails 4.2.2
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

server 端
Rails 4.2.2
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

Derek Chiu

**Comment by zackexplosion** [comment]
你在本機上執行時，也有加上 RAILS_ENV 嗎？

```
RAILS_ENV=production bundle exec rake assets:precompile
```

**Comment by chinghanho** [comment]
瞎猜，是用了 ES6 的語法嗎？ :stuck_out_tongue:

**Comment by crsgypin** [comment]
OK，參照  zackexplosion 建議
本機上，不能跑 RAILS_ENV=production bundle exec rake assets:precompile 指令，後來查到是因為 fog 的設定問題
然後跑 RAILS_ENV=production bundle exec rake assets:precompile 這之後，也會發現失敗，
之後用一個檔案一個檔案刪除的方式來找問題，結果找到了
原因：我在  hashtable 上直接使用 hash = {aa(){ xxxx}} 語法，用瀏覽器則讀得懂這語法(等同於 hash = {aa: function(){xxxx}} ，但會導致 assets precompile 失敗。
不過，如果執行 bundle exec rake assets:precompile 還是可以成功。

**Comment by zackexplosion** [comment]
因為你沒下 RAILS_ENV=production， 預設就會用 developer 環境，所以我在猜，你是有些設定在 production 環境沒設定好。

**Comment by crsgypin** [comment]
如果要研究設定的話 是研究哪個設定檔呢？

**Comment by zackexplosion** [comment]
方便把 Gemfile 貼上來嗎？ 有可能你把某些 gem 只裝在開發環境了

**Comment by crsgypin** [comment]
``` ruby
source 'https://rubygems.org'

gem 'rails', '4.2.2'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'devise'
gem 'omniauth-facebook'
gem 'remotipart', '~> 1.2'
gem 'capistrano-rails', :group => :development
gem 'capistrano-passenger', :group => :development
gem 'carrierwave'
gem 'rmagick'
gem 'fog'
gem 'rspec-rails', :group => [:development, :test]
gem 'mysql2'
gem "nested_form"
gem 'jquery-ui-rails'
gem 'delayed_job_active_record'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
```

**Comment by chinghanho** [comment]
`hash = {aa(){ xxxx}}` 是 ES6 的語法。

development 環境 precompile 不會做 uglify，所以沒事，反正瀏覽器也讀得懂 ES6 新語法，開發上也不會碰到問題。

換成 production 環境去 precompile 會做 uglify，可能是因為這樣碰到不認識的語法了，我不知道 sprockets 支援 ES6 了沒。

**Comment by zackexplosion** [comment]
這個 (/tmp/execjs20151110-9829-ljodgjjs:2659:11936) log 檔的 error 呢？

**Comment by crsgypin** [comment]
好像找不到這個檔案ㄟ
