### ISSUE TITLE
在專案中使用別人開發的gem的使用方式

### ISSUE THREAD

**Issue by water-su** [rubytaiwan/AMA#86]
各位前輩好，想請教一般在Rails專案開發時，基於不要重複開發輪子的原則，是否一般會建議盡量尋找適合使用的gem加以應用？
而倘若找到合適的gem之後，若因專案需求需要修改view、CSS、rb code或加入localization時，建議的作法會是:
1. clone目標gem，修改他的source，仍以gem的方式引入專案中
2. clone目標gem，將需要的source拉進自己的專案中融為一體的進行修改
3. 仍使用原publish的gem，但有某些方式可以overwrite？
想請教一般專案開發比較建議採用哪種方式進行整合，或各種方式適用的情境為何？
謝謝！

**Comment by imgarylai** [comment]
分享我的經驗
有些 gem 年久失修或是有部分的 dependency 需要升級，我會考慮第一種方法，然後再送 pull request 
但我想比較負責的是你說的第二跟第三種情況
我認為需要看是哪個 gem，有些可以讓 customization, overwrite 
有沒有遇到那個 gem 特別有問題的可以提出來討論喔

**Comment by ilake** [comment]
會一直需要改的，你用到原本gem的地方又多 => fork，弄自己的gem
會一直需要改的，你用到原本gem的地方很少 => 直接拿有用到的那段出來，弄自己的gem
不會需要一直改，你用到原本gem的地方又多 => 用原本的gem，在app裡overwrite 想改的部份
不會需要一直改，你用到原本gem的地方又少 => 不用gem了，在app裡直接拿那段出來改成自己要的

**Comment by water-su** [comment]
感謝二位的回答，我大致了解！
那另外想再請教，若對方的gem本身沒有支援多國語系，或說沒有支援中文，但我需要對它整個作中文化。此時是否就必須直接修改對方gem的source，加入i18n的支援，或直接針對顯示文字改為我需要的語言。
這個部分是否還有某種奇妙的作法，可以用外加的方式達成的嗎？
再次感謝謝各位前輩的熱心回覆！

**Comment by ilake** [comment]
他本身沒有支援i18n 就是沒有，你頂多就是看它message的部份有沒有辦法自己設定，不然就是自己弄了。

**Comment by water-su** [comment]
了解！感謝前輩的熱情回應！
