### ISSUE TITLE
如何限制網站只限台灣人使用??

### ISSUE THREAD

**Issue by jcsky** [rubytaiwan/AMA#87]
目前想到的是 ip 白名單，有推薦的 gem 可以使用嗎??
除此之外，是否有其它方法??

**Comment by puff-tw** [comment]
以前我是從路由器層做掉，把那個國家的 ip range 加到路由器 config 裡面。

**Comment by jcsky** [comment]
我server放在 Linode, DigitalOcean, or AWS EC2 的話，有路由器 config 這東西嗎??

**Comment by Vdragon** [comment]
能不能透過排除掉所有偏好語系不是 zh_TW 的 Web 瀏覽器來辦到？

**Comment by puff-tw** [comment]
這篇是用 AWS 的 Route 53 來達到目的
http://serverfault.com/questions/585189/can-aws-block-access-from-embargoed-countries

**Comment by jcsky** [comment]
得到了許多方法，謝謝大家!!
