### ISSUE TITLE
Undefined variable: "$alert-padding"

### ISSUE THREAD

**Issue by koei1025** [rubytaiwan/AMA#88]
開啟Application時會顯示Undefined variable: "$alert-padding".的錯誤

![_004](https://cloud.githubusercontent.com/assets/12932473/11230700/f9fd535a-8ddb-11e5-908f-c42b3459ce1b.png)

我懷疑可能是precomplie設定的問題，google了兩篇文章，但說的狀況跟我的也不太一樣，也仍然無法解決問題
https://github.com/twbs/bootstrap-sass/issues/863
https://stackoverflow.com/questions/21911620/rails-bootstrap-sass-assets-compilation-error-undefined-variable-alert-padding/21935120#21935120

我的gem file內容

```
source 'https://rubygems.org'
gem 'rails', '4.2.4'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bootstrap-sass'
gem "compass-rails", "~> 2.0.4"

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
```

application.css.scss

```
/*
 *
 *= require_tree .
 *= require_self
 */
@import "bootstrap-sprockets";
@import "bootstrap";
@import 'flatty/theme-colors';
@import 'flatty/bootstrap/bootstrap';
@import 'flatty/plugins/plugins';
@import 'flatty/jquery/jquery_ui';
@import 'flatty/light-theme';
```

**Comment by koei1025** [comment]
我的source code為
https://github.com/koei1025/flatty_test

**Comment by imgarylai** [comment]
看了一下你的 code 你的目的是客製化自己的 Bootstrap 樣式吧？

這是我的經驗：

`application.scss` 的結構：

``` scss
@import "bootstrap-sprockets";
@import "bootstrap_variables";
// 如果有需要修改 bootstrap 的變數才需要加上面這行，補充 1. 
@import "bootstrap";
@import "bootstrap_override";
// 如果有需要覆寫 bootstrap 樣式才需要加上面這行，補充 2. 
```

補充：
1. 客製化 bootstrap 的變數

新增 `app/assets/stylesheets/_bootstrap_variables.scss`
然後找到 bootstrap 對應版本的變數檔案貼上 
example: https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss

就可以修改自己要的變數
1. 覆寫掉 bootstrap 原本的樣式

新增 `app/assets/stylesheets/_bootstrap_override.scss`
舉例：在檔案裡面新增

```
.form-control {
  border: 4px solid red;
}
```

即可覆寫掉原本 bootstrap `.form-control` 的樣式

這樣就不需要把bootstrap的所有程式碼加近來

**Comment by koei1025** [comment]
@imgarylai 感謝回覆的這麼詳細。
我現在還是Rails菜鳥，沒那麼強可以去客製自己的 Bootstrap 樣式。
會有這個問題是因為我在Wrapbootstrap買了一個Template，按文件操作而已。
http://www.bublinastudio.com/flattybs3/docs/get_started.html

**Comment by chinghanho** [comment]
只看這邊的話覺得很奇怪：

``` scss
@import "bootstrap-sprockets";
@import "bootstrap";
@import 'flatty/bootstrap/bootstrap';
```

**Comment by koei1025** [comment]
```
@import "bootstrap-sprockets";
@import "bootstrap";
```

這個部份是我自己加上去的，後來發現重複import了，GitHub上的版本已經拿掉

**Comment by koei1025** [comment]
感謝各位的回覆，問題已經解決了
解決的方式對老手可能很簡單，但對菜鳥我而言其實滿曲折的，因此可能也不適用在其他人的身上，但還是紀錄一下原因
1.因為是套用Template，已經有自帶的Assets，包內已經有包含JQuery跟Bootstrap等套件
2.在自動生成的application.js基礎上添加Template的Javascript，導致JQuery衝突
3.相同的在application.css.scss也發生跟application.js同樣的事

解決方式
把application.js與application.css.scss原有import的清除乾淨
