### ISSUE TITLE
想請教一下 Rails 4.2 的環境參數設定

### ISSUE THREAD

**Issue by afgnsu** [rubytaiwan/AMA#9]
RAILS 4.2把一些關鍵參數設定為 <%= ENV['DATABASE_PASSWORD'] %>
<%= ENV['DATABASE_URL'] %>... 之類的，究竟應該設定在哪裡？

以 Ubuntu Desktop 為例，是不是設定在 ~/.bashrc 底下？ 
就直接下 DATABASE_PASSWORD = '123456'

**Comment by tsechingho** [comment]
你可以試試 https://github.com/bkeepers/dotenv

**Comment by viflin** [comment]
你可以試試看 [Figaro](https://github.com/laserlemon/figaro)
要自行定義ENV的話，這個很方便

**Comment by CarolHsu** [comment]
[Figaro](https://github.com/laserlemon/figaro) +1

**Comment by adlerhsieh** [comment]
我試過幾個方法，Figaro的好處是可以加入`.gitignore`以免敏感資料曝光。我個人比較不喜歡用`ENV`這個變數，比較不敏感的資料會丟到`config/initializers`資料夾底下另外開一個檔案，裡面用一個class包起來，用起來還算順手，例如：

```ruby
module Business
  class Logic
    Here = "hello world"
  end
end

# 在app任何地方使用
Business::Logic::Here
# => "hello world"
```

其他方法可以參考[之前寫的心得](http://motion-express.com/blog/global-variables-in-rails-4)。

**Comment by JuanitoFatas** [comment]
@afgnsu 上面的回答有解決你的問題了嗎？:blush:

**Comment by afgnsu** [comment]
Very Good，謝謝大家 ^_^
