### ISSUE TITLE
如何在前端得知目前有無登入？

### ISSUE THREAD

**Issue by aiueoH** [rubytaiwan/AMA#92]
請教各位先進

我的網頁需要一個類似購物車的功能，當未登入時會將資訊儲存在 cookie，登入後會將資訊用 ajax 送到後端。該如何在前端 js 部份判斷現在有沒有登入呢？

目前找到、想到的方法有

1.在後端若有登入就輸出一段 js code
var login = true

2.登入後在後端設定 cooike[islogin] = true

想請教各位在 rails 有沒有更好的方法，謝謝！

**Comment by zackexplosion** [comment]
你可以直接用 JS 讀 cookie，不過，千萬別相信前端進來的資料

**Comment by aiueoH** [comment]
謝謝提醒

目前我是採用在 application_controller 寫一段設定 cookie 的 action，並設定 before_action 執行
