### ISSUE TITLE
heroku custom domain設定好，出現不安全的瀏覽警告

### ISSUE THREAD

**Issue by hungmi** [rubytaiwan/AMA#93]
我目前在taiwandns購買了一個xxx.com.tw的網址，已經加到heroku app的custome domain中，
不過連上之後出現此為不安全的瀏覽警告的紅色頁面，似乎與我用devise強制全站ssl有關係，
但我試過ssl必須開啟，fb登入才不會有問題
想請教該如何正確設定轉址呢？
目前設定是

| Host | URL | RecordType |
| --- | --- | --- |
| www | xxx.herokuapp.com | CNAME(Alias) |

**Comment by motephyr** [comment]
設定SSL應該要和第三方申請憑證哦，這樣在browser認證才會過。

**Comment by dlackty** [comment]
可以試試 CloudFlare 的免費 SSL，設定方法可以參考[這篇網路上的文章](https://sofree.cc/cloudflare-free-ssl/)。

**Comment by imgarylai** [comment]
之前我也用過 CloudFlare 的 SSL 但 windoews XP 好像不支援XD
一天內被好多客人反應
