### ISSUE TITLE
如何用一對多的對象的內容來排序並作分頁？

### ISSUE THREAD

**Issue by MitsunChieh** [rubytaiwan/AMA#95]
Topic has_many Replies
Reply belongs_to User

我希望能把該 User 還沒回覆過的 Topic 排在前面，已回覆過的在後面。一種解法是分開處理再混合成陣列。但如果我希望整個提取出來的物件序列仍能做 paginate，是否表示該物件序列仍需是個 ActiveRecord 類別的實例？並且我該如何達到這件事呢？

又如果我希望還沒回覆/已回覆兩個組別內的 Topic 各自是隨機排序的，Query 該當如何處理？

這是我用來提取沒回應過的 Topic 的 Query，或許也更好的寫法，也希望獲得指教。

```
no_reply_topics = Topic.joins('LEFT JOIN replies ON replies.topic_id = topics.id').where('replies.id IS NULL OR replies.user_id != ?', current_user).published.order("RAND()")

no_reply_topics_ids = no_reply_topics.pluck :id
replied_topics = Topic.where.not(id: no_reply_topics_ids).published.order("RAND()")

topics = no_reply_topics | replied_topics
```

然而這樣的 `topics.class #=> Array`，無法用 kaminari 做分頁

**Comment by ilake** [comment]
https://github.com/amatsuda/kaminari#paginating-a-generic-array-object

**Comment by MitsunChieh** [comment]
謝謝 @ilake
