### ISSUE TITLE
如何在跑 feature tests 的時候還能 inspect Model 或 Controller 裡的變數？

### ISSUE THREAD

**Issue by festime** [rubytaiwan/AMA#96]
我的一個 feature test 大致長這樣

``` ruby
feature '' do
  let!(:user) do
    create(:user, :signed_in_with_fb)
  end

  scenario '' do
    OmniAuth.config.mock_auth[:facebook] = {
      provider: 'facebook',
      uid: 'facebook-user-uid',
      credentials: {
        token: 'facebook-token'
      }
    }

    visit root_path
    click_link "Facebook 登入", match: :first

    save_and_open_page
    binding.pry
  end
end
```

我現在卡在 `/users/auth/facebook/callback` 這個 URL ，在 feature test 裡放 `binding.pry` 和 save_and_open_page 無法給出更有用的訊息，我想如果可以檢查相關的 controller 或 model 裡面的變數值應該會很有用，可是：
1. 我在相關的 model 或 controller 裡放 `binding.pry` 並沒有在跑 feature test 時停住，請問這是什麼原因呢？
2. 有辦法在跑 feature test 時去檢查 controller 或 model 裡的變數值嗎？
3. 是不是因為 rspec 在跑這段 feature spec 時是開另一個 process 去載入 Rails 環境之類的，造成這問題？

**Comment by zackexplosion** [comment]
正常來說有跑到應該就會斷，你有辦法確定有跑到嗎？

**Comment by festime** [comment]
@zackexplosion ，看起來是我 `OmniAuth.config.mock_auth[:facebook]` 那邊設定有些問題，我改了之後有跑出預期的結果，之後放在 controller 的 binding.pry 也有停住，謝謝

**Comment by zackexplosion** [comment]
:+1:
