### ISSUE TITLE
請問關於grub rescue的問題

### ISSUE THREAD

**Issue by sophia1215** [rubytaiwan/AMA#97]
最近桌機(ubuntu 14.04 LTS)反應變慢，昨天重開機之後出現：
error:attempt to read or write outside of disk ‘hd0’
Entering resource mode…
grub rescue>

重灌之後的時間驚人！竟然灌到早上，然後畫面剩下背景色，不藍也不黑。
再重開機之後，依然是：
error:attempt to read or write outside of disk ‘hd0’
Entering resource mode…
grub rescue>

然後google到一個可能的解決辦法：
http://askubuntu.com/questions/397485/what-to-do-when-i-get-an-attempt-to-read-or-write-outside-of-disk-hd0-error

於是照著做：
grub rescue > ls
(hd0) (hd0, msdos5)(hd0,msdos1)
grub rescue > ls (hd0)
grub rescue > ls (hd0,msdos5)
grub rescue > ls (hd0,msdos1) # suppose this is ubuntu
grub rescue > set root=(hd0,msdos1)
grub rescue > set prefix=(hd0,msdos1)/boot/grub
grub rescue > insmod normal
grub rescue > normal

開機選單出現了!!!
但是直接點進去，就沒畫面了，不知道大大們有沒有其他的解決辦法？

**Comment by Vdragon** [comment]
看起來像是硬碟壞軌
